### ISSUE TITLE
[iOS] Support dynamically transitionStyle and orientation change

### ISSUE THREAD

**Issue by linhmimoza** [callstack/react-native-pager-view#128]
# Feature Request
Please support dynamically transitionStyle change and orientation change

## Why it is needed
It can simulate the page flip action of a book more smoothly
For example: 
 Currently user is viewing first page of book
- Notice book is open on screen show you can see page 1, the spine of the book, and then part of page 2
- Swiping left brings page 2 (scroll effect)
- Swiping left again takes user to page 3 (curl effect)

**Comment by troZee** [comment]
Curl support has been dropped, hence I am closing this issue
