### ISSUE TITLE
Feature: Pull to Refresh

### ISSUE THREAD

**Issue by nnajiabraham** [callstack/react-native-pager-view#137]
# Feature Request

Hi team, I was wondering if this is in the plans for implementing a pull to refresh/reload feature where the children will get replaced/reloaded?

Currently using this great library for a video-pager where users swipe up/down to move to the next video and tried implementing a pull to refresh but it seemed impossible since it overlapped with the vertical swipe.

**Comment by sanborN93** [comment]
Would like to see it too.

**Comment by rizbud** [comment]
will be nice if this feature is implemented

**Comment by gulsher7** [comment]
needed

**Comment by ThanhNguyen140797** [comment]
+1

**Comment by johnrevs** [comment]
+1

**Comment by GabrielGhe** [comment]
+1

**Comment by milesscherrer** [comment]
+1

**Comment by alexandreaugus** [comment]
+1

**Comment by Vladimirrr666** [comment]
+1

**Comment by alecdewitz** [comment]
+1

**Comment by mehamednews** [comment]
+1

**Comment by LeviWilliams** [comment]
This doesn't seem like something that needs to be in the main pager view library, this can easily be implemented right now in numerous ways

**Comment by alexandreaugus** [comment]
> This doesn't seem like something that needs to be in the main pager view library, this can easily be implemented right now in numerous ways

Could you kindly share those ways? All that I've tried were very buggy and prone to issues. I bet most people requesting this feature have been through the same

Thank you

**Comment by troZee** [comment]
Closing, bc it should be supported inside a list component.

**Comment by ppegu** [comment]
![Screenshot 2023-04-23 at 12 36 50 PM](https://user-images.githubusercontent.com/45468555/233825286-a5813517-664a-413d-9f67-1d608d1fba29.png)


Here is an solution 😍😍
