### ISSUE TITLE
App Crash - UIViewControllerHierarchyInconsistency 

### ISSUE THREAD

**Issue by ozgursoy** [callstack/react-native-pager-view#167]
# Bug

When i open the app, it crashes sometimes ( %20 crash rate )
There is no log on console, Flipper can't catch any error, Only Crashlytics catches the error.

* Android is working very well.
* There is no problem on version 3.3.0

![Screen Shot 2020-05-05 at 17 21 56](https://user-images.githubusercontent.com/13810383/81078205-94eed300-8ef6-11ea-98ae-27accf694c4a.png)

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 162.63 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.0.0

**Comment by troZee** [comment]
It is strange, that iOS fixes does not work for you. 

You can checkout changelog here: 
https://github.com/react-native-community/react-native-viewpager/releases/tag/v4.0.0

Could you provide reproducible example code ? 

@krystiansliwa have you got any ideas ?

**Comment by farad4y** [comment]
Extra info:
We use [redux-offline](https://github.com/redux-offline/redux-offline). 
When i disable redux-online, works perfectly. 
This is really strange because there is no problem on version 3.3.0

**Comment by srfaytkn** [comment]
+1

**Comment by ahk093** [comment]
I have the same issue.

**Comment by troZee** [comment]
@srfaytkn @ahk093 Could you provide any reproducible example ?

**Comment by farad4y** [comment]
@troZee
I replaced childViewController.view = view;
to
[childViewController.view addSubview: view];
then issue is solved

I can't provide any reproducible example right now, i have to create a new project for this

**Comment by troZee** [comment]
@farad4y 
I checked 3 fixes, which has been included into 4.0 and I can't find any cause of above errors. 
It is hard to say without reproducible example, where the problem is. 

You can fix it now locally using patch-package. 

> I can't provide any reproducible example right now, i have to create a new project for this 
No worries :D I am waiting for reproducible example

**Comment by genglei01** [comment]
@troZee 
I  have the same issue and try  @farad4y's solution, the error seems to be fixed/(I try it many times)

> I replaced childViewController.view = view;
> to
> [childViewController.view addSubview: view];

**Comment by Inexpressible** [comment]
This error happens for us with screens that have multiple carousels. The suggested patch fixed the issue.

**Comment by farad4y** [comment]
@genglei01 @Inexpressible Could you provide example project? My project that crashes is very big, so i can't simplified it

**Comment by tekmin** [comment]
We had the same issue, but not reproducible from our project too. I will try on @farad4y solutions first.

**Comment by jpamarohorta** [comment]
I had the same issue and @farad4y patch fixed it. Here is the patch created using [patch-package](https://github.com/ds300/patch-package):

```
diff --git a/node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m b/node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m
index cbb3b36..d7e8893 100644
--- a/node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m
+++ b/node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m
@@ -379,7 +379,7 @@ - (void)setReactViewControllers:(NSInteger)index
 
 - (UIViewController *)createChildViewController:(UIView *)view {
     UIViewController *childViewController = [[UIViewController alloc] init];
-    childViewController.view = view;
+    [childViewController.view addSubview: view];
     return childViewController;
 }
```

**Comment by genglei01** [comment]
Is there any release schedule for this bug?

**Comment by troZee** [comment]
> Is there any release schedule for this bug?

I will merge and release it, once someone provides me an example to test it.

**Comment by jpamarohorta** [comment]
In my case the crash occurred 10% of the times this component was mounted (stats from Firebase), so it's difficult to track and make an example that always crashes.

**Comment by stami** [comment]
There may be a race condition causing this crash.

> UIViewControllerHierarchyInconsistency
> A view can only be associated with at most one view controller at a time!

In `ReactNativePageView.m` the `createChildViewController` is called with the **same array of UIViews** (`self.reactSubviews`) from `renderChildrenViewControllers` and `addPages`.

The @farad4y 's patch fixes the issue because `addSubView` [removes the previous superview if needed](https://developer.apple.com/documentation/uikit/uiview/1622616-addsubview) before adding it to the new superview.

**Comment by RodrigoSosa95** [comment]
+1 on this issue, even on version `4.1.0` happens to me when called `viewPager.current.setPage`.

**Comment by troZee** [comment]
It has been resolved here https://github.com/react-native-community/react-native-viewpager/pull/189 in 4.1.0 version.

**Comment by eladgel** [comment]
Has this been really fixed? Making sure before I upgrade my library. @RodrigoSosa95 ?

**Comment by chj-damon** [comment]
I'm facing the same problem. I'll try to upgrade the version and see if it's fixed.

**Comment by enigmablue** [comment]
Also faced the same problem. omg i hope this fixes. 

Now am on "@react-native-community/viewpager": "^4.1.3",

**Comment by troZee** [comment]
I reopening this issue, because bug still exist

**Comment by enigmablue** [comment]
Yes i'm getting the same error. But this time, it's not (randomly) killing the app completely, just consistently throwing an error. My current unglamorous workaround to fix the race condition is:

 ```
 let updatedShares = getUpdatedShares()

      setTimeout(()=>{
        setDisplayShares(updatedShares);
        }, 100) //needed to set timeout here because of some other issue on pausing video

        setTimeout(()=>{
          viewPager.current && viewPager.current.setPage(0)
        }, 200) //race condition problem with setpage

```

**Comment by troZee** [comment]
Can you try to change:
```js
   {displayList && displayList.map((share,index) =>
          renderSlide(share, index)
        )}
```
into: 
```
{ (displayList || []).map((share,index) =>
        renderSlide(share, index)
 )}
```

**Comment by enigmablue** [comment]
> ```
> { (displayList || []).map((share,index) =>
>         renderSlide(share, index)
>  )}
> ```

The thing is my displayList will never be empty because in my useState i set it. The props will always have a value. 

It is one of the conditions to come into this view in the first place. If its empty it shows a different view.

const [displayList, setDisplayList] = useState(loadDefault(props.shares));

**Comment by ZeroJian** [comment]
Also faced the same problem

**Comment by krystiansliwa** [comment]
@enigmablue Could you provide a minimal repro example? Without that it is very hard to reproduce that issue

**Comment by younes200** [comment]
Had also the same problem, used `requestAnimationFrame(() => refViewPager.current?.setPage(index));` to avoid the exception.

**Comment by enigmablue** [comment]
> @enigmablue Could you provide a minimal repro example? Without that it is very hard to reproduce that issue
sorry i haven't had a chance to try to do this yet. am working on a few priority items right now. 

-- on a separate note
Unfortunately i just hit the same 'multiple views' error on Android. Also random. :( And the weird thing was, the view which had the viewpager wasn't even rendered.

**Comment by ethanyuwang** [comment]
Had the same problem and younes200's workaround worked for me

**Comment by RobTS** [comment]
Also experiencing this on iOS. I tried reproducing in a sample project, but was not successful.

Here is a rough description of my setup:

I have a react-navigation TabNavigationController with three tabs, first and last have a ViewPager. Both use the same wrapper around ViewPager, with the following snippet:

```
  useEffect(() => {
    setPage(props.selectedTab);
    viewPager.current?.setPage(props.selectedTab);
  }, [props.selectedTab]);
```

On startup when the initial tab is the third one (I guess otherwise it just renders the first tab) I get the crash. However, I can fix it when replacing the above snippet with the following:

```
  useEffect(() => {
    setPage(props.selectedTab);
    setTimeout(() => {
      viewPager.current?.setPage(props.selectedTab);
    }, 50);
  }, [props.selectedTab]);
```

I hope this might help resolve the issue!

**Comment by krystiansliwa** [comment]
Thank you @RobTS, In free time I will take a look on it. So probably problem is because of using setPage during initialization process (when component is mounting and crating on native side)

**Comment by ramonvermeulen** [comment]
> requestAnimationFrame(() => refViewPager.current?.setPage(index));

Didn't work for me unfortunately

**Comment by bonlemuel** [comment]
Currently experiencing this issue 

```
Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! 
View <RCTView: 0x7fe0e7e62ad0; reactTag: 355; frame = (0 0; 414 896); layer = <CALayer: 0x600003a877c0>> is associated 
with <UIViewController: 0x7fe0e7c4e450>. Clear this association before associating this view with 
<UIViewController: 0x7fe0e7c56060>.

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1192
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.489
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0
```

I'm trying to integrate a dialog component inside one of the pages. It works well on android. But not on iOS. I'm trying to find the cause. I tried to place my dialog component on its parent module. but still the same. Someone might know a fix or any advise? Thanks!

**Comment by troZee** [comment]
> Currently experiencing this issue
> 
> ```
> Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! 
> View <RCTView: 0x7fe0e7e62ad0; reactTag: 355; frame = (0 0; 414 896); layer = <CALayer: 0x600003a877c0>> is associated 
> with <UIViewController: 0x7fe0e7c4e450>. Clear this association before associating this view with 
> <UIViewController: 0x7fe0e7c56060>.
> 
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
>     RCTUIManager.m:1192
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.489
> __RCTExecuteOnMainQueue_block_invoke
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_main_queue_callback_4CF
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> __CFRunLoopRun
> CFRunLoopRunSpecific
> GSEventRunModal
> -[UIApplication _run]
> UIApplicationMain
> main
> start
> 0x0
> ```
> 
> I'm trying to integrate a dialog component inside one of the pages. It works well on android. But not on iOS. I'm trying to find the cause. I tried to place my dialog component on its parent module. but still the same. Someone might know a fix or any advise? Thanks!

Could you provide a code snippet ?

**Comment by joebochill** [comment]
I am getting the same error as @bonlemuel. Mine does not seem to be related to dialogs though. I get the error when the ViewPager is rendered conditionally after some asynchronous data is loaded.

Simplified example:
```
    return conditionSatisfied ? (
        <View>
            <SafeAreaView>
                <ViewPager
                    ref={viewPager}
                    initialPage={0}
                >
                    <View style={{height: 500, width: 300, backgroundColor: 'orange'}}/>
                    <View style={{height: 500, width: 300, backgroundColor: 'red'}}/>
                    <View style={{height: 500, width: 300, backgroundColor: 'blue'}}/>
                    <View style={{height: 500, width: 300, backgroundColor: 'green'}}/>
                </ViewPager>
            </SafeAreaView>
        </View>
    ) : (
        <LoadingComponent />
    ) 
```

The other component doesn't seem to matter...I can return null and still get the same error. 

Downgrading to 3.x makes the issue go away, but I was using 4.x before I upgraded my RN version to 0.63.

**Comment by bonlemuel** [comment]
> > Currently experiencing this issue
> > ```
> > Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! 
> > View <RCTView: 0x7fe0e7e62ad0; reactTag: 355; frame = (0 0; 414 896); layer = <CALayer: 0x600003a877c0>> is associated 
> > with <UIViewController: 0x7fe0e7c4e450>. Clear this association before associating this view with 
> > <UIViewController: 0x7fe0e7c56060>.
> > 
> > __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
> >     RCTUIManager.m:1192
> > __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.489
> > __RCTExecuteOnMainQueue_block_invoke
> > _dispatch_call_block_and_release
> > _dispatch_client_callout
> > _dispatch_main_queue_callback_4CF
> > __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> > __CFRunLoopRun
> > CFRunLoopRunSpecific
> > GSEventRunModal
> > -[UIApplication _run]
> > UIApplicationMain
> > main
> > start
> > 0x0
> > ```
> > 
> > 
> > I'm trying to integrate a dialog component inside one of the pages. It works well on android. But not on iOS. I'm trying to find the cause. I tried to place my dialog component on its parent module. but still the same. Someone might know a fix or any advise? Thanks!
> 
> Could you provide a code snippet ?

Hi, I can't provide the whole snippet. But here's the structure of the components. (These only to show how I render each). This component is where the dialog component is being rendered.

**Main.js**
```
<View>
   <ViewPager>
       <View>
          <CustomerHeader />
          <ComponentA />
       </View>
       <View>
          <CustomerHeader />
          <ComponentB />
       </View>
       <View>
          <CustomerHeader />
          <ComponentC />
       </View>
    </ViewPager>
</View>
```

**ComponentA.js**
```
<KeyboardAvoidingView>
   <ScrollView>
      <FormComponent />
   </ScrollView>
</KeyboardAvoidingView>
```

**FormComponent.js**
```
<View>
   <DialogComponent />
   <TextField />
   <TextField />
   ...
</View>
```

**DialogComponent.js**
```
<View>
   <Dialog>
       .....
   </Dialog>
</View>
```

I have verified that the dialog component causes the issue. I tried to comment it, it works. But I can't render the dialog. I have tried using a modal instead of dialog.. Still the issue persist. By the way, the issue only persist on iOS. It works well on android.

I'll try to downgrade my Viewpager. I'll give it a shot. Might work... @joebochill 

Here's a snippet of my package

```
....
    **"@react-native-community/viewpager": "^4.2.1",**
    "@react-navigation/bottom-tabs": "^5.9.1",
    "@react-navigation/native": "^5.7.5",
    "@react-navigation/stack": "^5.9.2",
    "axios": "^0.20.0",
    "deepmerge": "^4.2.2",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    **"react-native": "0.63.3",**
.....
```

Thanks!

**Comment by joebochill** [comment]
I narrowed down the problem in my case to version 4.1.0.

4.0.1: works as expected
4.1.0: throws the ViewController error above and the app crashes.

**Comment by bonlemuel** [comment]
@joebochill 

I confirm that **4.0.1** is also working on my end.

Thank you! Saved me a lot of time figuring out a fix.

**Comment by cjhines** [comment]
This seems to have to reappeared (5.4.0 + iOS).

<img width="502" alt="Screenshot 2021-07-30 at 09 00 48" src="https://user-images.githubusercontent.com/16542421/127613902-5125e2a7-e759-4b03-a61f-0be03b371979.png">


```
Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! View <RCTView: 0x7fe85544df90; reactTag: 7413; frame = (0 0; 0 0); layer = <CALayer: 0x6000002f6180>> is associated with <UIViewController: 0x7fe8550becb0>. Clear this association before associating this view with <UIViewController: 0x7fe854f78b50>.

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1193
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.493
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0
```

**Comment by sezginriggs** [comment]
In addition to above reply, I also have the same error with IOS 13.7

**Comment by troZee** [comment]
> I am getting the same error as @bonlemuel. Mine does not seem to be related to dialogs though. I get the error when the ViewPager is rendered conditionally after some asynchronous data is loaded.
> 
> Simplified example:
> 
> ```
>     return conditionSatisfied ? (
>         <View>
>             <SafeAreaView>
>                 <ViewPager
>                     ref={viewPager}
>                     initialPage={0}
>                 >
>                     <View style={{height: 500, width: 300, backgroundColor: 'orange'}}/>
>                     <View style={{height: 500, width: 300, backgroundColor: 'red'}}/>
>                     <View style={{height: 500, width: 300, backgroundColor: 'blue'}}/>
>                     <View style={{height: 500, width: 300, backgroundColor: 'green'}}/>
>                 </ViewPager>
>             </SafeAreaView>
>         </View>
>     ) : (
>         <LoadingComponent />
>     ) 
> ```
> 
> The other component doesn't seem to matter...I can return null and still get the same error.
> 
> Downgrading to 3.x makes the issue go away, but I was using 4.x before I upgraded my RN version to 0.63.

I was trying to reproduce using below code: 
```
import React, { useMemo } from 'react';
import { StyleSheet, View, SafeAreaView, Animated, Text } from 'react-native';

import PagerView from 'react-native-pager-view';

import { LikeCount } from './component/LikeCount';
import { NavigationPanel } from './component/NavigationPanel';
import { useNavigationPanel } from './hook/useNavigationPanel';

const AnimatedPagerView = Animated.createAnimatedComponent(PagerView);

export function BasicPagerViewExample() {
  const { ref, ...navigationPanel } = useNavigationPanel();

  const [isLoading, setLoading] = React.useState(true);

  const pages = useMemo(
    () =>
      navigationPanel.pages.map((page, index) => (
        <View key={page.key} style={page.style} collapsable={false}>
          <LikeCount />
          <Text testID={`pageNumber${index}`}>{`page number ${index}`}</Text>
        </View>
      )),
    [navigationPanel.pages]
  );

  React.useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => {
      clearTimeout(timer);
    };
  }, []);

  return isLoading ? (
    <View />
  ) : (
    <SafeAreaView style={styles.container}>
      <AnimatedPagerView
        //@ts-ignore
        testID="pager-view"
        ref={ref}
        style={styles.PagerView}
        initialPage={2}
        layoutDirection="ltr"
        overdrag={navigationPanel.overdragEnabled}
        scrollEnabled={navigationPanel.scrollEnabled}
        onPageScroll={navigationPanel.onPageScroll}
        onPageSelected={navigationPanel.onPageSelected}
        onPageScrollStateChanged={navigationPanel.onPageScrollStateChanged}
        pageMargin={10}
        // Lib does not support dynamically orientation change
        orientation="horizontal"
        // Lib does not support dynamically transitionStyle change
        transitionStyle="scroll"
        showPageIndicator={navigationPanel.dotsEnabled}
      >
        {pages}
      </AnimatedPagerView>
      <NavigationPanel {...navigationPanel} />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  image: {
    width: 300,
    height: 200,
    padding: 20,
  },
  PagerView: {
    flex: 1,
  },
});
``` 
and I was not able to do that

**Comment by wildseansy** [comment]
From my tests, this is in 5.3.4 too (released on the same day)

> This seems to have to reappeared (5.4.0 + iOS).
> 
> <img alt="Screenshot 2021-07-30 at 09 00 48" width="502" src="https://user-images.githubusercontent.com/16542421/127613902-5125e2a7-e759-4b03-a61f-0be03b371979.png">
> 
> ```
> Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! View <RCTView: 0x7fe85544df90; reactTag: 7413; frame = (0 0; 0 0); layer = <CALayer: 0x6000002f6180>> is associated with <UIViewController: 0x7fe8550becb0>. Clear this association before associating this view with <UIViewController: 0x7fe854f78b50>.
> 
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
>     RCTUIManager.m:1193
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.493
> __RCTExecuteOnMainQueue_block_invoke
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_main_queue_callback_4CF
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> __CFRunLoopRun
> CFRunLoopRunSpecific
> GSEventRunModal
> -[UIApplication _run]
> UIApplicationMain
> main
> start
> 0x0
> ```

**Comment by theambidextrous** [comment]
this issue still persists in 5.4.0. Am using it as a dependency of `@react-navigation/material-top-tabs`

Here is the error:

Exception thrown while executing UI block: A view can only be associated with at most one view controller at a time! View <RCTView: 0x7fe9ef208a00; reactTag: 313; frame = (0 0; 0 0); clipsToBounds = YES; layer = <CALayer: 0x600001061760>> is associated with <UIViewController: 0x7fe9ed45ed30>. Clear this association before associating this view with <UIViewController: 0x7fe9ed656d70>.

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1193
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.493
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

**Comment by msimon** [comment]
Downgrading to `4.2.4` worked for me on IOS.

Something else that I notice, is that this bug seems to happen when the app is cold. I never had it randomly, only when I opened the app for the first time after a while.

**Comment by theambidextrous** [comment]
> Downgrading to `4.2.4` worked for me on IOS.
> 
> Something else that I notice, is that this bug seems to happen when the app is cold. I never had it randomly, only when I opened the app for the first time after a while.

Seems so. For me, the apps runs well on first start, but the error shows when i restart the RN Bundler or when i close and reopen the app on the simulator.

let me try downgrade to 4.2.4

**Comment by alimek** [comment]
I found workaround for that issue, delay rendering `ViewPager` by 50ms, its enough to fix issue for me and almost not visible to end user.

**Comment by bonlemuel** [comment]
Downgrading works for me as well.

**Comment by theambidextrous** [comment]
Yes, i can confirm the same. either version 4.2.4 or 5.3.3 ... they both work, so i went with 5.3.3

**Comment by rborn** [comment]
Worked for me with a combination between delaying the render with 50ms and downgrade to 5.3.0 😿

**Comment by Bardiamist** [comment]
I have this error now. Appeared after update React native to 0.65.0 (coincidence?). Problem related with some view from `PagerView`.

<details>
  <summary>Screenshot</summary>
  
<img width="1508" alt="Screenshot 2021-08-23 at 16 32 11" src="https://user-images.githubusercontent.com/22082342/130424844-45ade32d-c81e-45c7-b383-b978f9d3cdfb.png">
</details>

**Comment by troZee** [comment]
Can anyone test this code ? https://github.com/callstack/react-native-pager-view/pull/432

Instructions: 
- open `node_modules/react-native-pager-view/ios/ReactNativePageView.m` file 
- copy/paste this https://raw.githubusercontent.com/callstack/react-native-pager-view/0da6df0765d7c23ec66c637983fb26316ce2fdec/ios/ReactNativePageView.m into above file 
- `yarn ios` and check if error still occurs

**Comment by Bardiamist** [comment]
> Can anyone test this code ? #432
> 
> Instructions:
> 
> * open `node_modules/react-native-pager-view/ios/ReactNativePageView.m` file
> * copy/paste this https://raw.githubusercontent.com/callstack/react-native-pager-view/0da6df0765d7c23ec66c637983fb26316ce2fdec/ios/ReactNativePageView.m into above file
> * `yarn ios` and check if error still occurs

I tested. Looks no crash (it not 100% reproducable for me so tested 6 times without errors). But I can't change page by gesture with this code.

**Comment by troZee** [comment]
> > Can anyone test this code ? #432
> > Instructions:
> > 
> > * open `node_modules/react-native-pager-view/ios/ReactNativePageView.m` file
> > * copy/paste this https://raw.githubusercontent.com/callstack/react-native-pager-view/0da6df0765d7c23ec66c637983fb26316ce2fdec/ios/ReactNativePageView.m into above file
> > * `yarn ios` and check if error still occurs
> 
> I tested. Looks no crash (it not 100% reproducible for me so tested 6 times without errors). But I can't change page by gesture with this code.

Thank you for the replay. I am on it.

**Comment by troZee** [comment]
@Bardiamist 
I have pushed a new commit. Could you retest it ?

**Comment by Bardiamist** [comment]
> @Bardiamist
> I have pushed a new commit. Could you retest it ?

LGTM. Tested 5 times without crash. Gesture was fixed.

**Comment by troZee** [comment]
> > @Bardiamist
> > I have pushed a new commit. Could you retest it ?
> 
> LGTM. Tested 5 times without crash. Gesture was fixed.

Thank you for cooperation. Before the merge, I will wait for the other developers.

**Comment by troZee** [comment]
This issue has been fixed here: https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.1
