### ISSUE TITLE
Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by AlexSmirnov9107** [callstack/react-native-pager-view#173]
# Bug report

## Summary

```bash 
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.reactnative.community.viewpager2.widget.ViewPager2$RecyclerViewImpl{a137042 VFED..... ......ID 0,0-1080,1369 #1}, adapter:com.reactnativecommunity.viewpager.FragmentAdapter@b871853, layout:com.reactnative.community.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@520d590, context:com.facebook.react.uimanager.ThemedReactContext@7113f48
        at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6433)
        at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1456)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:12699)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13199)
        at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
        at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 24.62 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.0 => 16.13.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

1. Home -> OrganizationsList 
2.Going back from OrganizationsList -> Home

```
export default createNativeStackNavigator(
  {
    Home: HomeScreen,
    OrganizationsList: OrganizationsListScreen,
    OrganizationDetail: OrganizationDetailScreen,
    Rating: RatingScreen,
    Feedbacks: FeedBacksScreen,
    Provider: ProviderScreen,
    WebBrowser: WebBrowserScreen,
    SplashScreens: SplashScreens,
  },
  {
    initialRouteName: 'Home',
    headerMode: 'none',
  },
);

```

**Comment by troZee** [comment]
Could you check, if issue still exist on 3.3.0 ?

**Comment by troZee** [comment]
I assume, this issue does not exist on 3.3.0, so as workaround you can use this version. 

I found some solutions here: https://code.briarproject.org/briar/briar/issues/1363 
But I would like to test those solutions. Could you provide a reproducible repository ?

**Comment by dsznajder** [comment]
Hi @troZee :) I'm not sure if it's related but I was able to reproduce it with `native-stack` from `react-native-screens`.

**Comment by troZee** [comment]
> Hi @troZee :) I'm not sure if it's related but I was able to reproduce it with `native-stack` from `react-native-screens`.

Hey, could you provide a reproducible code ? React navigation uses react native screen under the hood, so probably it is somehow related :D

**Comment by chirag04** [comment]
seeing this in our app as well on v4. will try and gather more information soon

**Comment by jong-hui** [comment]
I have same problem in react-navigation v5 (native-stack)

**Comment by codecog** [comment]
@troZee Happy to take this on and try to solve the issue

**Comment by codecog** [comment]
If it helps, i can confirm it's only happening with v4+ so will focus my efforts there.

**Comment by codecog** [comment]
Sorry guys, i won't be able to continue on with this. Had a few things happen and i won't be able to commit as much time here right now. Once i've sorted that and if this is still an issue i'll come back to it.

**Comment by radko93** [comment]
If you can manage navigation yourself then you can unmount the view pager before navigating. Unfortunately, it's not possible to do it like this always. Do you still need repro for that?

**Comment by troZee** [comment]
> Do you still need repro for that?

Yes, please

**Comment by fadiquader** [comment]
same here, it happens when pressing back.  I'm using `react-navigation` + `react-native-screens`.

**Comment by osdnk** [comment]
I think this bug is quite urgent. It happens when we have `viewpager` inside `native-stack` i.e. `creatweNativeStackNavigator`

**Comment by LRNZ09** [comment]
I also have this problem with `ViewPager` v4.1.6 and `react-native-screens` v2.10.1 using a native stack

**Comment by thanhdevapp** [comment]
same problem Android when user viewpager and creatweNativeStackNavigator

**Comment by jdconley** [comment]
I also have this issue with a new app. I see it when I render a different set of screens inside a `createNativeStackNavigator`, where the screen that has the `ViewPager` as a child is no longer in the native stack navigator. I'm on 4.1.6, react-native-screens 2.11.0, react-native 0.63.x...

Anyone have a workaround?

**Comment by troZee** [comment]
Fix has been applied https://github.com/callstack/react-native-viewpager/pull/271

**Comment by domasn** [comment]
Seems that the issue is still there when using [v6.0.0-rc.0](https://github.com/callstack/react-native-pager-view/tree/v6.0.0-rc.0) with lazy page loading 😕 

App crashes after navigating back or going forward from a screen with a `LazyPagerView` inside a native stack with the following log:
```
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{fb07b3f VFED..... ......ID 0,0-1080,2142 #1}, adapter:com.reactnativepagerview.FragmentAdapter@56bdc0c, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@9408955, context:com.facebook.react.uimanager.ThemedReactContext@692ceaf
        at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6614)
        at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1525)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13109)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13611)
        at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
        at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by pedrolopes10** [comment]
This issue also occurs using 5.4.0 with react navigation native stack 6.1.0, react native screens 3.5.0 and RN 0.64.2.

Hope it helps find out. Tks

**Comment by alexco2** [comment]
Also happens to me (https://github.com/gorhom/react-native-bottom-sheet/discussions/427#discussioncomment-1250678)
Was able to solve the issue by changing from `nativeStackNavigator` to `StackNavigator`, which of course is not an ideal solution regarding the performance.

**Comment by LaGregance** [comment]
> Seems that the issue is still there when using [v6.0.0-rc.0](https://github.com/callstack/react-native-pager-view/tree/v6.0.0-rc.0) with lazy page loading 😕
> 
> App crashes after navigating back or going forward from a screen with a `LazyPagerView` inside a native stack with the following log:
> 
> ```
> java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{fb07b3f VFED..... ......ID 0,0-1080,2142 #1}, adapter:com.reactnativepagerview.FragmentAdapter@56bdc0c, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@9408955, context:com.facebook.react.uimanager.ThemedReactContext@692ceaf
>         at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6614)
>         at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1525)
>         at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13109)
>         at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13611)
>         at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
>         at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
>         at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
>         at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
>         at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
>         at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
>         at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
>         at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
>         at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:796)
>         at android.view.Choreographer.doFrame(Choreographer.java:727)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
>         at android.os.Handler.handleCallback(Handler.java:938)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> ```

Is there some news about this ?

**Comment by Kailash23** [comment]
**androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal
RecyclerView.java, line 6614**
```
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{e0ac578 VFED..... ......ID 0,0-1080,1012 #3f}, adapter:com.reactnativepagerview.ViewPagerAdapter@590d451, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@70144b6, context:com.facebook.react.uimanager.ThemedReactContext@b68408
```
```
androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal RecyclerView.java:6614
androidx.recyclerview.widget.RecyclerView.removeAnimatingView RecyclerView.java:1525
androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished RecyclerView.java:13109
androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished RecyclerView.java:13611
androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished SimpleItemAnimator.java:277
androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd DefaultItemAnimator.java:213
android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd ViewPropertyAnimator.java:1111
android.animation.Animator$AnimatorListener.onAnimationEnd Animator.java:554
android.animation.ValueAnimator.endAnimation ValueAnimator.java:1242
android.animation.ValueAnimator.doAnimationFrame ValueAnimator.java:1484
android.animation.AnimationHandler.doAnimationFrame AnimationHandler.java:146
android.animation.AnimationHandler.access$100 AnimationHandler.java:37
android.animation.AnimationHandler$1.doFrame AnimationHandler.java:54
android.view.Choreographer$CallbackRecord.run Choreographer.java:994
android.view.Choreographer.doCallbacks Choreographer.java:794
android.view.Choreographer.doFrame Choreographer.java:725
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:981
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:237
android.app.ActivityThread.main ActivityThread.java:7948
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:493
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1075
```

Most affected device : Redmi 9 Prime, Galaxy S7 Edge, Galaxy A50

**Comment by chr4ss12** [comment]
same, needs fixing, right now as comment above mentioned, hackish workaround:

```
  exit () {
    this.setState({unmount: true}, () => {
      setTimeout(() => this.props.navigation.goBack(), 100)
    })
  }
```


and


```
      {!this.state.unmount &&
        <PagerView
          scrollEnabled={false}
          ref={(ref) => { this.pagerViewRef = ref }}
          onPageSelected={({ nativeEvent }) => { this.setState({ page: nativeEvent.position }) }}
          style={{ flex: 1, padding: padding }} initialPage={this.state.page} orientation="horizontal">

```

**Comment by hubciorz** [comment]
The problem occurs extremely often. We have about 6000 reports from 1.6k users. 

![image](https://user-images.githubusercontent.com/6502822/148199819-fc96c903-2eac-41ed-8504-29660e800daa.png)
![image](https://user-images.githubusercontent.com/6502822/148199926-39373314-c7b4-43bc-b230-b379146eab1c.png)

**Comment by radko93** [comment]
It happens for me on 6.0.0-rc but on 5.4.x. (not on lazy loading, regular).

**Comment by ArturoTorresMartinez** [comment]
Still happening on RN 67, React navigation 6 when used in a view that then unmounts

**Comment by ArturoTorresMartinez** [comment]
> same, needs fixing, right now as comment above mentioned, hackish workaround:
> 
> ```
>   exit () {
>     this.setState({unmount: true}, () => {
>       setTimeout(() => this.props.navigation.goBack(), 100)
>     })
>   }
> ```
> 
> and
> 
> ```
>       {!this.state.unmount &&
>         <PagerView
>           scrollEnabled={false}
>           ref={(ref) => { this.pagerViewRef = ref }}
>           onPageSelected={({ nativeEvent }) => { this.setState({ page: nativeEvent.position }) }}
>           style={{ flex: 1, padding: padding }} initialPage={this.state.page} orientation="horizontal">
> ```



> > Seems that the issue is still there when using [v6.0.0-rc.0](https://github.com/callstack/react-native-pager-view/tree/v6.0.0-rc.0) with lazy page loading 😕
> > App crashes after navigating back or going forward from a screen with a `LazyPagerView` inside a native stack with the following log:
> > ```
> > java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{fb07b3f VFED..... ......ID 0,0-1080,2142 #1}, adapter:com.reactnativepagerview.FragmentAdapter@56bdc0c, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@9408955, context:com.facebook.react.uimanager.ThemedReactContext@692ceaf
> >         at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6614)
> >         at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1525)
> >         at androidx.recyclerview.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:13109)
> >         at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:13611)
> >         at androidx.recyclerview.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:277)
> >         at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:213)
> >         at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
> >         at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
> >         at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
> >         at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
> >         at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
> >         at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
> >         at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
> >         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
> >         at android.view.Choreographer.doCallbacks(Choreographer.java:796)
> >         at android.view.Choreographer.doFrame(Choreographer.java:727)
> >         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
> >         at android.os.Handler.handleCallback(Handler.java:938)
> >         at android.os.Handler.dispatchMessage(Handler.java:99)
> >         at android.os.Looper.loop(Looper.java:223)
> >         at android.app.ActivityThread.main(ActivityThread.java:7656)
> >         at java.lang.reflect.Method.invoke(Native Method)
> >         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> >         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> > ```
> 
> Is there some news about this ?
> 
> I've temporary fix this by doing bad things :
> 
> ```js
> // setFixAndroidUnmount(true) instead of direct doing navigation.goBack()
> const [fixAndroidUnmount, setFixAndroidUnmount] = useState(false);
> useEffect(() => {
>   if (fixAndroidUnmount) {
>     setTimeout(() => navigation.goBack(), 100);
>   }
> }, [fixAndroidUnmount, navigation]);
> 
> // ....
> {!fixAndroidUnmount && <LazyPagerView />}
> ```

These methods do work, so anyone still having the issue try one of these.

**Comment by hubciorz** [comment]
@ArturoTorresMartinez Perhaps when users go back to the previous screen. I don't know why, but unmounting the pageview (by replacing it with null) does not work.

**Comment by yepMad** [comment]
This error happens when I use PagerView and on the same screen I allow the user to click on a button with "navigation.replace". If I use "navigation.navigate", it doesn't happen.

This is urgent, I'm on version: ^6.0.0-rc.0

**Comment by ArturoTorresMartinez** [comment]
> @ArturoTorresMartinez Perhaps when users go back to the previous screen. I don't know why, but unmounting the pageview (by replacing it with null) does not work.

If removing the pager entirely from the screen doesn't resolve the issue perhaps the pager isn't the library causing it?

If removing it entirely does fix the issue, then the condition for replacing it with a null object isn't triggering at the expected time.

**Comment by lxp-git** [comment]
maybe we need remove `removeAllViews` in  `PagerViewViewManager`?

**Comment by yepMad** [comment]
> maybe we need remove `removeAllViews` in  `PagerViewViewManager`? 

This still occurs on most recent next version?

**Comment by lxp-git** [comment]
> > maybe we need remove `removeAllViews` in  `PagerViewViewManager`?
> 
> This still occurs on most recent next version? In the thruth, "removeAllViews" should fix it. See #516

Wow! Thank you for your work. I am not migrating to `Pre-Release` right now. [I am just left removeAllViews empty](https://github.com/Flickering-AI/react-native-pager-view/commit/b34b065e9fe66d082cd02f1fd42d5456353e60e2). Not sure if it will cause other issues.

**Comment by lxp-git** [comment]
@yepMad Hi. I have tried `6.0.0-rc.2`. It crashed if pages `goBack` quickly. Add this code in example.

```
// use NativeStack
const Stack = createNativeStackNavigator();

export function Navigation() {
  const navigationContainerRef = useNavigationContainerRef();
  React.useEffect(() => {
    const timer = setInterval(async () => {
      navigationContainerRef.navigate(examples[Math.floor(Math.random() * examples.length)].name, {

      });
      await new Promise(resolve => setTimeout(resolve, 100));
      navigationContainerRef.goBack();
    }, 1000);
    return () => {
      clearInterval(timer);
    }
  }, []);
  return (
    <NavigationContainer ref={navigationContainerRef}>
......
```

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.18

**Comment by hixus** [comment]
@troZee is it possible to add the fix also to next branch, we are using`6.0.0-rc.2` and seems this is still happening there. I'm able to crash the app if almost same time changing tab and pressing back.

**Comment by SimpleCreations** [comment]
Second this. 6.0.0 has great performance when having a large amount of pages, but falls behind the main branch too much to be usable on Android :(
I ended up installing both 6.0.0 and 5.x and use the former on iOS and the latter on Android.

**Comment by laurenzcodes** [comment]
This issue is closed and yet the crash still persists in the latest `next` version. (`6.0.0-rc.2` to use LazyPagerView) 

We mainly see it happening on older Android phones running Android 10 and 11. It's really hard to implement a workaround in our codebase so it would be great if we could get an official fix from the maintainers.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673

**Comment by rohit9625** [comment]
> [@troZee](https://github.com/troZee) is it possible to add the fix also to next branch, we are using`6.0.0-rc.2` and seems this is still happening there. I'm able to crash the app if almost same time changing tab and pressing back.

Yes, I can face the crash in the same scenario. Do you know if anyone has found a solution in this case?

**Comment by MrRefactor** [comment]
Hey everyone, I have implemented a fix in this https://github.com/callstack/react-native-pager-view/pull/1063 - please validate it if your crashes are resolved. Once I will finish testing it I will cut a new version.

**Comment by troZee** [comment]
Could you test this version `npm install react-native-pager-view@9.0.0-rc.0` ?
