### ISSUE TITLE
Unable to setup vertical Scroll

### ISSUE THREAD

**Issue by waqarkhan327** [callstack/react-native-pager-view#188]
# Bug report

## Summary
Unable to setup Vertical Scroll on Android. 
Whatever value I'm assigning to "orientation", it always scrolls horizontally.

## Environment info

Expo Version 3.13.1
Tested on Android 9 Device, and Android 7.0.1 Emulator

Library version: 
Tested on both 3.1.0 and 4.0.1

Describe what you expected to happen:

1. It should scroll vertically when I'm assigning the "vertical" to its orientation property

## Reproducible sample code

render() {
    
    return (
      <View style={styles.container}>

        <ViewPager
              style={styles.viewPager}
              initialPage={0}
              onPageScroll={this.onPageScroll}
              onPageSelected={this.onPageSelected}
              onPageScrollStateChanged={this.onPageScrollStateChanged}
              orientation="vertical">
              <View key="1">
                <Text>First Page</Text>
              </View>
              <View key="2">
                <Text>Second Page</Text>
              </View>
              <View key="3">
                <Text>Third Page</Text>
              </View>
          </ViewPager>
      </View>
    );
  }

**Comment by lahivee** [comment]
Did you find a solution or workaround for this? Really hanging on this one :/
