### ISSUE TITLE
ios rundom handle onPress

### ISSUE THREAD

**Issue by maystrenkoYurii** [callstack/react-native-pager-view#241]
ios rundom handle onPress item FlatList if onscroll tabs. Android work perfect

I use
"@react-native-community/viewpager": "4.2.0",
"@react-navigation/material-top-tabs": "5.3.4",
 "react-native-tab-view": "2.15.2",
"react-native-tab-view-viewpager-adapter": "1.1.0",

**Comment by kyoz** [comment]
Relate to https://github.com/callstack/react-native-pager-view/issues/424, which have a repro
