### ISSUE TITLE
TextInput is not focusing on multiple pages 

### ISSUE THREAD

**Issue by PankajChaturvediDtechies** [callstack/react-native-pager-view#250]
## Ask your Question

Hello everyone I am using a view pager for the video scrolling page and using the bottom sheet to add comments, now the text input is not focusing in development mode, and in production, it takes two taps to be focused. 
Even using the normal code without a video page I am facing the same issue. 
this is my simple code where textinput is not getting fuscused. tried with all options of setting heights of the pages but still it is not working.

```
const {height} = Dimensions.get('window');
 <ViewPager
      style={{height: height * 0.91}}
      orientation="vertical"
      onPageSelected={(e) => setSelected(e.nativeEvent.position)}
      initialPage={index}>
      {videos.map((item, index) => {
        return (
         <View
            key={index}
            backgroundColor="gray"
            style={{
              height: height * 0.91,
              alignContent: 'center',
              alignItems: 'center',
              justifyContent: 'center',
            }}>
            <StatusBar translucent backgroundColor="grey" />
            {/* <VideoPlayer
              video={item}
              navigation={navigation}
              isPlay={selected === index}
            /> */}
            <TextInput placeholder={item._id}></TextInput>
          </View>
        );
      })}
    </ViewPager>
```

**Comment by troZee** [comment]
What version is used in above code ? 
Could you check 4.2.0 ?

**Comment by magicismight** [comment]
Same issue on @4.2.1

**Comment by magicismight** [comment]
#155

**Comment by PankajChaturvediDtechies** [comment]
> What version is used in above code ?
> Could you check 4.2.0 ?

version of viewpager is 4.1.6

**Comment by MateWW** [comment]
@PankajChaturvediDtechies Hi, I'm trying to reproduce your problem but it work's for me on `latest` version as well as `next`.
Could you provide some reproduction repository or check if it works with latest version?

**Comment by leoafarias** [comment]
I am having the same issue. Tried to create a snack but it happens in a specific case. For me it only happens when I open the screen in a materialBottomBar navigator. I am guessing that it could have something to do with the height.

**Comment by cjhines** [comment]
@leoafarias Also having issues in MaterialTopTabNavigator.

Did you find a solution / workaround?

**Comment by troZee** [comment]
duplicated: https://github.com/callstack/react-native-pager-view/issues/382

**Comment by ethandpowers** [comment]
This issue appears still, if the `PagerView` is inside a `KeyboardAvoidingView`
