### ISSUE TITLE
Displaying a Modal inside view pager children.

### ISSUE THREAD

**Issue by NathanBeesley** [callstack/react-native-pager-view#302]
Expo: 40
React: 16.13.1
React native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
react-native-community/viewpager: 4.2.0
@react-navigation/bottom-tabs:  5.7.1
@react-navigation/drawer:  5.8.6
@react-navigation/native:  5.5.0
@react-navigation/stack: 5.4.1
Platform: iOS

If a modal(RN) is presented inside one of the children views, when it is closed the layout hides behind navigation and status bar. This issue doesn't happen every time. If it doesn't happen the first time then the layout is fine. It causes issues with all children views inside the view pager, not just the one the modal is presented on. I've tried various layouts for the children and non seem to help. Anyone have any ideas?

**Comment by NathanBeesley** [comment]
I pulled down source and got the example running and cannot repro on the example. I'll have to do some more digging in my environment to better track it down. I'll close this until I can figure this out.

**Comment by NathanBeesley** [comment]
Seems like only when the <Modal /> presentation style is fullscreen this occurred. When I changed presentationStyle='overFullScreen' seemed to alleviate the issue.

**Comment by brkdnmz** [comment]
> Seems like only when the presentation style is fullscreen this occurred. When I changed presentationStyle='overFullScreen' seemed to alleviate the issue.

Thanks for sharing this, helped a lot.
