### ISSUE TITLE
React native 0.64 Support

### ISSUE THREAD

**Issue by teamzz111** [callstack/react-native-pager-view#309]
Support React Native 0.64

## Motivation

Announcing React Native 0.64 with Hermes on iOS, in fact it's important mantain this package compatible with newer versions.

## Related Issues

```
e: /Users/andreslargo/Develop/chamba-app/node_modules/react-native-pager-view/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt: (34, 80): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type UIManagerModule?

```

**Comment by Fortidude** [comment]
Ye, I'm struggling with it as well.

File: `react-native-pager-view/android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt`

line 34:
```
    eventDispatcher = reactContext.getNativeModule(UIManagerModule::class.java).eventDispatcher
```

the issue can be with react-native itself.

**Comment by parkcoop** [comment]
Can confirm, `react-native-pager-view` unusable on new react-native projects

**Comment by teamzz111** [comment]
Did you tried in production mode?

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.1.2

**Comment by teamzz111** [comment]
Thanks a lot!
