### ISSUE TITLE
onPageScrollEvent negative offset value

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-pager-view#310]
```tsx
import ViewPager, {
  PagerViewOnPageSelectedEvent,
  PageScrollStateChangedNativeEvent,
} from 'react-native-pager-view' // v5.1.0
```

here is a screen recording on iOS from a working branch of https://github.com/PedroBern/react-native-collapsible-segmented-view to add the pager, you can see the negative values when swiping to the left. On android I always get positive values.

https://user-images.githubusercontent.com/39778068/110968200-02009f80-8336-11eb-9f0b-1fb9c980129c.mp4

The code:

```tsx
const AnimatedViewPager = Animated.createAnimatedComponent(ViewPager)

...
const [pagerOffset] = React.useState(new Animated.Value(0))

React.useEffect(() => {
  const listener = pagerOffset.addListener(({ value }) => {
    console.log(value)
  })

  return () => {
    pagerOffset.removeListener(listener)
  }
}, [pagerOffset])

...

<AnimatedViewPager
  ...
  onPageScroll={Animated.event(
    [{ nativeEvent: { position: pagerIndex, offset: pagerOffset } }],
    { useNativeDriver: true }
  )}
>
...
```

_Originally posted by @PedroBern in https://github.com/callstack/react-native-pager-view/issues/293#issuecomment-797598872_

**Comment by PedroBern** [comment]
Here is the branch of the recording https://github.com/PedroBern/react-native-collapsible-segmented-view/tree/feat-add-pager-view

**Comment by troZee** [comment]
@PedroBern 
You are using expo right ? https://github.com/PedroBern/react-native-collapsible-segmented-view/blob/a26fac2605d2e871b798b515dde1311ae813b362/example/package.json

So new version needs to be added to the expo. Please try non expo project (https://github.com/callstack/react-native-pager-view/tree/master/example) and then, you will see, it has been fixed.  

Expo for now uses 4.x version of old [ViewPager](https://docs.expo.io/versions/latest/sdk/view-pager/). 

Due above reason, I am closing this issue.

**Comment by PedroBern** [comment]
Thanks for the quick response, sorry for the misunderstanding!

**Comment by troZee** [comment]
> Thanks for the quick response, sorry for the misunderstanding!

No problem :D Probably I need to add a section about the expo to avoid any confusion.
