### ISSUE TITLE
Using Nested View Pager 

### ISSUE THREAD

**Issue by jitenshah19** [callstack/react-native-pager-view#313]
Hi. I am trying to use nested View Pager where the outer view pager has a "Vertical" orientation and the inner ones have a "Horizontal" orientation. I was trying to change the value of the current view in one of the Horizontal View Pager but it does not seem to be working. 
In the first view, I have added a button that should change the current view to the third view but I do not see the changes in the UI. 

Can someone guide me if I am missing something here? 

`import React, {  useState,  } from "react";
import { Text, View, StyleSheet, Button } from "react-native";
import Constants from "expo-constants";
import PagerView from "react-native-pager-view";

export default function App() {
    const [num, setNum] = useState(0);
    const [page, setPage] = useState(1);

  return (
    <View style={styles.container}>
      <PagerView
      style={{ flex: 1 }}
      initialPage={num}
      orientation="vertical"
      onPageSelected={(e) => {
        console.log("onPageSelected", e.nativeEvent.position);
        setNum(e.nativeEvent.position);
      }}
    >
      {data.map((topic, index) => {
        return (
          <View key={index}>
            <PagerView
              style={{ flex: 1 }}
              initialPage={page}
              orientation="horizontal"
              onPageSelected={(e) => {
                console.log("onPageSelected", e.nativeEvent.position);
              }}
            >
              <View key={index + "-" + "1"}>
                <Text>First page {topic.subData[0]}</Text>
                <Button
                  title="Change initial Page to 3"
                  color="#841584"
                  onPress={() => {
                    console.log("Button Clicked");
                    setPage(2);
                  }}
                />
              </View>
              <View key={index + "-" + "2" }>
                <Text>Second page {topic.subData[1]}</Text>
              </View>
              <View key={index + "-" +"3"}>
                <Text>Third page {topic.subData[2]}</Text>
              </View>
            </PagerView>
          </View>
        );
      })}
    </PagerView>
    </View>
  );
}

const data = [
  {
    subData: [1, 2, 3],
  },
  {
    subData: [4, 5, 6],
  },
];

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingTop: Constants.statusBarHeight,
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
});
`

Expo Link : https://snack.expo.io/LGhD0BBcG

**Comment by jitenshah19** [comment]
though the actual problem in my project that I am encountering is when I change the initial page to lets say index : 3 for a horizontal view pager, it does go to that page but when I move left swipe or right swipe it gets me an incorrect value on the PageScroll method in e.nativeEvent.position

For Left Swipe it does not allow to left Swipe and for Right Swipe it returns a value 1 

Please check the attachment.

<img width="1571" alt="React Native Page Viewer" src="https://user-images.githubusercontent.com/79366172/112841786-8b49fd00-90be-11eb-9388-175c27bfa292.png">

**Comment by troZee** [comment]
You should use below api to change the page
https://github.com/callstack/react-native-pager-view/blob/6ba8356cba68e1a7350c8f2ae7a7b24317c30ce6/example/src/hook/useNavigationPanel.ts#L42
