### ISSUE TITLE
TypeError thrown with conditional pages

### ISSUE THREAD

**Issue by rissois** [callstack/react-native-pager-view#321]
## Environment

iOS 14.4 simulator
"react-native-pager-view": "^5.1.2",

## Description

Conditional rendering of a page throws 
**TypeError: null is not an object (evaluating '_ref.props')**
when condition is not met.

NOTE: This is a new problem, this did not occur with @react-native-community/viewpager 4.2.0

## Reproducible Demo

Should be reproducible with this simple code:
```
<PagerView style={styles.pagerView} initialPage={0}>
    <View />
    {false && <View />}
</PagerView>
```

**Comment by imranMnts** [comment]
Linked to this PR?
https://github.com/callstack/react-native-pager-view/pull/354

**Comment by hotaryuzaki** [comment]
> Linked to this PR? #354

is there any solution for this other than manually merging the PR?
