### ISSUE TITLE
app crashed in android when pagerView showing

### ISSUE THREAD

**Issue by gallavie** [callstack/react-native-pager-view#324]
## Environment
I used
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-pager-view": "5.1.2",
## Description
 in some of android devices the app crash when the pagerView show I received this error:
"Page can only be offset by a positive amount, not by -1076 at androidx.viewpager2.widget.ScrollEventAdapter.updateScrollEventValues(ScrollEventAdapter.java:280) at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:178) at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173) at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1971) at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3391) at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:991) at android.view.View.dispatchTouchEvent(View.java:15199) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3914) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3578) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:66) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:39) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594) at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:900) at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957) at android.app.Activity.dispatchTouchEvent(Activity.java:4180) at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69) at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:858) at android.view.View.dispatchPointerEvent(View.java:15458) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7270) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7046) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6446) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6503) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6469) at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6637) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6477) at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6694) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6450) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6503) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6469) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6477) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6450) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9684) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9522) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9475) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9818) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220) at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method) at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200) at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9764) at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9860) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010) at android.view.Choreographer.doCallbacks(Choreographer.java:809) at android.view.Choreographer.doFrame(Choreographer.java:737) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8443) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)"

the details of devices is happen:
Android modelPhone: SM-G960F systemVersionPhone: 10
Android modelPhone: Redmi Note 7 systemVersionPhone: 10
Android modelPhone: SM-G950F systemVersionPhone: 9
Android modelPhone: SM-G965F systemVersionPhone: 9

before i upgraded to this lib i used react-native-swiper@1.5.6
https://www.npmjs.com/package/react-native-swiper 
and not received this error

**Comment by troZee** [comment]
You need to fix below error in your code
`Page can only be offset by a positive amount, not by -1076 at`

**Comment by gallavie** [comment]
HI 
thank you for your fast replay
I am not understand your replay 
how I can fix the bug 
this is my code 
`export default class ViewPager extends Component {
  _currentPage; // the swiper not work well with save the currentPage in state

  constructor(props) {
    super(props);
    this.state = {pages: props.pages, isLTR: props.isLTR};
    this._currentPage = props.isLTR ? 0 : props.pages.length - 1;
  }
  get currentPageIndex() {
    return this._currentPage;
  }
  render() {
    const {children, style} = this.props;
    let {pages, isLTR} = this.state;
    const newPages = [];
    pages = isLTR ? pages : pages.slice().reverse();
    pages.forEach((value, index) => {
      index = isLTR ? index : pages.length - 1 - index;
      if (typeof children === 'function') {
        newPages.push(children({value, index}));
      }
    });
    return (
      <View style={[{flex: 1}, style]}>
        <PagerView
          ref={v => (this.swiper = v)}
          style={styles.pagerView}
          initialPage={isLTR ? 0 : pages.length - 1}
          onPageSelected={event => this.onPageIndexChanged(event)}>
          {newPages}
        </PagerView>
        <View style={[globalStyles.row, styles.containerDots]}>
          {this.renderDots()}
        </View>
      </View>
    );
  }
  renderDots() {
    const {renderDot, renderActiveDot, pages, isLTR} = this.props;
    let dots = [];
    let newIndex = isLTR
      ? this.currentPageIndex
      : pages.length - 1 - this.currentPageIndex;
    pages.forEach((value, index) => {
      dots.push(
        <View key={index}>
          {index === newIndex ? renderActiveDot() : renderDot()}
        </View>,
      );
    });
    return dots;
  }
  onPageIndexChanged({nativeEvent}) {
    let page = nativeEvent.position;
    const {pages, isLTR} = this.state;
    this._currentPage = page > pages.length - 1 ? pages.length - 1 : page;
    this._currentPage = page < 0 ? 0 : page;
    const {onPageIndexChanged} = this.props;
    const newIndex = isLTR ? page : pages.length - 1 - page;
    typeof onPageIndexChanged === 'function' && onPageIndexChanged(newIndex);
  }

  scrollBy(index) {
    const {isLTR, pages} = this.state;
    index = isLTR ? index : index * -1;
    if (
      this._currentPage + index < this.props.pages.length ||
      this._currentPage + index < 0
    ) {
      this.swiper.setPage(this._currentPage + index);
    }
  }
  next() {
    this.scrollBy(1);
  }
  previos() {
    this.scrollBy(-1);
  }
}`

I do not know why the code does not appear properly I entered it under '
I will add that I test it on three Android devices and it always works for me but with my clients the app crashes
thank you

**Comment by gallavie** [comment]
Hi
I found the problem
When you set the phone in a language that is rtl like Hebrew then the app crashes when using the setPage method or when the user scrolls to change a page
When using the setPageWithoutAnimation method it works but works the other way around

**Comment by pierroo** [comment]
I come in 5 years later, but it is still happening.
Might be worth a mention in the documentation?
So how exactly can it be fixed?
