### ISSUE TITLE
web error: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by iamgouravturka** [callstack/react-native-pager-view#333]
×
TypeError: Object(...) is not a function
Module.D:\project\React Native\RN-Test\node_modules\react-native-pager-view\lib\module\PagerViewNative.js
D:/project/React Native/RN-Test/PagerViewNative.tsx:11
   8 |   getInnerViewNode(): ReactElement;
   9 | }
  10 | 
> 11 | export const PagerViewViewManager = requireNativeComponent(
  12 |   VIEW_MANAGER_NAME
  13 | ) as PagerViewViewManagerType;
  14 |

**Comment by troZee** [comment]
Hello @iamgouravturka 
Could you provide more details ? I don't understand this error TBH

**Comment by sindev95** [comment]
> Hello @iamgouravturka
> Could you provide more details ? I don't understand this error TBH

on a brand new react native project , if you install react-native-pager-view and do the example provided and run on web/android/ios , you will get this error , i run into this issue myself now and im looking into it

**Comment by troZee** [comment]
viewpager does not support the web. More context here: 
https://github.com/callstack/react-native-pager-view/issues/91

**Comment by phatnguyentan** [comment]
I know it does not support web, but when I using it, it break all my app, although I exclude it:
const isNative = Platform.OS !== "web";
{isNative && (<PagerView></PagerView>)

**Comment by bkamrani** [comment]
https://stackoverflow.com/questions/66928489/react-native-pagerview-webpack-typeerror-on-web/76790747#76790747

**Comment by bkamrani** [comment]
> > I know it does not support web, but when I using it, it break all my app, although I exclude it: const isNative = Platform.OS !== "web"; {isNative && (PagerView here)
> 
> @phatnguyentan have you found any solution or workaround for that? Many thanks!

https://stackoverflow.com/questions/66928489/react-native-pagerview-webpack-typeerror-on-web/76790747#76790747
