### ISSUE TITLE
[Android] children are not rendering, after upgrading versions

### ISSUE THREAD

**Issue by ahmedrowaihi** [callstack/react-native-pager-view#337]
## Environment
[Android] 
windows 10
node 15.10
 "react": "17.0.1",
 "react-native": "0.64.0",
 "react-native-pager-view": "^5.1.4",
 "react-native-tab-view": "^3.0.1",

## Description

children of react-native-tab-view do not appear!

this message while compiling!

`> Task :react-native-pager-view:compileDebugKotlin
w: <projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (74, 9): Condition 'child == null' is always 'false'
w: <projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (152, 11): 'receiveCommand(T, Int, ReadableArray?): Unit' is deprecated. Deprecated in Java
w: <projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (158, 24): Unnecessary non-null assertion (!!) on a non-null receiver of type EventDispatcher
w: <projectFolder>\node_modules\react-native-pager-view\android\src\main\java\com\reactnativepagerview\PagerViewViewManager.kt: (163, 24): Unnecessary non-null assertion (!!) on a non-null receiver of type EventDispatcher
`

**Comment by ku8ar** [comment]
Maybe you could add any example code? And I think this issue shoud be inside react-native-tab-view repo, not here.

**Comment by ahmedrowaihi** [comment]
> Maybe you could add any example code? And I think this issue shoud be inside react-native-tab-view repo, not here.

the issue was I am passing the tab view inside of a scrollview, so don't do my mistake
