### ISSUE TITLE
enable scroll using left/right arrow keys on iPad keyboard

### ISSUE THREAD

**Issue by RMCollins175** [callstack/react-native-pager-view#338]
## Ask your Question

Is it possible to enable scrolling on PagerView using the left/right arrow keys on an iPad keyboard?

**Comment by troZee** [comment]
ViewPager has a ability to change pages programmatically, but I am not sure, how to set a keyboard listener, which will be responsible for detecting a pressed key. Maybe you can try this library for that stuff https://github.com/kevinejohn/react-native-keyevent
