### ISSUE TITLE
PagerView error when un-mounting

### ISSUE THREAD

**Issue by IPWright83** [callstack/react-native-pager-view#339]
## Environment

react-native-pager-view@5.1.3
react-native@0.64.0
react@17.0.2

Android (multiple versions).

## Description

We seem to be getting an issue when the `PagerView` is un-mounting, but I'm not sure exactly what is causing it. Essentially we have a component that is rendering a `PagerView` like so:

```
const SchedulePage = () => (
    <React.Fragment>
        <Text>Hello</Text>
        <PagerView initialPage={0}>
            <Text>World</Text>
        </PagerView>
    </React.Fragment>
);
```

There comes a point in our application lifecycle where the parent component decides it shouldn't be on the page anymore, and instead we should render something different (tokens have expired, switch to a login page). At the point of doing so, we hit the error.

![image](https://user-images.githubusercontent.com/1374775/116277505-71fba580-a77d-11eb-8409-554df2370a8a.png)

## Reproducible Demo

Start with a new react-native project `npx create-react-native-app` and install the `react-native-pager-view`. Modify `App.js` to contain the following:

```
import { StatusBar } from 'expo-status-bar';
import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import PagerView from 'react-native-pager-view';

const Pager = () => (
  <React.Fragment>
    <Text>This is a Pager</Text>
    <PagerView initialPage={0}>
      <Text>PagerContents</Text>
    </PagerView>
  </React.Fragment>
);

const NotAPager = () => (
  <React.Fragment>
    <Text>This is NOT a Pager</Text>
  </React.Fragment>
);

export default function App() {
  const [count, setCount] = useState(0);

  if (count === 0) {
    setTimeout(() => {
      setCount(1);
    }, 1);
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      {count === 0 ? <Pager /> : <NotAPager />}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

This will render the `PagerView` on first render (as our app does), before simulating needing to hide it (as mentioned we do so after we realise our auth token has expired).

Unfortunately this is a blocking issue for us as it's causing an app crash in a not uncommon situation so it's holding up releases :(

**Comment by IPWright83** [comment]
I've added a reproducible example since I logged the bug, I've also added some additional logging at the top of a few functions in `PagerView.tsx`, and I'm logging immediately before the return in `App.js`.

```
[Wed Apr 28 2021 09:31:55.743]  BUNDLE  ./index.js 
[Wed Apr 28 2021 09:31:56.772]  LOG      Running "main" with {"rootTag":61}
[Wed Apr 28 2021 09:31:56.773]  LOG      App()
[Wed Apr 28 2021 09:31:56.774]  LOG      PagerView.render()
[Wed Apr 28 2021 09:31:56.775]  LOG      PagerView.componentDidMount()
[Wed Apr 28 2021 09:31:56.776]  LOG      App()
[Wed Apr 28 2021 09:31:56.781]  LOG      PagerView.setPageWithoutAnimation
[Wed Apr 28 2021 09:31:56.794]  ERROR    Error: Unable to find node on an unmounted component.
```

So it appears as though the component is un-mounting while waiting for the `requestAnimationFrame` callback. By the time the callback is fired in the JS processing loop, our component is no longer on the page. I'm guessing all we need to do is cancel that request on unmount.

**Comment by IPWright83** [comment]
@troZee thanks for merging, does this get auto released too?

**Comment by troZee** [comment]
@IPWright83 https://github.com/callstack/react-native-pager-view/releases/tag/v5.1.6
