### ISSUE TITLE
inital page doesn't work for dots on HeadphonesCarouselExample.tsx

### ISSUE THREAD

**Issue by batuhanakin** [callstack/react-native-pager-view#348]
Hello everyone,
i have an issue but i don't know how to fix it. maybe there is a bug in this example. Can you help me?

## Environment
simulator: iphone 11 pro max, ios: 14.0.1
mac osx: 10.15.7 

## Description

onpageScroll -> listener sometimes does not work as it should while the application is loading. that's why dots don't start at the initial page value.

## Reproducible Demo

change initialPage , for example "initialPage={3}" and refresh app and you should see dots dont start 3. index.

**Comment by troZee** [comment]
@batuhanakin could you check, if this PR https://github.com/callstack/react-native-pager-view/pull/368 fixes your issue ?
