### ISSUE TITLE
[Android] Could not find viewpager2-1.0.0.jar (androidx.viewpager2:viewpager2:1.0.0)

### ISSUE THREAD

**Issue by iamhaaamed** [callstack/react-native-pager-view#357]
## Environment

"react-native": "0.64.1"
"@react-native-community/viewpager": "^5.0.11"

Devices: HTC Nexus One (Android 11)

## Description

project does not working on android

## Stack trace

Could not resolve all files for configuration ':react-native-community_viewpager:debugCompileClasspath'.
   > Could not find viewpager2-1.0.0.jar (androidx.viewpager2:viewpager2:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/viewpager2/viewpager2/1.0.0/viewpager2-1.0.0.jar

**Comment by rezareact** [comment]
Change viewpager version in : node_modules/react-native-pager-view/android/build.gralde:
`  implementation 'androidx.viewpager2:viewpager2:1.1.0-alpha01'
`

**Comment by iamhaaamed** [comment]
> Change viewpager version in : node_modules/react-native-pager-view/android/build.gralde:
> ` implementation 'androidx.viewpager2:viewpager2:1.1.0-alpha01'`

in this way i should always do the change after `npm install` or `yarn`

**Comment by ynonra** [comment]
> Change viewpager version in : node_modules/react-native-pager-view/android/build.gralde:
> ` implementation 'androidx.viewpager2:viewpager2:1.1.0-alpha01'`

Didn't work for me... :(

**Comment by maleking** [comment]
> > Change viewpager version in : node_modules/react-native-pager-view/android/build.gralde:
> > ` implementation 'androidx.viewpager2:viewpager2:1.1.0-alpha01'`
> 
> in this way i should always do the change after `npm install` or `yarn`

you can use patch package https://www.npmjs.com/package/patch-package
