### ISSUE TITLE
The Kotlin Gradle plugin was loaded multiple times in different subprojects

### ISSUE THREAD

**Issue by KrisLau** [callstack/react-native-pager-view#366]
## Environment
```
"react": "^17.0.2",
    "react-native": "^0.64.0",
    "react-native-pager-view": "^5.1.7",
    "react-native-unimodules": "^0.13.3",
    "react-native-webview": "^11.4.3"
```

## Description
Getting this error on build:
```
The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-webview'
```

## Reproducible Demo
1. Install react-native-pager-view, and react-native-webview.
2. Build the app & run react-native run-android

**Comment by rajkinkhabwala** [comment]
same here I am also facing the same problem. did you get any solution?  @KrisLau

**Comment by KrisLau** [comment]
@rajkinkhabwala  Nope not yet unfortunately

**Comment by troZee** [comment]
Could you try this version ? https://github.com/callstack/react-native-pager-view/releases/tag/v5.2.1

**Comment by KrisLau** [comment]
@troZee Sorry for the late reply! I just tested it with v5.2.1 but I'm still getting the same error unfortunately

**Comment by lucas0205** [comment]
worked for me! THX!

**Comment by rajkinkhabwala** [comment]
> @troZee Sorry for the late reply! I just tested it with v5.2.1 but I'm still getting the same error unfortunately

Hey, the apps but it's buggy, if like swipe faster then it starts swiping itself, and it's annoying so I have to go back to the previous screen and again try it but still works but it is buggy.
