### ISSUE TITLE
[CodeSandbox] (0 , _reactNative.requireNativeComponent) is not a function

### ISSUE THREAD

**Issue by 1uokun** [callstack/react-native-pager-view#377]
## how to use react-native-pager-view in CodeSandbox or react-native-web?

```node
TypeError
(0 , _reactNative.requireNativeComponent) is not a function
evaluate
https://feirj.csb.app/node_modules/react-native-pager-view/lib/commonjs/PagerViewNative.js:12:70
```
<img width="931" alt="截屏2021-06-16 下午10 27 30" src="https://user-images.githubusercontent.com/28673261/122237694-1b475800-cef2-11eb-89db-3f1b40651718.png">

**Comment by troZee** [comment]
Unfortunately, we don't support the web version 
https://github.com/callstack/react-native-pager-view/issues/91
