### ISSUE TITLE
When lot of data comes app freezes.

### ISSUE THREAD

**Issue by sankar9659** [callstack/react-native-pager-view#378]
Hi,
I have used the react-native-pager-view package for sliding the images. 
The app freezes some time  or hung when there is lot of data comes.
I have used normal looping method inside viewpager like below code,

```
         <ViewPager
                onPageSelected={(e) => indexChanged(e.nativeEvent.position)}
                ref={swiperRef}
                initialPage={flag}
            >
                {_map(artworksData, (val, keys) => {
              return (
               <Text style={[detailStyles.nameStyle, styles.openSanBold]}>
                                                {val.firstName} {val.lastName}
                                            </Text>
              )})}
             <ViewPager/>
```

While using above code app hangs in that page for long time, after some time the swiper worked.
To fix this issue I have used FlatList method instead of looping.
But If I used flatlist the ref and initial page props not working.
Also we can't achieve the smooth scrolling that means when you swipe across a image, it needs to snap to the next image. 
but it allows the middle with half(or parts) of two images displaying.
Like below image. 
Any solution for this?

![image](https://user-images.githubusercontent.com/58698022/122251465-25fcef80-cee8-11eb-8d50-a3c419020890.png)

**Comment by troZee** [comment]
Hey 👋
Could you test next version, which has implemented lazy loading feature ?

**Comment by sankar9659** [comment]
Sure @troZee Let me check the latest version and update here.
Shall I use map (loop) inside the viewpager?

**Comment by troZee** [comment]
> Sure @troZee Let me check the latest version and update here.
> Shall I use map (loop) inside the viewpager?

Yes you can. Please checkout our examples.

**Comment by sankar9659** [comment]
@troZee I am using the latest version (5.2.1),
I got near 1000 data, But still takes some delay to show the items.
Please check my code, and let me know If anything wrong,
My code is,

```
<PagerView
                initialPage={flag}
                style={styles.flex}
                onPageSelected={(e) => indexChanged(e.nativeEvent.position)}
                scrollEnabled
            >
                {_map(artworksData, (val, i) => {
                    Reactotron.log({ "val": val });
                    return (
                        <View style={{
                            flex: 1,
                            justifyContent: 'center',
                        }} key={i}>
                            <Text style={[detailStyles.nameStyle, styles.openSanBold]}>
                                {val.firstName} {val.lastName}
                            </Text>
                            <Text style={[detailStyles.nameStyle, styles.openSanItalic]}>
                                {val.title}
                            </Text>
                            {val.slength || val.swidth
                                ? (
                                    <Text style={detailStyles.priceTxtStyl}>
                                        {val.slength} x {val.swidth} {printerSettings.dimFormat}
                                    </Text>
                                )
                                : null
                            }
                            {val.mediumType
                                ? <Text style={detailStyles.priceTxtStyl}>
                                    {val.mediumType}
                                </Text>
                                : null
                            }
                        </View>

                    )
                })}
            </PagerView>```

**Comment by troZee** [comment]
> @troZee I am using the latest version (5.2.1),
> I got near 1000 data, But still takes some delay to show the items.
> Please check my code, and let me know If anything wrong,
> My code is,
> 
> ```
> <PagerView
>                 initialPage={flag}
>                 style={styles.flex}
>                 onPageSelected={(e) => indexChanged(e.nativeEvent.position)}
>                 scrollEnabled
>             >
>                 {_map(artworksData, (val, i) => {
>                     Reactotron.log({ "val": val });
>                     return (
>                         <View style={{
>                             flex: 1,
>                             justifyContent: 'center',
>                         }} key={i}>
>                             <Text style={[detailStyles.nameStyle, styles.openSanBold]}>
>                                 {val.firstName} {val.lastName}
>                             </Text>
>                             <Text style={[detailStyles.nameStyle, styles.openSanItalic]}>
>                                 {val.title}
>                             </Text>
>                             {val.slength || val.swidth
>                                 ? (
>                                     <Text style={detailStyles.priceTxtStyl}>
>                                         {val.slength} x {val.swidth} {printerSettings.dimFormat}
>                                     </Text>
>                                 )
>                                 : null
>                             }
>                             {val.mediumType
>                                 ? <Text style={detailStyles.priceTxtStyl}>
>                                     {val.mediumType}
>                                 </Text>
>                                 : null
>                             }
>                         </View>
> 
>                     )
>                 })}
>             </PagerView>```
>        
> ```

Please use [next](https://github.com/callstack/react-native-pager-view#next-version) version

```
yarn add @react-native-community/viewpager@next
```

Where the lazy feature has been implemented

**Comment by sankar9659** [comment]
Okay Thanks for your quick response, Let me try this.

**Comment by sankar9659** [comment]
@troZee Can you please give the example link?

**Comment by troZee** [comment]
> @troZee Can you please give the example link?
> How should I import the package?

Sure :D Example you can find here: https://github.com/callstack/react-native-pager-view/blob/next/example/src/LazyPagerViewExample.tsx

**Comment by devladinci** [comment]
@troZee I think it's not `yarn add @react-native-community/viewpager@next` but `yarn add react-native-pager-view@next` since RNC view pager was deprecated. I saw the same thing in the README.md

**Comment by troZee** [comment]
> @troZee I think it's not `yarn add @react-native-community/viewpager@next` but `yarn add react-native-pager-view@next` since RNC view pager was deprecated. I saw the same thing in the README.md

You are right. Thank you for inconvenience.

**Comment by elisjoaquim** [comment]
Hello @troZee! I'm trying to implement LazyPagerView with expo but I'm getting error. Is it not available for expo?
