### ISSUE TITLE
Running a PWA with react-native-pager-view

### ISSUE THREAD

**Issue by PiotrNap** [callstack/react-native-pager-view#381]
I'm developing a React Native application with Expo & react-native-pager-view, after a few weeks of development I wanted to check my app on the browser by running: expo start --web

The Expo project is starting without any issues, however when I navigate to the local address where the app is being served I get a nasty error:

![ude2I](https://user-images.githubusercontent.com/59693946/122679290-8e024d00-d1ea-11eb-9a37-377879541abc.png)
 
This is my first React Native app and I'm not sure if the react-native-pager-view simply cannot be run in the browser or I just need to add some webpack configuration for it to succeed.

Any help would be much appreciated.

**Comment by troZee** [comment]
Hey @PiotrNap 
So far, this lib does not support the web. More context here: https://github.com/callstack/react-native-pager-view/issues/91
