### ISSUE TITLE
[Android] Sometimes the component render nothing (related to #323)

### ISSUE THREAD

**Issue by thanakij** [callstack/react-native-pager-view#389]
## Environment

platform: Android only
react-native: 0.62.3
react-native-pager-view: 5.2.1

## Description

After I upgrade to 5.2.1 (#323), I didn't see the NPE crash anymore. However, there is a side effect so that sometimes we see that the component just renders nothing.

In short, the crash is replaced with null rendering.

## Reproducible Demo

Good news is that I can now consistently reproduce this one. The step is actually simple:

1. run `npx react-native run-android` when your connected Android device's screen is **off**
2. After the command finishes, you may need to wait a few seconds, making sure that the the bundle is loaded properly.
3. Unlock your phone, the app should load with the PagerView component showing nothing. When this happens, the swipe effect is not working also.

**Comment by thanakij** [comment]
In addition, I have found that ReactAndroid shipped with old react-native (before it gets removed in react versions)
has a basic support of `ViewPager`. Unfortunately, it is not `ViewPager2` though.

It is confirmed that solution in #323 is not clean and we may learn something from this. Please see below link:
- [https://github.com/facebook/react-native/tree/0.62-stable/ReactAndroid/src/main/java/com/facebook/react/views/viewpager](https://github.com/facebook/react-native/tree/0.62-stable/ReactAndroid/src/main/java/com/facebook/react/views/viewpager)

I don't know much about Kotlin but I wish this can be converted into Kotlin and migrate to `ViewPager2`?

```
@Override
protected ReactViewPager createViewInstance(ThemedReactContext reactContext) {
    return new ReactViewPager(reactContext);
}

```

**Comment by zabutok** [comment]
@thanakij  Yes i see problem i am testing solution

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.0
