### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCViewPager

### ISSUE THREAD

**Issue by pradeepanCodetez** [callstack/react-native-pager-view#399]
Environment
-------------

"dependencies": {
        "@ptomasroos/react-native-multi-slider": "2.2.2",
        "@react-native-async-storage/async-storage": "1.15.2",
        "@react-native-community/geolocation": "^2.0.2",
        "@react-native-community/masked-view": "^0.1.10",
        "@react-native-community/push-notification-ios": "^1.8.0",
        "@react-native-community/toolbar-android": "0.1.0-rc.2",
        "@react-native-community/viewpager": "^4.1.0",
        "@react-native-firebase/app": "^12.1.0",
        "@react-native-firebase/messaging": "^12.1.0",
        "@react-navigation/native": "^5.9.4",
        "@react-navigation/stack": "^5.14.5",
        "axios": "^0.21.1",
        "eventemitter3": "^4.0.7",
        "native-base": "2.15.2",
        "react": "16.13.1",
        "react-native": "0.63.4",
        "react-native-confirmation-code-field": "7.0.1",
        "react-native-country-picker-modal": "2.0.0",
        "react-native-deck-swiper": "github:HardikDhanani/react-native-deck-swiper",
        "react-native-fast-image": "8.3.4",
        "react-native-gesture-handler": "^1.10.3",
        "react-native-gifted-chat": "0.16.3",
        "react-native-iap": "^5.2.14",
        "react-native-image-crop-picker": "0.36.0",
        "react-native-linear-gradient": "2.5.6",
        "react-native-localization": "^2.1.7",
        "react-native-localize": "^2.1.1",
        "react-native-modalbox": "^2.0.2",
        "react-native-page-control": "1.1.2",
        "react-native-permissions": "^3.0.5",
        "react-native-popup-dialog": "0.18.3",
        "react-native-push-notification": "^7.4.0",
        "react-native-reanimated": "^2.1.0",
        "react-native-safe-area-context": "^3.2.0",
        "react-native-screens": "^3.1.1",
        "react-native-scrollable-tab-view": "1.0.0",
        "react-native-video": "5.1.1",
        "react-native-view-overflow": "0.0.5",
        "react-navigation": "4.4.4",
        "react-navigation-stack": "^2.10.4",
        "react-redux": "7.2.3",
        "react-timer-mixin": "^0.13.4",
        "redux": "4.0.5",
        "redux-persist": "^6.0.0",
        "redux-thunk": "2.3.0"
    },

When using @react-native-community/viewpager, it show an error.

"Invariant Violation: Tried to register two views with the same name RNCViewPager"

**Comment by troZee** [comment]
Please replace `@react-native-community/viewpager` with `react-native-pager-view` and probably some of your dep uses pager-view as a dependency. You need to find this dependency inside your project and use appropriate one.

**Comment by brambang** [comment]
i had same issue.
and i think we had same cause which is react-native-scrollable-tab-view
i want to try this package because react-native-scrollable-tab-view had issue with flatlist tab content

**Comment by L0rdCr1s** [comment]
I'm still getting this error @brambang did you find a solution for this

**Comment by b0nbon1** [comment]
I'm also still getting this error. any other solutions

**Comment by nemanjamitric** [comment]
I'm still getting this error 
`"react-native-pager-view": "^6.3.1"`
