### ISSUE TITLE
[Android] The number of ANR has increased

### ISSUE THREAD

**Issue by thanakij** [callstack/react-native-pager-view#406]
## Environment

It might relates to #389. I have found that the number of ANR has significantly increased.
The log provided by Google Play shows that it is potentially from ViewPager2
so I report an issue here for further investigation.

## Description

![screenshot](https://i.imgur.com/xxzBsIu.png)

## Reproducible Demo

This is reported by Google Play Console.
After [the fix](https://github.com/callstack/react-native-pager-view/pull/404) is ready.
Let's see whether the ANR rate is also reduced.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.0
