### ISSUE TITLE
Change of Page does not animate anymore since version 5.3.3

### ISSUE THREAD

**Issue by alexco2** [callstack/react-native-pager-view#411]
## Environment
"react-native-pager-view": "5.3.3"
"react-native": "0.64.2"

## Description
Since version 5.3.3 switching between pages is not animated anymore. The pages just jump from one to another (no gliding). Subsequent versions are not fixing this bug. If the prop lazy is set to true, the first switch to a page is animated, the subsequent jumps to the page are not though.

## Reproducible Demo
It should be fairly somple to reproduce this, I have nothing fancy going on in my PagerView. If not, I will try to provide a snack.

**Comment by ku8ar** [comment]
My palantir tells me that "nothing fancy" means new computed "initialPage" prop after each new render. Right?

**Comment by alexco2** [comment]
@ku8ar 
I removed the initialPage prop and the animation is working again. I remember that I set that to fix some weird behavior. This behavior is luckily also not happening in the new version. So all in all, everything works fine now. Thank you for your help!
