### ISSUE TITLE
node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m:426:6: Bad receiver type 'int * _Nonnull'

### ISSUE THREAD

**Issue by studiozocaro** [callstack/react-native-pager-view#414]
after install page view 
when i compile in xcode receive this. error  **node_modules/@react-native-community/viewpager/ios/ReactNativePageView.m:426:6: Bad receiver type 'int * _Nonnull'**

" [_eventDispatcher sendEvent:[[RCTOnPageSelected alloc] initWithReactTag:self.reactTag position:[NSNumber numberWithInteger:_currentIndex] coalescingKey:_coalescingKey++]];
    
    [_eventDispatcher sendEvent:[[RCTOnPageScrollEvent alloc] initWithReactTag:self.reactTag position:[NSNumber numberWithInteger:_currentIndex] offset:[NSNumber numberWithFloat:0] coalescingKey:_coalescingKey++]];
"

on code row 372 error  **Bad receiver type 'int *'**
"  if (weakSelf.eventDispatcher) {
             [weakSelf.eventDispatcher sendEvent:[[RCTOnPageSelected alloc] initWithReactTag:weakSelf.reactTag position:[NSNumber numberWithInteger:index] coalescingKey:coalescingKey]];
         }"

**Comment by troZee** [comment]
`@react-native-community/viewpager` has been deprecated. Please use [new lib](https://github.com/callstack/react-native-pager-view#migration)
