### ISSUE TITLE
App crash - RTCView error

### ISSUE THREAD

**Issue by sezginriggs** [callstack/react-native-pager-view#415]
## Environment

IOS 13.2.2, IOS 13.7

## Description

On IOS 13.7, PagerView leads to attached error. Couldn't find what triggers that but it disappears after several refreshes.

![Simulator Screen Shot - iPhone 7 13 7 - 2021-07-30 at 15 31 38](https://user-images.githubusercontent.com/10950287/127654626-ebb63f10-a28b-4768-a844-daeb9d46e8e9.png)

Might be related with https://github.com/callstack/react-native-pager-view/issues/167 because @cjhines also reported the same issue with version 5.4.0 several hours ago.

**Comment by cjhines** [comment]
Can confirm that I'm also getting this error in the current version.

**Comment by arifo** [comment]
we are also experiencing this same behaviour, app crashes randomly when screen with PagerView is opened

**Comment by radko93** [comment]
Also having this error on iOS 14.7.

**Comment by troZee** [comment]
Duplicated. Please use #167 as a main thread

**Comment by troZee** [comment]
Could yall test it https://github.com/callstack/react-native-pager-view/pull/432
