### ISSUE TITLE
Android Issue: Focus issues on Text Input View inside of a  FlatList 

### ISSUE THREAD

**Issue by himu243** [callstack/react-native-pager-view#416]
I have 2 screens inside of a Pager View both having TextInput in each row of Flatlist.

My Observations so far:

      **<PagerView
        ref={ pagerRef }
        initialPage={ 0 }
        orientation="horizontal"
        style={{ flex: 1 }}
        onPageSelected={ e => setSelectedPageIndex(e.nativeEvent.position) }
      >**
If we use flex = 1, means Pager View can adjust its height dynamically according to the View available (When Keyboard Opens and when it closes), **then Text Input looses focus and Keyboard Dismisses** for the very first time we click. Then after the first time, it works fine

But, 

If we don't use Flex property and we use Height instead which is going to be same no matters keyboard will open or close(Focus or Unfocus), the the above issue doesn't occur.

const height = Dimensions.get('window').height

      **<PagerView
        ref={ pagerRef }
        initialPage={ 0 }
        orientation="horizontal"
        style={{ width: '100%', height }}
        onPageSelected={ e => setSelectedPageIndex(e.nativeEvent.position) }
      >**

Has anyone faced such similar situation before?

**Comment by troZee** [comment]
Duplicated: https://github.com/callstack/react-native-pager-view/issues/382
