### ISSUE TITLE
How to set buffer preload size to 0 in Lazy pager

### ISSUE THREAD

**Issue by max-frai** [callstack/react-native-pager-view#417]
Hello, thank you for amazing lib. What I need is fully lazy pager when data request on page should be called only after page is active and in viewport. I tried to change `buffer` for `PagerView` but it preloads at least one next page. If it's not possible and pager need to preload next slide, how to detect inside rendered item that it's first time and page is visible and make request?

**Comment by kaiyes** [comment]
Hi @max-frai were you able to solve this ? Also Can you please show the the code for here ? I'm working on a something similar

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
