### ISSUE TITLE
How to change backgroundColor while children are rendering.

### ISSUE THREAD

**Issue by adriantx** [callstack/react-native-pager-view#418]
When the children within pager are loaded/rendering the background color of the content is white, I need to change it as my interface is mainly black.
I tried to change the color using `backgroundColor: 'black'` in style prop but it doesn't seem to work.

**Comment by troZee** [comment]
You need to change style for each child view https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx#L39

**Comment by adriantx** [comment]
> You need to change style for each child view https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx#L39

I tried to change the color of the child as mention above using `style={{ backgroundColor: 'black' }}` and it doesn't seem to have any effect

**Comment by troZee** [comment]
Could you provide a code snippet ? Or can you compare your code with this example ?  https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx#L39

**Comment by adriantx** [comment]
> Could you provide a code snippet ? Or can you compare your code with this example ? https://github.com/callstack/react-native-pager-view/blob/master/example/src/BasicPagerViewExample.tsx#L39

The code is similar to the example above , the issue can be observed when the app just starts, or child list are re-rendered, 
I think it is not related to child views at all, it is something related to how the component is displayed when it is just about to render its children, but I can't find the source code where the background color of the 'default view' is set

**Comment by troZee** [comment]
Child views are added dynamically ?

**Comment by adriantx** [comment]
> Child views are added dynamically ?

Yes, the entire list is sometimes replaced with a new one, and for a portion of second the background becomes white

**Comment by adriantx** [comment]
> Child views are added dynamically ?

Is there any solution to changing the color of the flickering background ?
