### ISSUE TITLE
OnPageSelected - Return View Current Key (Id) ? 

### ISSUE THREAD

**Issue by aal75-oc** [callstack/react-native-pager-view#419]
Hi, Thanks for react-native-pager-view.
But something is missing like getting current Key of Views.
Actually onPageSelected return only position but is it possible return also Key (ID) of Views ?
Thanks in advance

**Comment by troZee** [comment]
Hello 👋 
Based on index, you can get a particular view, hence there is no need to add additional params to callback.

**Comment by erzzo** [comment]
Hi @troZee, I searched for the same thing. Finally I found the solution.
```
onPageSelected={(e) => console.log(e.nativeEvent.position)
```
Probably good to mention in the docs, if it's not a react native basic thing... I didn't know about it.
cc @aal75-oc

**Comment by oldo** [comment]
@erzzo thanks very much for this. Agree should be in the docs as I was unaware too.

**Comment by nikitph** [comment]
thanks @erzzo yes this should be in the docs
