### ISSUE TITLE
[iOS]Incorrect position value emitted from onPageScroll

### ISSUE THREAD

**Issue by Elabar** [callstack/react-native-pager-view#421]
## Environment
|Package|Version|
|-|-|
|react-native-pager-view|5.3.1|

This issue is migrated from https://github.com/satya164/react-native-tab-view/issues/1211
Take a look at this PR also https://github.com/satya164/react-native-tab-view/pull/1148#issuecomment-889883221

## Description

Position value jump across page.
Value recorded from onPageScroll event
```
{"value":0}
{"value":0.007788162212818861}
{"value":0.0303738322108984}
{"value":0.06697819381952286}
{"value":0.11682242900133133}
{"value":0.17834891378879547}
{"value":0.25}
{"value":0.32866042852401733}
{"value":0.413551390171051}
{"value":0.5}
{"value":0.5872274041175842}
{"value":0.6713395714759827}
{"value":0.75}
{"value":0.8216511011123657}
{"value":0.8831775784492493}
{"value":0.9330217838287354}
{"value":0.9696261882781982}
{"value":0.9922118186950684}
{"value":1}
{"value":3}
```

![image](https://user-images.githubusercontent.com/42211280/126630641-106b8d1e-fdcb-44c2-921e-9afad14f1932.gif)

## Reproducible Demo
https://github.com/captain-refactor/tab-view-position-bug

**Comment by tgensol** [comment]
Any news on that one ?

**Comment by troZee** [comment]
> Any news on that one ?

Yes: https://github.com/callstack/react-native-pager-view/pull/435 

Could y'all test it ?

**Comment by Elabar** [comment]
> Could y'all test it ?

Seems to work fine on my side! 🚀🚀
