### ISSUE TITLE
The point of this library

### ISSUE THREAD

**Issue by Stevemoretz** [callstack/react-native-pager-view#430]
## Ask your Question

I use this library only because it was included in expo SDK, but really the whole thing can be done with a scrollView why do we need this library?Is it more performant than a scrollView with full width and height views (pages)? Or why else?

**Comment by LadislavBohm** [comment]
Well this is a wrapper around native components so it has better performance at least. Also implementing those vertical/horizontal swipes smoothly just in ScrollView would be a lot of work, not to mention animations and methods like setting a specific page.

**Comment by Stevemoretz** [comment]
> Well this is a wrapper around native components so it has better performance at least. Also implementing those vertical/horizontal swipes smoothly just in ScrollView would be a lot of work, not to mention animations and methods like setting a specific page.

Thank you so much for clarification.
Just hoping that reanimated 2 events would be supported soon.
