### ISSUE TITLE
How to prevent going to the 1st view when we reach the end?

### ISSUE THREAD

**Issue by wilsolutions** [callstack/react-native-pager-view#433]
Hi, I have a button with a onPress -> ref.current?.setPage(++index), it works fine, the only problem is that when I'm on the last view an tap next it send me back to the 1st view even though I add a condition to don't call setPage when it is on the last view.

**Comment by LadislavBohm** [comment]
Why not use condition to check current index and total number of pages like this:
`
if (index < pages.length - 1) {
    ref.current?.setPage(++index);
}
`

**Comment by wilsolutions** [comment]
> Why not use condition to check current index and total number of pages like this:
> `if (index < pages.length - 1) { ref.current?.setPage(++index); }`

Hi, yeah man that's the weird part, as I mentioned in my question it goes to the 1st view even though I add a condition to avoid it.

**Comment by wilsolutions** [comment]
it was a re-rendering issue, no problem with the library...
