### ISSUE TITLE
XCode: Unknown type name 'RCTEventDispatcher' in ReactNativePageView.h

### ISSUE THREAD

**Issue by lxrmido** [callstack/react-native-pager-view#434]
## Ask your Question

![image](https://user-images.githubusercontent.com/863382/130760304-2db4226f-c123-462b-9dc2-d6e6d8a78379.png)

but if I `#import <React/RCTEventDispatcher.h>`, another error throws like:

`34 duplicate symbols for architecture x86_64`

I'd tried `remove Pods`, `pod update`, `pod install`, `react-native link` not working 

my versions:

```
        "react": "17.0.1",
        "react-native": "0.64.1",
```

how can I resolve it?

**Comment by troZee** [comment]
If you would like to change something in the library, you need to open an Example folder and edit files from Pods. Below you can find more info

![Screen Shot 2021-08-25 at 11 44 11 AM](https://user-images.githubusercontent.com/12766071/130768335-aded38c7-7594-4bd2-8d14-287fed8c6eda.png)

**Comment by rogel123** [comment]
Also having this issue, how to fix this? :(

**Comment by rogel123** [comment]
> ## Ask your Question
> ![image](https://user-images.githubusercontent.com/863382/130760304-2db4226f-c123-462b-9dc2-d6e6d8a78379.png)
> 
> but if I `#import <React/RCTEventDispatcher.h>`, another error throws like:
> 
> `34 duplicate symbols for architecture x86_64`
> 
> I'd tried `remove Pods`, `pod update`, `pod install`, `react-native link` not working
> 
> my versions:
> 
> ```
>         "react": "17.0.1",
>         "react-native": "0.64.1",
> ```
> 
> how can I resolve it?


Did you resolve it?

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/blob/master/CONTRIBUTING.md

**Comment by csantarin** [comment]
@lxrmido @rogel123 Are the both of you using `3.3.1`? I ran into this today, too.

According to this library's version history, you should pick up to at minimum [`4.2.0`](https://github.com/callstack/react-native-pager-view/releases/tag/v4.2.0) as it now explicitly imports
```obj-c
#import <React/RCTEventDispatcher.h>
```

From #239:
> [...] it seems like [`RCTEventDispatcher`] is no longer transitively imported from `RCTViewManager`.

And the author's right! If you jump to definition between the two React Native versions, you can prove this.

| 0.63.4 | 0.64.1 |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/67677362/131836771-d7cdf9d5-c88b-4f98-bcfa-be1e09199c37.png) | ![image](https://user-images.githubusercontent.com/67677362/131836825-e307e68e-9f59-4f5e-9c3a-46461f7b004a.png) |
| https://github.com/facebook/react-native/blob/v0.63.4/React/Views/RCTViewManager.h#L13 | https://github.com/facebook/react-native/blob/v0.64.1/React/Views/RCTViewManager.h |

**Comment by rogel123** [comment]
@csantarin I'm using latest react 0.65
