### ISSUE TITLE
Crash when navigating back from PagerView

### ISSUE THREAD

**Issue by alexco2** [callstack/react-native-pager-view#440]
Hello, I found a crash in my app which I was able to reproduce and trace back to `PagerView`.

## Environment

    "@react-navigation/bottom-tabs": "^6.0.0",
    "@react-navigation/native": "^6.0.0",
    "@react-navigation/native-stack": "^6.0.0",
    "react-native-pager-view": "^5.4.1",
    "react-native-screens": "~3.4.0",

## Description

This bug crashed the app without an error message. Crashlytics gives me the following crashreport:

```
Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true b.v.b.f$m{8268e2 VFED..... ......ID 0,0-1080,2096 #3}, adapter:com.reactnativepagerview.b@447b473, layout:b.v.b.f$h@f750f30, context:com.facebook.react.uimanager.l0@5d374a0
       at androidx.recyclerview.widget.RecyclerView$v.C(:282)
       at androidx.recyclerview.widget.RecyclerView.removeAnimatingView(:22)
       at androidx.recyclerview.widget.RecyclerView$m.a(:27)
       at androidx.recyclerview.widget.RecyclerView$l.h(:7)
       at androidx.recyclerview.widget.n.G(:3)
       at androidx.recyclerview.widget.c$d.onAnimationEnd(:17)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1111)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
It seems to be the same/ similar issue like this: https://github.com/callstack/react-native-pager-view/issues/173.
The `@next` version does not solve the bug though and since the other issue does not seem to be maintained anymore, I created this issue.

## Reproducible Demo

1. Navigate to second screen in stack with `PagerView`
2. Swipe to second Page in `PagerView`
3. Press the TabIcon of Parent `TabNavigator` to get back to first `StackScreen`

Doing this fast increases the chance of the error happening. I have to try ~10 times for the error to happen.

The video shows the bug in action. On the last frame, the app crashes. 
Interesting to note here is that: On the first navigation back to the Startscreen, the `PagerView` is still rendered and the crash does not appear. On the second time I navigate back, you can see that the `PagerView` ist not rendered anymore. The app then crashes.

https://user-images.githubusercontent.com/61253912/133158434-06533ec1-afe3-4c57-b3f3-2e7c0a0b3765.mp4

In the following snack, the bug is reproduced for you to test:
https://snack.expo.dev/@expoco2/fatal-crash-with-pagerview

**Comment by OzymandiasTheGreat** [comment]
I'm actually experiencing this on every navigation away from the pager. Sometimes it doesn't crash, but those times are rare.

**Comment by alexco2** [comment]
For me it is the other way around. But still not reliable enough for production. Will have to search for an alternative. A fix would be amazing though.

**Comment by wbercx** [comment]
It crashes every time you navigate back while the pages are transitioning.

Worked around it by temporarily disabling the back button for half a second (using `BackHandler` from `react-native`) every time I change to a different page. So far so good.

**Comment by ArturoTorresMartinez** [comment]
Anyone have updates on this?

**Comment by yepMad** [comment]
This error happens when I use PagerView and on the same screen I allow the user to click on a button with "navigation.replace". If I use "navigation.navigate", it doesn't happen.

This is urgent, I'm on version: ^6.0.0-rc.0

**Comment by chakrihacker** [comment]
If it's urgent maybe put a bounty on issue. 
You can't demand free work at urgent level

**Comment by ArturoTorresMartinez** [comment]
> If it's urgent maybe put a bounty on issue. You can't demand free work at urgent level

100%

We get this for free, if it doesn't work as expected, to find and suggest workarounds or submit PRs is the least we can do.

**Comment by yepMad** [comment]
Hey, sorry if that sounded bad. It was not my intention to rush anyone, nor to say that I am not trying to provide workarounds, I just wanted to make it clear that this makes it impossible for this RC to work with react-navigation.

**Comment by ArturoTorresMartinez** [comment]
Does the conditional render from the other issue thread help you at all?

I tagged you over there

> Hey, sorry if that sounded bad. It was not my intention to rush anyone, nor to say that I am not trying to provide workarounds, I just wanted to make it clear that this makes it impossible for this RC to work with react-navigation. In the above comment I provided how I am reproducing this error, and this was my first contact with react-native-pager-view. I hope you understand that I didn't mean to demand free work from anyone.

**Comment by yepMad** [comment]
I believe so. I will be testing this shortly. I reverted my version to the latest release and tried to do some workaround to simulate a LazyLoader. Now I will go back to RC and try this workaround, in the end I can give my opinion and help in some PR if possible.

In the past this https://github.com/callstack/react-native-pager-view/pull/271 was a plausible fix for this same problem, why not now? It's a question for all of us to think about, I'll look at this too.

> Does the conditional render from the other issue thread help you at all?
> 
> I tagged you over there
> 
> > Hey, sorry if that sounded bad. It was not my intention to rush anyone, nor to say that I am not trying to provide workarounds, I just wanted to make it clear that this makes it impossible for this RC to work with react-navigation. In the above comment I provided how I am reproducing this error, and this was my first contact with react-native-pager-view. I hope you understand that I didn't mean to demand free work from anyone.

**Comment by ArturoTorresMartinez** [comment]
> I believe so. I will be testing this shortly. I reverted my version to the latest release and tried to do some workaround to simulate a LazyLoader. Now I will go back to RC and try this workaround, in the end I can give my opinion and help in some PR if possible.
> 
> In the past this #271 was a plausible fix for this same problem, why not now? It's a question for all of us to think about, I'll look at this too.
> 
> > Does the conditional render from the other issue thread help you at all?
> > I tagged you over there
> > > Hey, sorry if that sounded bad. It was not my intention to rush anyone, nor to say that I am not trying to provide workarounds, I just wanted to make it clear that this makes it impossible for this RC to work with react-navigation. In the above comment I provided how I am reproducing this error, and this was my first contact with react-native-pager-view. I hope you understand that I didn't mean to demand free work from anyone.

Good question, so that was a fix for last year.

Could React Native or React Navigation 6 be part of the issue? 

I'm currently on RN 67 and Navigation 6 so if you also upgraded recently that could be part of it.

**Comment by yepMad** [comment]
@ArturoTorresMartinez @chakrihacker @alexco2 I believe I have come up with a fix, could you check it out? https://github.com/callstack/react-native-pager-view/pull/516

**Comment by alexco2** [comment]
@yepMad thank you for the pr!
Since the issue was breaking my app and I wasn't able to find a solution, I moved to another library and can't reproduce the bug anymore, sorry :/

**Comment by yepMad** [comment]
@alexco2 sem problemas! This is very urgent for me, while this PR is under review I sent a package to NPM. I will delete it when this PR is approved. If you feel comfortable, you can also use it.

https://www.npmjs.com/package/@heymad/react-native-pager-view

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.0-rc.1

**Comment by alexco2** [comment]
@yepMad Did your patch solve the issue for you? I tried your patch and version 6-rc.2 and both still crash when quickly navigating to and back from a page with a pager-view
@troZee

**Comment by alexco2** [comment]
https://github.com/callstack/react-native-pager-view/pull/552 solves this Bug in my case.

**Comment by troZee** [comment]
> #552 solves this Bug in my case.

Thank you for checking this fix. I will check this issue later locally

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.18
