### ISSUE TITLE
[Example] Simple PageIndicator for iOS and Android

### ISSUE THREAD

**Issue by mwegener-com** [callstack/react-native-pager-view#453]
If anyone is looking for a simple page indicator which is working on Android and iOS: here it is.

Code: https://pastebin.com/uBQuWczK

<img width="438" alt="Bildschirmfoto 2021-09-23 um 15 36 21" src="https://user-images.githubusercontent.com/64470126/134564431-9461f8b0-b268-4d3e-81d0-197fc1abe186.png">

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/blob/master/example/src/PaginationDotsExample.tsx
