### ISSUE TITLE
setPageWithoutAnimation fires onPageSelected for all pages in between

### ISSUE THREAD

**Issue by yanush** [callstack/react-native-pager-view#454]
## Environment

    "react-native": "0.65.1",
    "react-native-pager-view": "^5.4.4"

## Description

I'm trying to achieve immediate page change using setPageWithoutAnimation.
The problem is i'm also subscribing to onPageSelected and it fires for every page in between the range.
For example, I have 5 pages, when I'm on page 1 and call setPageWithoutAnimation(4) I get onPageSelected for page 2, onPageSelected for page 3, and onPageSelected for page 4

Is there a way to work around this behavior?

**Comment by troZee** [comment]
@yanush 
Could you test my changes ?

**Comment by yanush** [comment]
Seems like it fixed the issue, but now when I navigate from the last tab to the first tab (I have 5 tabs), I can't see the content of the first tab. Only after I swipe a little bit the content appears

**Comment by troZee** [comment]
> Seems like it fixed the issue, but now when I navigate from the last tab to the first tab (I have 5 tabs), I can't see the content of the first tab. Only after I swipe a little bit the content appears

Thank you for testing my changes. Could you provide a repro code ?

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.6
