### ISSUE TITLE
[tab-view] Quick Swipe Gesture Causes Race Condition on onIndexChange (Android)

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-pager-view#456]
Original issue: 
https://github.com/satya164/react-native-tab-view/issues/1250

## EPILEPSY WARNING
https://user-images.githubusercontent.com/17049683/130364091-715c0cea-63d7-4005-8385-fac167bfe735.mp4

First 2-3 seconds, I show a regular swipe-right followed by a swipe-left which works fine (using the TabBar example)

Then the following 2-3 seconds I swipe right as usual, but quickly swipe left before the animation has finished.

This causes the infinite loop shown in the video at the end, this will continue until I restart the screen.

### Expected behavior

Just go back to the first screen as usual.

### Reproduction

Will provide later

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | "^3.1.1"
| react-native-pager-view                | "^5.4.0"
| react-native                           | ~0.63.3
| expo                                   | ^38.0.0 (ejected)
| node                                   | v14.2.0
| npm or yarn                            | yarn

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.5

**Comment by stelmakhivan** [comment]
This issue is still reproducing.

**Comment by rhanziy** [comment]
This issue is still reproducing.

**Comment by yangduonghong-duc** [comment]
This issue is still reproducing on v6.2.3
