### ISSUE TITLE
initialPage is not working

### ISSUE THREAD

**Issue by M4cM4rco** [callstack/react-native-pager-view#460]
I created a project with react-native-pager-view, and everything works fine (initialPage worked too). 
I copied my src to another empty project and installed every lib again, but now the initialPage does not work anymore. Any idea what I did wrong, or is it a bug? 
(I use expo in my projects)

**Comment by kyunkakata** [comment]
Hey, please check out and patched your local modules with this pull request https://github.com/callstack/react-native-pager-view/pull/521.
