### ISSUE TITLE
Removing last page when it's active causes a crash in iOS on RN 0.64

### ISSUE THREAD

**Issue by duailibe** [callstack/react-native-pager-view#465]
## Environment

- react-native: 0.63.4
- react-native-pager-view: 5.4.7

## Description

If we remove the last child of the PagerView, when it's active, iOS crashes with:

<img src="https://user-images.githubusercontent.com/1574588/138365136-ad0af46c-4860-47a6-9447-95179346ca72.png" width="400" />

```
Exception thrown while executing UI block: *** -[__NSArrayM objectAtIndexedSubscript:]: index 4 beyond bounds [0 .. 3]

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1199
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.496
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

```

## Reproducible Demo

This is a minimal case that we can verify this crash happening. A simple app to navigate to the 5th (last) page and press the text to remove it. iOS should crash.

```js
import React, {useState} from 'react';
import {Text, View} from 'react-native';
import PagerView from 'react-native-pager-view';

const App = () => {
  const [pages, setPages] = useState(5);

  return (
    <PagerView style={{flex: 1}} initialPage={0}>
      {new Array(pages).fill().map((_, i) => (
        <View
          key={i}
          style={{width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center'}}>
          {i !== pages - 1 ? (
            <Text>Please navigate to next page -></Text>
          ) : (
            <Text
              onPress={() => {
                setPages(pages - 1);
              }}>
              Press me to remove this page
            </Text>
          )}
        </View>
      ))}
    </PagerView>
  );
};
```

**Comment by svenlombaert** [comment]
@troZee This still seems to happen for me on iOS, attached a video. I'm using react-native-tab-view and am going from three tabs to one, and it crashes. 

https://user-images.githubusercontent.com/2846986/140039537-7cfac05b-a648-4585-a3f8-49b4c9a5349a.mov

If I can do anything to help out, do let me know.

**Comment by troZee** [comment]
Due to fact, that above fix did not work, I have reopened the PR https://github.com/callstack/react-native-pager-view/pull/467

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.9

**Comment by raymishtech** [comment]
@troZee Tried the latest release as well, the fix is not solving the iOS crash issue.
