### ISSUE TITLE
Rendering issue !

### ISSUE THREAD

**Issue by youngseo-im** [callstack/react-native-pager-view#470]
## Ask your Question

Hello, I have a question.

If you select a tab that's more than 2 spaces away, you'll be able to render the component in the middle and see the tab you chose. Can't you implement this so that you can move it directly to the tab you selected from the current tab?

https://user-images.githubusercontent.com/75972718/138989861-6166431f-7794-4332-8b16-1706b481f246.mov

**Comment by troZee** [comment]
Thank you @wbercx for answering on that question. For now, we don't support lazy screen loading. Maybe it will be possible in the future.
