### ISSUE TITLE
onPageScroll, onPageScrollStateChanged and onPageSelected are never fired

### ISSUE THREAD

**Issue by SamiChab** [callstack/react-native-pager-view#473]
## Environment

`react-native: 0.66.1`
`react: 17.0.2`
`react-native-pager-view: 5.4.8` (also tried 5.4.7 and 6.0.0-rc.0)

## Description

The functions `onPageScroll`, `onPageScrollStateChanged` and `onPageSelected` are never fired, neither on Android nor on iOS.

## Reproducible Demo

```
<AnimatedPagerView
	style={styles.pagerView}
	initialPage={0}
	onPageScroll={(event: PagerViewOnPageScrollEvent) => console.log('onPageScroll', { event }) } // nothing is logged
	onPageScrollStateChanged={(event: PageScrollStateChangedNativeEvent) => console.log('onPageScrollStateChanged', { event }) } // nothing is logged
	onPageSelected={(event: PagerViewOnPageSelectedEvent) => console.log('onPageSelected', { event }) } // nothing is logged
	orientation="horizontal"
	transitionStyle="scroll"
>
	{data.map((item, index) => renderItem(item, index))}
</AnimatedPagerView>
```

**Comment by troZee** [comment]
please checkout our example https://github.com/callstack/react-native-pager-view/tree/master/example

**Comment by SamiChab** [comment]
Okay, I used the hook you created [here](https://github.com/callstack/react-native-pager-view/blob/master/example/src/hook/useNavigationPanel.ts). I don't know why it works now but it works
