### ISSUE TITLE
Crashing when switching pages quickly on iOS

### ISSUE THREAD

**Issue by likeSo** [callstack/react-native-pager-view#479]
## Environment

Running on the latest React Navigation and Expo.

## Description

Create a new material top navigator in react navigation, and switch between screens quickly, then it crashes!

![2021-11-14 18 35 57](https://user-images.githubusercontent.com/12247340/141677697-bf35a063-d03b-474d-ba8c-b08d5bd4e8a8.gif)
As you can see, problem one, the indicator is wrong after the tab changed.
Problem 2, and the most important, it crashed!!!

## Reproducible Demo

This problem should be the same with:
https://github.com/callstack/react-native-pager-view/issues/458

**Comment by suraj-desai** [comment]
Yeah, got the same issue.
any solution?

**Comment by likeSo** [comment]
> 

No... Still waiting for a response.Too many problems in this lib

**Comment by jasony9982** [comment]
meet the same issue， dose anyone have a solution?

**Comment by likeSo** [comment]
> meet the same issue， dose anyone have a solution?

Please refer to this comment: https://github.com/callstack/react-native-pager-view/issues/458#issuecomment-940020561
This should be a bug on UIPageViewController

**Comment by RZulfikri** [comment]
After a few investigations, I believe this issue is due to the racing condition/top many actions of the animation. Try my temporary solution, to change the **animated** value to **NO**.

```
diff --git a/node_modules/react-native-pager-view/ios/ReactNativePageView.m b/node_modules/react-native-pager-view/ios/ReactNativePageView.m
index bebfb39..6907119 100644
--- a/node_modules/react-native-pager-view/ios/ReactNativePageView.m
+++ b/node_modules/react-native-pager-view/ios/ReactNativePageView.m
@@ -183,7 +183,7 @@ - (void)setReactViewControllers:(NSInteger)index
     
     [self.reactPageViewController setViewControllers:@[controller]
                                            direction:direction
-                                            animated:animated
+                                            animated:NO
                                           completion:^(BOOL finished) {
         __strong typeof(self) strongSelf = weakSelf;
         strongSelf.currentIndex = index;
```

**Comment by BrianIto** [comment]
@likeSo, I was using Expo Go too and it was not working well, so I started a crusade to solve the problem because this Pager was essential to the project.

So, this is not a **real** solution, but something that removes the bug.

If you disable `scrollEnabled` from your pager you will not have this issue anymore, but... Users can't scroll.

If you're willing to sacrifice this interaction to have your ViewPager working fine, this can solve the problem.

Code Example:
```
<PagerView scrollEnabled={false}
    transitionStyle={"curl"}
    initialPage={0}>
```

I hope it helps you guys to achieve what you want.

**Comment by troZee** [comment]
Closing since it has been fixed here https://github.com/callstack/react-native-pager-view/issues/458
