### ISSUE TITLE
onPageScrollStateChanged' 'idle' state not firing in some cases on iOS

### ISSUE THREAD

**Issue by Omelyan** [callstack/react-native-pager-view#496]
## Description

**onPageScrollStateChanged** with pageScrollState === 'idle' does not fire when trying to overdrag the page (first and last pages) on iOS if overdrag prop is false, and works fine while dragging between pages or overdrag prop is true; yet works well in all cases for Android platform.

## Environment

"react-native-pager-view": "^5.4.9", iOS 14.4

**Comment by zamplyy** [comment]
I have the same issue.
