### ISSUE TITLE
Jcenter needs to be removed

### ISSUE THREAD

**Issue by AdhamMahmoud98** [callstack/react-native-pager-view#501]
## Environment
 Android

## Description

Jcenter is not stable at the moment and its support will be discontinued. I am trying to compile my app locally and I getting this issue due to jcenter 

> Could not download kotlin-build-common-1.5.30.jar (org.jetbrains.kotlin:kotlin-build-common:1.5.30)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.5.30/kotlin-build-common-1.5.30.jar'.         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.5.30/kotlin-build-common-1.5.30.jar'. Received status code 502 from server: Bad Gateway

**Comment by wiscgazf** [comment]
I also have this problem. Have you solved it

**Comment by mauricedoepke** [comment]
@troZee @krozniata can you consider removing jcenter in favor of maven?

Jcenter is currently down, see: https://github.com/facebook/react-native/issues/35136 which breaks apps with react-native-pager-view,.
Jcenter is already read only for quite some time now. Even though they said it will stay, online indefinitly there is a risk of it shutting down forever.

**Comment by andre-luiz1997** [comment]
I can confirm this is a problem with me too. Until today I wasn't experiencing any issues with react-native-pager-view, but today the app won't build and fails everytime on this package.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.2

**Comment by ivanichi** [comment]
> https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.2

@troZee thank you

**Comment by FungkiPandu** [comment]
> https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.2

Can I use Lazy page loading with this version?
