### ISSUE TITLE
multiple pages visible

### ISSUE THREAD

**Issue by ggepenyan** [callstack/react-native-pager-view#511]
## Is there any way to have multiple pages visible but only one of them active?

I'm putting an example of what I mean (I think the image will describe itself better).

<img width="395" alt="Screen Shot 2022-02-13 at 06 28 43" src="https://user-images.githubusercontent.com/17830568/153735728-c6c0f85b-3294-4378-8c9d-3ec63f650d5f.png">

If there is a way to achieve that, I think it would be nice to include it in examples. Thanks for this wonderful package and for the support you do.

**Comment by alexandermirzoyan** [comment]
Same issue.

**Comment by troZee** [comment]
Duplicated: https://github.com/callstack/react-native-pager-view/issues/37
