### ISSUE TITLE
React Navigation Material Top Tabs stop responding when pressed rapidly.

### ISSUE THREAD

**Issue by elmcapp** [callstack/react-native-pager-view#515]
## Environment

"@react-navigation/material-top-tabs": "^6.1.1",
"react-native-pager-view": v5.4.11,
"react": "17.0.2",
"react-native": "0.67.2"

## Description

I am using React Navigation Material Top Tabs which depends on this library. 

1.) When I press on tabs rapidly eventually the tabs stop responding. You can swipe left to right on the screen to change pages however pressing on a tab has no response.

2.) This problem also seem to happen if you click on the same tab twice. In this example if you click on CAM then wait 2 seconds and click CAM again then after all tabs become unresponsive. 

## Reproducible Demo

https://user-images.githubusercontent.com/64275658/154208477-c0ad20b4-f1d7-477c-82c1-21b600ddaf43.mp4

**Comment by dngconsulting** [comment]
Same issue here ...

**Comment by elmcapp** [comment]
I notice this even happen if you press slow and if you press a tab and press the same tab again then after no response

**Comment by coolguy001tv** [comment]
> Same issue here with 5.4.11 and react navigation 6 ...
> 
>  Screen.Recording.2022-02-17.at.08.36.33.mov

I temp solve this problem by using https://github.com/callstack/react-native-pager-view/pull/492 with 5.4.9
U may try.

**Comment by TomCorvus** [comment]
Hi there,
same problem here with `5.4.11`. No app crash but the bar doesn't responding.
It's not a fatal crash but it's the same thing on user side in the end.
The problem was mention 5 months ago, any chance to finally eradicate this problem?

Thanks

**Comment by dngconsulting** [comment]
We are trying to ship a product that is blocked waiting for this fix. It's Open Source, that's the game ... Thanks for all you can do regarding this (nasty) bug.

**Comment by TimMun** [comment]
https://github.com/callstack/react-native-pager-view/pull/527

**Comment by mehthabt** [comment]
Thanks @TimMun , this fixed for me

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.12
