### ISSUE TITLE
STRANGE CRITICAL Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined + RNCViewPager was not found in the UIManager

### ISSUE THREAD

**Issue by putuoka** [callstack/react-native-pager-view#535]
## Environment
"react": "17.0.2",
"react-native": "0.67.3",
"react-native-pager-view": "^6.0.0-rc.1"

## Description

Me (windows 11) and my friend (MacBook Air) fresh basic install react native CLI with only welcome text. We are trying to test this framework and copy very basic example written. I got an error "Element type is invalid" and fixed it by add curly brace in import PagerView. before: import PagerView from 'react-native-pager-view'; after: import { PagerView } from 'react-native-pager-view';
then i push my work so my friend can git clone/pull to it.

But in my friend side (mac) got 2 diff error. with { PagerView } he got "Element type is invalid error", with PagerView (without { curly brace) he got "RNCViewPager was not found in the UIManager" error.  

## Reproducible Demo

```

import React from 'react';
import { StyleSheet, View, Text } from 'react-native';
import  PagerView  from 'react-native-pager-view';

const MyPager = () => {
  return (
    <View style={{ flex: 1 }}>
      <PagerView style={styles.viewPager} initialPage={0}>
        <View style={styles.page} key="1">
          <Text>First page</Text>
          <Text>Swipe ➡️</Text>
        </View>
        <View style={styles.page} key="2">
          <Text>Second page</Text>
        </View>
        <View style={styles.page} key="3">
          <Text>Third page</Text>
        </View>
      </PagerView>
    </View>
  );
};

const styles = StyleSheet.create({
  viewPager: {
    flex: 1,
  },
  page: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default MyPager;

```

**Comment by putuoka** [comment]
Sorry already Solved with

1. react-native start --reset-cache
2. uninstall the app from the device
3. react-native run-android

**Comment by oarsoy** [comment]
instead of import PagerView from 'react-native-pager-view';

`import { PagerView } from 'react-native-pager-view';`
