### ISSUE TITLE
(ios)@next: on LazyPagerViewer and PagerViewer .setPage could stuck, .setPageWithoutAnimation works fine

### ISSUE THREAD

**Issue by yepMad** [callstack/react-native-pager-view#537]
## Environment

react-native@0.64.3
react-natve-pager-view-6.0.0-rc.1
iOS 15

## Description

Using LazyPagerView and/or PagerView in the @next version on iOS when using ref.setPage(page + 1) the user continues on the "page", if he clicks again he will go to page + 1.

I have a list with 10 items, and another with 3 items. The list with 10 items hangs at each item. I don't think code is needed, but you can see mine below.

When using setPagePageWithoutAnimation everything happens as it should.

## Reproducible Demo

```
<PagerContainer
    ref={listViewerRef}
    initialPage={page}
    data={data}
    buffer={1}
    maxRenderWindow={5}
    scrollEnabled={false}
    orientation="horizontal"
    transitionStyle="scroll"
    renderItem={renderItem}
    keyExtractor={item => item.id}
    onPageSelected={e => setPage(e.nativeEvent.position)}
/>
```

I'm on a project for release, sorry for not providing a source code. If necessary, I will do my best to provide for it.

**Comment by yepMad** [comment]
I believe it is the same problem as https://github.com/callstack/react-native-pager-view/pull/520, my objective-c abilities are still under development, this PR is a fix for the version 5, I believe is not 100% adaptable.

**Comment by yepMad** [comment]
I just found out that this also happens with PagerView, not just LazyPagerView

**Comment by alpha0010** [comment]
You could try `v6.0.0-rc.0`. If it works there, the issues is likely c558f98a859f3f147cf60cc2091b70e0c585c622.

**Comment by yepMad** [comment]
Solves in https://github.com/callstack/react-native-pager-view/pull/547
