### ISSUE TITLE
jcenter dependency error

### ISSUE THREAD

**Issue by MCalero11** [callstack/react-native-pager-view#541]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-pager-view@5.4.15` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-pager-view/android/build.gradle b/node_modules/react-native-pager-view/android/build.gradle
index 260b52f..413ca72 100644
--- a/node_modules/react-native-pager-view/android/build.gradle
+++ b/node_modules/react-native-pager-view/android/build.gradle
@@ -4,7 +4,7 @@ buildscript {
 
   repositories {
     google()
-    jcenter()
+    mavenCentral()
   }
 
   dependencies {
@@ -51,7 +51,6 @@ android {
 
 repositories {
   mavenCentral()
-  jcenter()
   google()
 
   def found = false
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vladimirevstratov** [comment]
It works! Thank you

**Comment by troZee** [comment]
@MCalero11 
Thank you for providing a diff. I encourage y'all to create a PR for a such changes. It would be much easier for me for tracking issues and maintain the repo. Here you can find a fixed version: 

https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.2
