### ISSUE TITLE
Blank screen after rotation or navigation inside of Material Top Tabs (React Navigation)

### ISSUE THREAD

**Issue by jcarioti** [callstack/react-native-pager-view#543]
## Environment

iOS 15.4.1 - iPhone 13 Pro

```
"@react-navigation/material-top-tabs": "^6.2.1",
"@react-navigation/native": "^6.0.10",
"react-native-pager-view": "5.4.15",
"react-native-screens": "^3.13.1",
```

I've tried two different versions of react-native-tab-view since I know that library is in between React Navigation Material Top Tabs and this React Native Pager View:

Latest, last published in 2021:
`"react-native-tab-view": "3.1.1",`

Pull Request that updates Tab View's dependency on Pager View to 5.4.15 from 2 weeks ago:
`"react-native-tab-view": "satya164/react-native-tab-view#1330/head",`

## Description

We use React Navigation (specifically Material Top Tabs) to render multiple, swipeable "pages". We were previously on pager-view 5.4.11 and things were working as expected, but after updating to 5.4.15 (with the intention of pulling in the iOS crash fixes), we started experiencing blank screens after rotating the device. We also will occasionally get blanks screens when navigating directly to a page in the pager-view using `navigation.navigate()`, but it's a bit less frequent that way. I've even seen examples where first load results in a blank screen, but that's even more rare. Rotation is a surefire way to cause the blank screen.

I'm not sure if this issue is related to React Navigation's Material Top Tabs, React Native Tab View, or this Pager View library. Considering the issue comes up only after a Pager View update, I decided to start here first.

## Reproducible Demo
https://user-images.githubusercontent.com/4457848/162533494-0fa26b36-a216-40ec-80a9-98968ab1b18d.mov

This should provide the minimum code necessary to reproduce what we're seeing:

```
import React, { useMemo, useCallback }   from 'react';
import { View, Text }                    from 'react-native';
import { enableScreens }                 from 'react-native-screens';

import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import { NavigationContainer }           from '@react-navigation/native';

enableScreens(true);

const Tab = createMaterialTopTabNavigator();

function getRandomColor() {
  const letters = '0123456789ABCDEF';
  let color = '#';
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }

  return color;
}

export default function App() {
  const pageData = useMemo(() => {
    const ids = Array.from(Array(30).keys());

    return ids.map(id => {
      return {
        id,
        color: getRandomColor()
      };
    });
  }, []);

  const renderPages = useCallback(() => {
    return pageData.map(page => (
      <Tab.Screen
        key={page.id}
        name={`page-${page.id}`}
      >
        {() => (
          <View style={{
            height: '100%',
            width: '100%',
            backgroundColor: page.color,
            justifyContent: 'center',
            alignItems: 'center'
          }}>
            <Text style={{ fontSize: 48 }}>Page {page.id}</Text>
          </View>
        )}
      </Tab.Screen>
    ));
  }, [ pageData ]);

  return (
    <NavigationContainer>
      <Tab.Navigator
        tabBar={() => null}
        backBehavior="none"
        screenOptions={{
          lazy: true,
          lazyPreloadDistance: 1,
          swipeEnabled: true,
        }}
      >
        { renderPages() }
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by jcarioti** [comment]
I believe I've narrowed the problem down to this commit: https://github.com/callstack/react-native-pager-view/commit/32608632de7a81e1baddf6172360527a09403945

If I comment out the code from this commit, the page is still visible after rotation. I'm going to temporarily patch these lines out of our project, but curious if this code-change is causing the issue I'm describing for anyone else?

**Comment by matthewparavati** [comment]
@jcarioti Not the same issue but kind of similar. The code from this commit causes our app to not render correctly after we rotate on tablets / larger devices. Initial load looks fine but once we rotate, a large chunk of the screen goes blank / not utilized. When we change tabs, the issue goes away but if you rotate again, the blank area shows again. 

Commenting out these lines resolves our issue.

**Comment by andreialecu** [comment]
> I believe I've narrowed the problem down to this commit: https://github.com/callstack/react-native-pager-view/commit/32608632de7a81e1baddf6172360527a09403945

Related issue also caused by that commit [#530](https://github.com/callstack/react-native-pager-view/issues/523#issuecomment-1129731887)
