### ISSUE TITLE
Page View is not working when placed inside a scrollview or flatlist

### ISSUE THREAD

**Issue by adityashrivastwa** [callstack/react-native-pager-view#570]
Hi, react-native-pager-view is not working on both iOS and android.

Currently, I am using `react-native-pager-view@5.4.15` and `react-native@0.64.2`. It shows blank screen when placed inside ScrollView. But, it's working perfectly fine when wrapped inside a View.
Please help me out.

`<ScrollView>
  <PagerView style={{ flex: 1 }} initialPage={0}>
    <View key="1">
      <Text>First page</Text>
    </View>
    <View key="2">
      <Text>Second page</Text>
    </View>
  </PagerView>
</ScrollView>`

**Comment by troZee** [comment]
Please checkout this example: https://github.com/callstack/react-native-pager-view/blob/master/example/src/ScrollablePagerViewExample.tsx

**Comment by anatoleblanc** [comment]
PagerView does not seem to have the same behaviour in a FlatList as in a ScrollView. 
Impossible to render as an item of a FlatList. 

If anyone has managed to render a PagerView inside a FlatList, would love to see how they do it :) Thanksss
