### ISSUE TITLE
Any plans to port the latest changes to the `next` branch?

### ISSUE THREAD

**Issue by SimpleCreations** [callstack/react-native-pager-view#578]
I have a large number of pages and the new `LazyPagerView` worked great for me so far.
However, there are some issues I've noticed have been resolved in the current stable branch, this one in particular:
https://github.com/callstack/react-native-pager-view/pull/500

I tried merging it myself, but couldn't due to how dramatically different is the new code (and I'm not that familiar with the codebase and with native development). So I was wondering whether there are plans to support the `next` branch.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
