### ISSUE TITLE
Pager View with reanimated not work

### ISSUE THREAD

**Issue by dodicandra** [callstack/react-native-pager-view#581]
## Environment
expo@latest
react-native-pager-view  5.4.9
react-native-reanimated 2.3.1
react-native-gesture-handler 2.1.0
react-native-screens 3.10.1

## Description
i am trying to use re-animated component with 'createAnimatedComponent' with hooks `useHandler` and `useEvent`.
I hope it goes as expected, but it doesn't seem so

## Reproducible Demo
[expo snack](https://snack.expo.dev/@dodi.candra/pager-view-animated)

**Comment by flexbox** [comment]
Hey @dodicandra 
it works like a charm on my phone iOS 16+

https://user-images.githubusercontent.com/360936/199774122-b75fee0c-b54a-499f-baa1-4bf2df4b06e8.MP4

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by dodicandra** [comment]
> ## Environment
> expo@latest react-native-pager-view 5.4.9 react-native-reanimated 2.3.1 react-native-gesture-handler 2.1.0 react-native-screens 3.10.1
> 
> ## Description
> i am trying to use re-animated component with 'createAnimatedComponent' with hooks `useHandler` and `useEvent`. I hope it goes as expected, but it doesn't seem so
> 
> ## Reproducible Demo
> [expo snack](https://snack.expo.dev/@dodi.candra/pager-view-animated)

I inform the `RC` version it doesn't run well but on the stable version it's fine. so I decided to close this issue
