### ISSUE TITLE
[@next] issue with initialPage & maxRenderWindow

### ISSUE THREAD

**Issue by DJWassink** [callstack/react-native-pager-view#583]
## Environment

Got an expo@45 app running on android (iOS also seems to be afflicted on expo snack).
Using "react-native-pager-view": "^6.0.0-rc.0",

## Description

There are a few issues concerning `initialPage` & `maxRenderWindow`.
I'm not completely sure if those are related or if they are separate issues tho.

First of all setting `initialPage` to for example 50, the resulting page is `50 - buffer`, so for example if we have a buffer of 2. Pages 48 till 52 gets mounted and the 48th page is displayed.
The next issues is, if we have `maxRenderWindow` set, the pages before and after the buffer don't get mounted at all and the pager stops at 48 & 52.

## Reproducible Demo

[https://snack.expo.dev/@djwassink/carefree-blueberries](https://snack.expo.dev/@djwassink/carefree-blueberries)

**Comment by renchap** [comment]
I am having similar issues with the `next` branch.

Is there interest in getting work done on getting the few bugs in v6 fixed and the version released? It looks like it has been a bit forgotten…

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
