### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by PritishSawant** [callstack/react-native-pager-view#584]
## Describe the feature

See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

## Motivation

Use new React and React Native features

## Related Issues

Upgrade to RN 0.68 and so on with new architecture enabled causes issue

**Comment by anton-patrushev** [comment]
Sounds like a duplicate of this https://github.com/callstack/react-native-pager-view/issues/584 issue for adding a support for new RN `Fabric` Renderer

**Comment by okwasniewski** [comment]
Hey, new architecture support was added in 6.1.0 👍
