### ISSUE TITLE
Scroll through all the pages on iOS

### ISSUE THREAD

**Issue by Bardiamist** [callstack/react-native-pager-view#595]
Can bahaviour on iOS be same as on Android? Video attached.
I want to implement scriollable tabs. And tab bar should have indicator. It strange when indicator jumps to position instead of scroll through all the pages on iOS.

https://user-images.githubusercontent.com/22082342/187420744-6f95dfa0-788d-4dfb-a900-0477ac81e1b5.mov

**Comment by hrastnik** [comment]
I'm facing the same issue. On iOS when scrolling to any page other than the adjacent ones, or in other words when you skip a page - it has this glitch.

**Comment by Bardiamist** [comment]
Done here: https://github.com/callstack/react-native-pager-view/pull/641
