### ISSUE TITLE
Carousel Inside LazyPagerView Page does not scroll properly on Android

### ISSUE THREAD

**Issue by crawlappsrn** [callstack/react-native-pager-view#596]
Want to swipe left and right images using Carousel Inside LazyPagerView . Carousel does not scroll properly inside lazypagerview. 

cases
======
- When I scroll image fast it scroll whole page instead of image.
- When I hold carousel for a second and scroll then works greatly.

Note :- Carousel working fine without LazyPagerView on Android.

Let me share package.json dependencies :-

"dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-navigation/bottom-tabs": "^5.11.3",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.13.0",
    "@sentry/react-native": "^3.4.1",
    "axios": "^0.27.2",
    "expo": "~44.0.0",
    "expo-font": "^10.0.5",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-animatable": "^1.3.3",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-inappbrowser-reborn": "^3.6.3",
    "react-native-modalize": "^2.0.13",
    "react-native-pager-view": "^6.0.0-rc.2",
    "react-native-paper": "^4.12.1",
    "react-native-permissions": "^3.3.1",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "^3.13.1",
    "react-native-share": "^7.3.9",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.14.3",
    "react-redux": "^8.0.1",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1"
  },

if you need more information I am ready to share. figuring out this issue for last 1 month.

Thanks!

**Comment by ayuan-gy** [comment]
I have the same problem.

**Comment by dcrawlapps** [comment]
@ayuan-gy Use react-native-gesture-handler ScrollView instead of react-native ScrollView. it will work.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
