### ISSUE TITLE
Invariant Violation - ViewPager Android has been removed from react native

### ISSUE THREAD

**Issue by Asim-Mehran** [callstack/react-native-pager-view#600]
## Environment
Hey dear I am using react native 0.61.5.

## Description
only android build is facing this error through which my application is being crashed. though IOS build is working fine.
- I am not using ViewPager or ViewPagerAndroid anywhere in my application.
- Also I have checked 'react-native-swiper' is not having any ViewPager or ViewPagerAndroid Imports

Please suggest a solution.

Here is my packages.json
{
  "name": "xyz",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "postinstall": "jetifier -r",
    "start": "react-native start",
    "ios": "react-native run-ios",
    "android": "react-native run-android",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@monterosa/react-native-parallax-scroll": "^1.0.4",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/cameraroll": "^1.2.1",
    "@react-native-community/netinfo": "^5.5.1",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.3",
    "@react-native-community/push-notification-ios": "^1.1.1",
    "@react-native-community/slider": "^2.0.9",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-community/viewpager": "^3.3.0",
    "appcenter": "^4.4.5",
    "appcenter-analytics": "^4.4.5",
    "appcenter-crashes": "4.4.3",
    "color-convert": "^1.9.3",
    "create-react-class": "^15.7.0",
    "dateformat": "^2.0.0",
    "encodeurl": "^1.0.1",
    "expo-keep-awake": "^8.1.0",
    "i18next": "^19.0.1",
    "lodash": "^4.17.21",
    "lodash-node": "^3.10.2",
    "moment": "^2.29.4",
    "native-base": "^2.13.4",
    "prop-types": "^15.6.0",
    "pusher-js": "^5.1.1",
    "rc-form": "^2.2.0",
    "react": "16.9.0",
    "react-i18next": "^11.2.5",
    "react-native": "^0.61.5",
    "react-native-autolink": "^1.1.1",
    "react-native-bambuser-broadcaster": "^0.0.17",
    "react-native-bambuser-player": "^0.0.18",
    "react-native-code-push": "^7.0.3",
    "react-native-collapsible": "0.10.0",
    "react-native-confetti": "0.0.6",
    "react-native-dash": "0.0.9",
    "react-native-document-picker": "^3.3.2",
    "react-native-draggable-flatlist": "^1.1.7",
    "react-native-exoplayer": "ngager-group/react-native-exoplayer",
    "react-native-fast-image": "^8.6.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-manager": "^4.0.13-16",
    "react-native-modal-datetime-picker": "^4.7.0",
    "react-native-modalbox": "^1.7.1",
    "react-native-nodemediaclient": "^0.2.18",
    "react-native-pdf": "^6.2.2",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.7.0",
    "react-native-router-flux": "4.0.1",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-spinkit": "^1.5.0",
    "react-native-star-rating": "^1.0.9",
    "react-native-svg": "^12.0.3",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-swipe-list-view": "^2.0.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-tab-view": "^2.13.0",
    "react-native-triangle": "0.0.9",
    "react-native-unimodules": "^0.9.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.1.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-webview": "^8.1.2",
    "react-navigation": "2.11.2",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "resumablejs": "^1.1.0",
    "rn-fetch-blob": "^0.12.0",
    "valid-url": "^1.0.9",
    "victory-native": "^32.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-eslint": "^10.0.2",
    "babel-jest": "^24.9.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "jest": "^24.9.0",
    "jest-react-native": "18.0.0",
    "jetifier": "^1.6.8",
    "metro-react-native-babel-preset": "^0.56.0",
    "prettier": "^1.18.2",
    "react-test-renderer": "^16.9.0"
  },
  "resolutions": {
    "metro-bundler": "0.20.2",
    "color-convert": "1.9.1",
    "uglify-js": "3.8.1"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts",
      "./node_modules/ngager-icon/src/fonts/"
    ]
  }
}

## Reproducible Demo

Please see attached file for complete error info and location of error file.
![image](https://user-images.githubusercontent.com/94536603/189068913-a7dbfead-2323-44bb-9a92-fc9906752d5f.png)

**Comment by filipecatraia** [comment]
https://github.com/callstack/react-native-pager-view/blob/master/MIGRATION.md
