### ISSUE TITLE
[@next] Carousel viewpager does not scroll horizontally properly within LazyPagerView : Android

### ISSUE THREAD

**Issue by dhameliyadharmesh** [callstack/react-native-pager-view#605]
## Environment
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 440.50 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.npm-global/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 22, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Package.json
{
  "name": "PROJECT",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-navigation/bottom-tabs": "^5.11.3",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.13.0",
    "@sentry/react-native": "^3.4.1",
    "axios": "^0.27.2",
    "expo": "~44.0.0",
    "expo-font": "^10.0.5",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-animatable": "^1.3.3",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-inappbrowser-reborn": "^3.6.3",
    "react-native-modalize": "^2.0.13",
    "react-native-pager-view": "^6.0.0-rc.2",
    "react-native-paper": "^4.12.1",
    "react-native-permissions": "^3.3.1",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "^3.13.1",
    "react-native-share": "^7.3.9",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.14.3",
    "react-redux": "^8.0.1",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@babel/preset-typescript": "^7.16.7",
    "@babel/runtime": "^7.17.9",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^8.14.0",
    "jest": "^28.0.3",
    "react-test-renderer": "^18.1.0"
  },
  "private": true
}

## Description
Integrates React-Native-Snap-Carousel within LazyPagerView, Carousel Image Viewer does not scroll properly within LazyPagerView on Android. Works fine on iOS.

Error :
works on android only when I slowly scroll and when I swipe fast it change the page instead of image.

## Reproducible Demo

https://user-images.githubusercontent.com/50448775/190399227-0f1bc260-0216-4af5-8db7-a0a9a4456f7f.mov

## Code
This How I used LazyPagerView
 <LazyPagerView
            style={[s.pagerViewStyle]}
            data={(searchData) ? searchData : null}
            initialPage={route.params.position}
            buffer={10}
            maxRenderWindow={10}
            scrollEnabled={true}
            orientation="horizontal"
            keyExtractor={keyExtractor}
            keyboardDismissMode="on-drag"
            onPageSelected={(e) => {
              dispatch(productActions.doSetProductPosition({ position: e.nativeEvent.position }))
              dispatch(productActions.doSetProductShown({ isProductShown: false }))
            }}
            renderItem={(item, index) => renderItem(item, index)} />

Let me know if you need more information.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
