### ISSUE TITLE
Indicator not moving and some extra blank space below the tabs in iOS with fabric and new architecture enabled

### ISSUE THREAD

**Issue by kartikmittal1996** [callstack/react-native-pager-view#618]
## Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/material-top-tabs    |6.3.0
| @react-navigation/native-stack         |6.9.0
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |3.18.1
| react-native-tab-view                  |3.3.0
| react-native-pager-view                |**6.1.0-rc.1**
| react-native                           |0.70.1
| node                                   |16
| npm or yarn                            |1.22.19

## Description

It is working fine in android but in iOS, indicator not moving in tabs and there is some extra space above pager-view in iOS as you can see in attached video recording.

https://user-images.githubusercontent.com/113685476/196901396-9e83fddc-b930-4de8-ab90-94f1ad6605ef.mov

## Reproducible Demo
[https://github.com/kartikmittal1996/FabricTabNavigation](https://github.com/kartikmittal1996/FabricTabNavigation)

**Comment by kartikmittal1996** [comment]
Hey @alpha0010 can you please take a look at this issue and help to resolve? Thanks.

**Comment by troZee** [comment]
Together with @krozniata and @okwasniewski we are working on it. Here we added some examples to test fabric more https://github.com/callstack/react-native-pager-view/pull/621

**Comment by troZee** [comment]
> 

Right now, we don't have any workaround :'( 
I posted an issue here and I hope it will be resolved soon https://github.com/reactwg/react-native-new-architecture/discussions/89

**Comment by troZee** [comment]
this issue has been fixed in this version https://github.com/callstack/react-native-pager-view/releases/tag/v6.1.0-rc.2 could you check that ?

**Comment by kartikmittal1996** [comment]
Thanks so much @troZee . It's working fine now.

**Comment by sagarjeu** [comment]
@troZee  if I update react native to 0.72.5 new architecture true with update all dependency with latest version app get crash and material top is not working as expected indicator is not visible working fine in 0.71.5
