### ISSUE TITLE
Task :react-native-pager-view:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by AdhamMahmoud98** [callstack/react-native-pager-view#628]
I installed the new architecture version  react-native-pager-view@newarch and I am trying to generate a release APK with the new architecture and I am using the latest react-native-pager-view it causes an issue.

The command I am using for the APK release is: ./gradlew assembleRelease -PnewArchEnabled=true

I tried ./gradlew clean and it succeed and every time I try to generate an APK I get the same error:
Task :react-native-pager-view:compileReleaseKotlin FAILED

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/46315255/199475743-7ee32b1f-b9f2-428a-9497-b3633d464793.png">

**Comment by AdhamMahmoud98** [comment]
@okwasniewski 

 "react": "18.1.0",
 "react-native": "0.70.3",

**Comment by okwasniewski** [comment]
Hey @AdhamMahmoud98,

Thanks for providing the versions. Can you try first cleaning the build folder with `git clean -fdx android`, then generating codegen files using `./gradlew generateCodegenArtifactsFromSchema` and then building with the same command that you used.
