### ISSUE TITLE
Incorrect pages transition animation when setPage is called and the new page isn't next or previous from current page

### ISSUE THREAD

**Issue by CarlosSLoureiro** [callstack/react-native-pager-view#636]
## Environment
Platform: iOS
react-native: 0.69.6
react-native-pager-view: 6.0.2

## Description
When I change the page calling the `setPage` method and the new page value is not next or previous from current page it shows an incorrect transition animation.
For example I have 3 pages. I'm in the page 1. And I will change with `setPage` to page 3 the animation that I'm expecting it's the transition from page 1 (current) to 3 but it shows from page 2 to 3.

## Reproducible Demo
https://user-images.githubusercontent.com/19580424/200635670-bf965360-0dda-4bfb-8c21-f9ea2f1ae7f7.mp4

**Comment by CarlosSLoureiro** [comment]
@krozniata How can I test the fix? I have already upgraded to 6.1.1 but still having same issue...
I'm also using expo 46.0.16 to test the application here (don't know if its relevant)

**Comment by troZee** [comment]
Are you testing it locally or in expo go ? Could you check, if correct version of pager has been used ?

**Comment by CarlosSLoureiro** [comment]
I'm testing in expo go (SDK 46, Client version 2.25.3.101) from iOS (16.1) Simulator.
I've upgraded the react-native-pager-view package with yarn to 6.1.1

**Comment by krozniata** [comment]
@CarlosSLoureiro **Pager View** isn't yet updated in Expo SDK. In order to test the fix you need to test it locally

**Comment by CarlosSLoureiro** [comment]
@krozniata Oh thanks for the info. I've used `expo eject` to test it without expo go and the fix works! Thank you!
