### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCViewPager

### ISSUE THREAD

**Issue by maaliHasan** [callstack/react-native-pager-view#652]
## Environment

{
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.9",
    "js-yaml": "^4.1.0",
    "moment": "^2.24.0",
    "native-base": "3.4.19",
    "react-native-devsettings-android": "^0.3.0",
    "react-native-elements": "^1.2.7",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-keychain": "^8.0.0",
    "react-native-localization": "^2.1.6",
    "react-native-material-menu": "^2.0.0",
    "react-native-pager-view": "^6.1.1",
    "react-native-permissions": "^2.2.2",
    "react-native-router-flux": "^4.0.6",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-simple-dialogs": "^1.4.0",
    "react-native-super-grid": "^4.1.3",
    "react-native-svg": "^13.0.0",
    "react-native-tab-view": "^3.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^7.1.0",
    "recyclerlistview": "^2.0.12",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "sitemap": "^6.3.3",
    "styled-components": "^5.3.5"
  },}

## Description

I'm trying to use react-native-tab-view to use the Tabs view in my RN Android app, but I'm getting this error! 
Any solutions, please?

**Comment by troZee** [comment]
Duplicated:
https://github.com/callstack/react-native-pager-view/issues/399
https://github.com/callstack/react-native-pager-view/issues/150
https://github.com/callstack/react-native-pager-view/issues/116
