### ISSUE TITLE
PagerView RNCViewPager keeps on the content after run setPage

### ISSUE THREAD

**Issue by CarlosSLoureiro** [callstack/react-native-pager-view#653]
## Environment

Platform: iOS
react-native: 0.69.6
react-native-pager-view: 6.1.1

## Description

All my pages are ScrollView and when I change the page with setPage I can't scroll the new page (or old page if I try to back) because the element RNCViewPager is on the ScrollView content element. At first entry it works but if setPage is used it happen.
I'm almost sure it's a problem from this package because in react-native-pager-view 5.4.24 it don't happen.

### At first entry in 6.1.1 and 5.4.24: (works)
<img src="https://user-images.githubusercontent.com/19580424/204110415-4584409c-ffb3-4043-a224-a04bbbf51811.png" width="335" height="766" />

### After I use setPage in 6.1.1: (keep RNCViewPager always from now)
<img src="https://user-images.githubusercontent.com/19580424/204110440-28c846da-1909-40bc-b2d0-dd7d278f522a.png" width="335" height="766" />

### After I use setPage in 5.4.24: (works)
<img src="https://user-images.githubusercontent.com/19580424/204110451-5609d702-da48-4ab8-9bb5-5ed0746c54ea.png" width="335" height="766" />

**Comment by krozniata** [comment]
Hi @CarlosSLoureiro 

Could you check if this issue still exists in version `6.1.2`?

**Comment by CarlosSLoureiro** [comment]
Seems fixed in `6.1.2`. Thank you @krozniata
