### ISSUE TITLE
Scrollable example is broken 

### ISSUE THREAD

**Issue by Bardiamist** [callstack/react-native-pager-view#658]
By some reason "Scrollable PagerView Example" is broken in 6.1.2
`setPage` don't work

I wanted to use example for create the issue about: `nativeEvent.position` returns wrong values on iOS only first time when use `setPage`

https://user-images.githubusercontent.com/22082342/204744481-849bfc3a-d675-4247-bd99-733a562bc325.mov

**Comment by paulpopus** [comment]
Hey, we're also experiencing that setPage or setPageWithoutAnimation don't work and both silently fail.

We can still change screens using scroll gestures so I think it's to do with the library. Will investigate later this week if I have the time.

**Comment by ryanSoftwareEngineer** [comment]
any work arounds for this? i'm not able to use setPage with a dynamic list of content

**Comment by MrRefactor** [comment]
is it still valid?
