### ISSUE TITLE
Example can't run on android

### ISSUE THREAD

**Issue by asapMaki** [callstack/react-native-pager-view#669]
## Environment
Your example project.

## Description
I have an issue in my project and wanted to see if it is happening in your example project, wasn't able to run it after cloning this repo, installing and triggering yarn android command.

Issue is related to metro and this is the error:
error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault

Checking the node_modules, this file does exist.

## Reproducible Demo
Clone this repository.
Navigate to example folder.
yarn
yarn android

**Comment by thanggggg1** [comment]
do you have solution ?

**Comment by asapMaki** [comment]
Unfortunately, no, wish I had it though

**Comment by toter3** [comment]
i had no problem running the example on Android.

try running `yarn` from the root folder as well
