### ISSUE TITLE
Task :@react-native-community_viewpager:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by RevivalDev** [callstack/react-native-pager-view#674]
## Environment
 "react": "16.13.1",
 "react-native": "0.63.2"
"@react-native-community/viewpager": "^5.0.11"

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 38.44 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Description
run ./gradlew assembleRelease 

error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-community_viewpager:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /Users/revival/.gradle/caches/transforms-2/files-2.1/9c6c81038e4c01dabde31d5d71d4bfd8/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by troZee** [comment]
Please install pager using `yarn add react-native-pager-view`. Community version is not supported and has been decommission
