### ISSUE TITLE
'React/RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by liptonzuma** [callstack/react-native-pager-view#688]

**Comment by liptonzuma** [comment]
<img width="1139" alt="Screenshot 2023-02-05 at 1 22 17 PM" src="https://user-images.githubusercontent.com/61327021/216821437-a0b2a3d7-5ad9-4735-b9ba-abec87e7686e.png">

**Comment by jffs** [comment]
I have the same error, how did you fix it?

**Comment by rupam999** [comment]
Same error getting
