### ISSUE TITLE
Module has no exported member 'LazyPagerView' in version 7.0.0-rc.0

### ISSUE THREAD

**Issue by LaGregance** [callstack/react-native-pager-view#690]
## Description

Hi, switching from version `6.0.0-rc.0` to `7.0.0-rc.0`, I get the following error in my import of LazyPagerView:
```
Module '"react-native-pager-view"' has no exported member 'LazyPagerView'
```

Did I miss something or LazyPagerView will be no longer maintained ?
Thanks for help.

**Comment by LaGregance** [comment]
Does anyone have any information on this?

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/issues/673
