### ISSUE TITLE
PagerView breaks sometimes on conditional render

### ISSUE THREAD

**Issue by ilyadynin** [callstack/react-native-pager-view#720]
## Environment

        "react-native": "0.71.6",
        "react-native-pager-view": "6.1.2",

## Description

okay, so I have two PagerViews that are rendered conditionally, the pagerview is wrapped into a custom component

{condition ? <PagerView1 /> : <PagerView2 />}

sometimes one of them just breaks, so it is dragable to the right but the upcoming image is not rendered but there is just white space that is a little draggable like overdrag, but I cannot scroll anywhere, also I track the currentPage with a function, and when the error occurs currentPage is set to 9223372036854776000, which is the highest number that javascript can work with

  const handlePageSelected = (event) => {
        setCurrentPage(event.nativeEvent.position);
    }; 

## Reproducible Demo

set up two pagerViews, inside of a custom component, then render them on condition, make it possible to switch between them and then try to do that some times and look if pagination and swiping breaks

**Comment by yqz0203** [comment]
Seems it's a native problem, the effective way is changing the key of `PagerView` when data change.

**Comment by ilyadynin** [comment]
@yqz0203 yeah probably, what I'll try is to make 2 custom pagerviews with a paginated vertical flatlist

**Comment by MrRefactor** [comment]
is it still valid with latest version of lib?
