### ISSUE TITLE
Any way to control the animation duration/speed from setPage(idx)?

### ISSUE THREAD

**Issue by artem-kzm** [callstack/react-native-pager-view#732]
## Ask your Question
When setting the page by the setPage function the transitioning between pages would look nicer if it was possible to slow down the animation.... any ideas?

**Comment by okwasniewski** [comment]
Hello, 

As the animation transition is controlled by the native side (ViewPager2 dependency) there is no way to control the animation speed. Only configuration is to enable / disable animation.
