### ISSUE TITLE
PropsParserContext.h 'react/utils/ContextContainer.h' file not found

### ISSUE THREAD

**Issue by jslok** [callstack/react-native-pager-view#743]
## Environment

RN0.72.3
rnpagerview 6.2.0

## Description

On ios building in xcode I get the following error:
`PropsParserContext.h 'react/utils/ContextContainer.h' file not found`

**Comment by okwasniewski** [comment]
Hello @jslok, 

Did you run `pod install` inside the ios directory?

**Comment by cipolleschi** [comment]
Does an empty react native app build without the `react-mative-pager-view` lib? if yes, that;s not a react-native issue.
If that's not the case, please open an issue in the react native repo with a reproducer created starting from [this template](https://github.com/react-native-community/reproducer-react-native)

**Comment by rditerwich** [comment]
Workaround until resolved by react native: 

Add 'react-native/ReactCommon' to the header search path in your Podfile (in my case, the "RNScreens" pod was giving the problem):

```
    installer.pods_project.targets.each do |target|
          if target.name == "RNScreens"
              append_header_search_path(target, "${PODS_ROOT}/../../node_modules/react-native/ReactCommon")
          end
        end
```

Also define the  append_header_search_path in your Podfile:

```
  def append_header_search_path(target, path)
      target.build_configurations.each do |config|
          # Note that there's a space character after `$(inherited)`.
          config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
          config.build_settings["HEADER_SEARCH_PATHS"] << path
      end
  end
```

**Comment by manishnaruka** [comment]
> Workaround until resolved by react native:
> 
> Add 'react-native/ReactCommon' to the header search path in your Podfile (in my case, the "RNScreens" pod was giving the problem):
> 
> ```
>     installer.pods_project.targets.each do |target|
>           if target.name == "RNScreens"
>               append_header_search_path(target, "${PODS_ROOT}/../../node_modules/react-native/ReactCommon")
>           end
>         end
> ```
> 
> Also define the append_header_search_path in your Podfile:
> 
> ```
>   def append_header_search_path(target, path)
>       target.build_configurations.each do |config|
>           # Note that there's a space character after `$(inherited)`.
>           config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
>           config.build_settings["HEADER_SEARCH_PATHS"] << path
>       end
>   end
> ```

Did not work for me. Any other work around?

**Comment by manishnaruka** [comment]
> RNScreens

How did you know that RNScreens was giving you the problem ?

**Comment by MrRefactor** [comment]
Closing as its not related to `react-native-pager-view`
