### ISSUE TITLE
SetPage not working on IOS on v7.0.0 next

### ISSUE THREAD

**Issue by samiullah452** [callstack/react-native-pager-view#749]
## Environment

React native pager view v7.0.0 next
React native tab view v3.5.2
React native 0.69.9
React 18.2

## Description

SetPage method of pager view is called but it does not change the page when used in conjunction with react native tab view. React native tab views pages contain pager view and on clicking a tab it should change the page but it does not happen. Only on IOS this happens and on android it works fine. Also i noticed that this happens on next version and on other versions the swiping part is disabled for tab view

**Comment by samiullah452** [comment]
SetPageWithoutAnimation works only if I use setTimeout with value of 0

**Comment by CarlosSLoureiro** [comment]
Same here, setPage not work but setPageWithoutAnimation works.

**Comment by MrRefactor** [comment]
Closing as we are moving away from `next` experimental implementation.
