### ISSUE TITLE
Strange values of the "offset" property in the "onPageScroll" method.

### ISSUE THREAD

**Issue by AndrewNes** [callstack/react-native-pager-view#751]
## Environment

"react": "17.0.2",
"react-native": "0.66.4",
"react-native-pager-view": "^6.2.0"

## Description

Good afternoon! Initially, I want to thank you for creating such a wonderful library. It covers a lot of tasks in my projects, but I have difficulties with setting up the parallax effect.

Since the offset property cannot have a negative value in the "onPageScroll" method. During which I can't determine the swipe side (backward or forward).

In addition, when I swipe back, the value is not something that does not become less than 0, but also turns into 0.99 by the moment, which is why any animation moves in leaps.

![1](https://github.com/callstack/react-native-pager-view/assets/27921682/99cc22f1-edf1-4b51-a390-95db920f2d7e)
offset = _(0.000, 0.100, 0.320, ..., 1.000)_

![2](https://github.com/callstack/react-native-pager-view/assets/27921682/a7db8586-f0c2-43f0-b9fc-e844ed86ea78)
offset = _(0.000, 0.990, 0.800, ..., 0.000)_

This does not allow the use of animation of this kind:

``` javascript
  const onPageScroll = usePagerScrollHandler<onPageScrollEventType>(
    {
      onPageScroll: (e: onPageScrollEventType): void => {
        'worklet';
       // ...
        opacityValue.value = 1 - e.offset;
       // ...
      },
    },
    'onPageScroll'
  )
```

After my research, I found a place to calculate this value on iOS:
<img width="899" alt="3-screen" src="https://github.com/callstack/react-native-pager-view/assets/27921682/cf859e0c-aa6c-46dd-aa57-14346e5ae12f">
_(../node_modules/react-native-pager-view/ios/ReactNativePageView.m)_

However, I have not found where to fix it in Android, are there any solutions to my problem?

_Sincerely, Andrey!_

**Comment by AndrewNes** [comment]
I'm sorry! I didn't notice a change in the "position" property at the time of scrolling back.
If we take it into account, then the creation of animations is more than real ...
And even despite this, the "offset" property has non-trivial values)

**Comment by troZee** [comment]
@AndrewNes please checkout one of our example here https://github.com/callstack/react-native-pager-view/blob/master/example/src/HeadphonesCarouselExample.tsx . I was not able to reproduce this issue. In case of noticed bug, please create a new issue with the full description.
