### ISSUE TITLE
[next][android] fix gap 

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-pager-view#764]
![Screenshot_1693505469](https://github.com/callstack/react-native-pager-view/assets/12766071/2f8e894b-ffb6-4680-89ba-906e263fca46)
![Screenshot_1693505510](https://github.com/callstack/react-native-pager-view/assets/12766071/ae492ef4-0af3-49fe-80a8-fc72e0cace2a)

Spacing issue

_Originally posted by @troZee in https://github.com/callstack/react-native-pager-view/issues/763#issuecomment-1701540408_

**Comment by MrRefactor** [comment]
Closing as we are moving away from `next` experimental implementation.
