### ISSUE TITLE
Issue with the initial render when using the new architecture.

### ISSUE THREAD

**Issue by Shivangigupta01** [callstack/react-native-pager-view#774]
## Environment

**react-native-tab-view	3.5.2
react-native-pager-view	6.2.1**
**react-native	0.72.5
node	20.8.0
npm or yarn	10.1.0**
@react-navigation/native	6.1.8
@react-navigation/bottom-tabs	6.5.9
@react-navigation/drawer	6.6.4
@react-navigation/native-stack	6.9.14
react-native-safe-area-context	4.7.2
react-native-screens	3.25.0
react-native-gesture-handler	2.13.1
react-native-reanimated	3.5.4

https://github.com/callstack/react-native-pager-view/assets/141234465/7b885ed1-2000-4b53-b4b7-80c535478bfe

## Description

I am using react-native-tab-view to render tab in my app.

**Issue details:**
- **After enabling the new architecture in my app**, the content in the respective tab is not visible on the initial render of the screen.
- After Toggling the active/initial tab from above , causes the UI to render properly.
- This issue is only encountered when the new architecture is enabled in the app.
- This scenario is valid for iOS.
- For Android, the data is rendered in respective tabs but gets stuck if a list is rendered inside the tab or the content size is more.

Here is the issue reference for react-native-tab-view: https://github.com/react-navigation/react-navigation/issues/11634
I was suggested to open the issue in this repository.

**Expected behavior**
The component should always render the data for each tab correctly, regardless of its state, whether it is initially rendered or not.

## Reproducible Demo
https://snack.expo.dev/2_7JifhHl

**Comment by osdnk** [comment]
For context, this is happening only in `0.72.5+`. Particularly, this is not happening in `0.72.4` (as in the example)

**Comment by shivanip-iprogrammer** [comment]
> For context, this is happening only in `0.72.5+`. Particularly, this is not happening in `0.72.4` (as in the example)

it's happening on RN #0.72.2 as well.

/

))

**Comment by krozniata** [comment]
@Shivangigupta01 @shivanip-iprogrammer Could you check if issue still exists in `v6.2.2`?

**Comment by shivanip-iprogrammer** [comment]
> @Shivangigupta01 @shivanip-iprogrammer Could you check if issue still exists in `v6.2.2`?

Worked with  v6.2.2. Thanks @krozniata
