### ISSUE TITLE
NSInternalInconsistencyException crashes app on iPad

### ISSUE THREAD

**Issue by prudhvi-k23** [callstack/react-native-pager-view#789]
## Environment

iOS
"react-native-pager-view": "6.2.0",
"react-native": "0.72.3"

## Description
Getting a crash in Firebase Crashlytics.

Fatal Exception: NSInternalInconsistencyException
Ending a faux host modal session without a matching begin!

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0xf28b4 
1  libobjc.A.dylib                0x19eb4 
2  Foundation                     0x11018c 
3  UIKitMacHelper                 0x5616c 
4  UIKitCore                      0x345e58 
5  UIKitCore                      0x344308 
6  UIKitCore                      0x98554 
7  UIKitCore                      0x2079b0 
8  UIKitCore                      0x5aaca4 
9  UIKitCore                      0x5aac84 
10 UIKitCore                      0x5aac84 
11 UIKitCore                      0x5aac84 
12 UIKitCore                      0x817d4
13 UIKitCore                      0xcf9028 
14 AVKit                          0x9ca88 
15 libobjc.A.dylib                0x13628 
16 libobjc.A.dylib                0xae84 
17 libobjc.A.dylib                0xae28 
18 AVKit                          0x3ec08 
19 libobjc.A.dylib                0x13628 
20 libobjc.A.dylib                0xae84 
21 libobjc.A.dylib                0xae28 
22 UIKitCore                      0xcebc8 
23 UIKitCore                      0xce998 
24 AVKit                          0x52f4c 
25 Foundation                     0x766fa4 
26 Foundation                     0x6dff8 
27 CoreFoundation                 0x1f7f0 
28 CoreFoundation                 0x1f72c 
29 UIKitCore                      0xce974 
30 Foundation                     0x68f68
31 Foundation                     0x68e90
32 acloudguru                     0x66e200 -[ReactNativePageView .cxx_destruct] + 32 (ReactNativePageView.m:32)

**Comment by MrRefactor** [comment]
Does the issue still exist?
