### ISSUE TITLE
What happened to `LazyPagerView`?

### ISSUE THREAD

**Issue by MoritzCooks** [callstack/react-native-pager-view#801]
## Ask your Question

I just found the issue #227 about preventing render for all pages at once. In the issue there is a PR mentioned that provides `LazyPagerView` component and it's also reference to 6.0.0-rc  but it's not part of version 6.2.3

Is this available now or not (any more)? 

Currently I have to prevent rerendering of all pages.

Thanks for clarification.

**Comment by troZee** [comment]
@MoritzCooks hope it clarifies the situation https://github.com/callstack/react-native-pager-view/issues/673. 
If you would like to achieve the lazy effect, you can use this library https://reactnavigation.org/docs/tab-view/ and hide the tabs.

**Comment by MoritzCooks** [comment]
Thanks for the clarification! 
I actually found a workaround for that 🙁

**Comment by dareman-venkat** [comment]
@MoritzCooks  Could you please share the workound for the lazy loading for not rendering all compoents

**Comment by efstathiosntonas** [comment]
@MoritzCooks would love to see the workaround too, can you please post an example? Thanks!

**Comment by MoritzCooks** [comment]
Oh sorry for responding so late @dareman-venkat and @efstathiosntonas .

This is quite a while but here is my implementation: 

```TS
      <PagerView
        offscreenPageLimit={2}
        ref={pagerRef}
        initialPage={0}
        style={styles.pager}
        scrollEnabled={false}
      >
        {screens?.map((screen, index) => (
          <OnboardingScreen
            key={screen.id}
            shouldRender={[
              // This renders only the previous, current and next page.
              // Used to increase performance as otherwise ALL onboarding screens would be rerendered on every single change
              state.page,
              state.page + (nextAndPrevPageConfig?.next.distance || 0),
              state.page - (nextAndPrevPageConfig?.prev.distance || 0),
            ].includes(index)}
            {...screen}
            onContinue={() => handleNextPage(screen)}
          />
        ))}
      </PagerView>
```


### `shouldRender`
The children have a custom `shouldRender` prop which accepts a boolean. 
- If true, render the component the way it should. 
- If false, return as early as possible within the child: `if (!shouldRender) return null`

To check whether `shouldRender` is true or false, I keep track of the current page outside of the PagerView in a reducer function. I need this level of complexity because in my case you can skip pages based on your answer in a page. 

Probably this could be way easier with the `onPageSelected` callback which keeps track of a selectedPage state.

In addition I add a tolerance of 2 pages forwards and backwards to prerender the screen before it gets shown. 


I hope this still helps!
