### ISSUE TITLE
RNCViewPager/RNCViewPagerComponentDescriptor.h file not found

### ISSUE THREAD

**Issue by atultiwaree** [callstack/react-native-pager-view#812]
## Description

After enabling react new arch this error is shown in xcode

**Comment by vinamrahalgar** [comment]
Any idea on how to fix this?

**Comment by RalissonMattias** [comment]
Same in RN 73.8

**Comment by vipom** [comment]
A [PR that fixes this has been merged in master](https://github.com/callstack/react-native-pager-view/pull/830) so we should wait for a new release to be made.

**Comment by MrRefactor** [comment]
Fixed in 6.3.2 release
