### ISSUE TITLE
IOS getting blank screen when moving between tabs

### ISSUE THREAD

**Issue by gitdevnaresh** [callstack/react-native-pager-view#815]
I am getting issue blank screen when i am moving to tabs, this issue i am facing only on IOS. [enter image description here](https://i.stack.imgur.com/RJTQ6.png)

Packages using:
"react-native-tab-view": "^3.5.2", "react-native-pager-view": "^6.2.3", "react-native": "0.71.7",

[enter image description here](https://i.stack.imgur.com/x5MBe.png)

[enter image description here](https://i.stack.imgur.com/JzRqZ.png)

When i came first time working, moving between tabs getting like this.

I am trying with version upgrade and degrade but still issue not resolved.

**Comment by samiullah452** [comment]
Had the exact same problem. It seems its a problem combining tab view and pager view. I had got it working somehow with next version of pager view but had to make a fix for setPage in IOS. Try using react-native-collapsable-tab-view maybe that might fix your problem but it introduces a problem of scrolling between tabs.

**Comment by adxzhang1** [comment]
Seeing this also, works when using 6.1.4
