### ISSUE TITLE
Support RN 0.74

### ISSUE THREAD

**Issue by NiuGuohui** [callstack/react-native-pager-view#821]
## Describe the feature

Compatible with version 0.74

**Comment by troZee** [comment]
Could you provide more context, on what does not work?

**Comment by troZee** [comment]
What version of pager?

**Comment by NiuGuohui** [comment]
6.3.1

**Comment by troZee** [comment]
<img width="486" alt="Screenshot 2024-04-29 at 11 26 57" src="https://github.com/callstack/react-native-pager-view/assets/12766071/ff5fdde7-3396-4e50-b323-ec586de2b80a">

We did an investigation and for some reason, cpp code does not see those modules

**Comment by NiuGuohui** [comment]
> <img alt="Screenshot 2024-04-29 at 11 26 57" width="486" src="https://private-user-images.githubusercontent.com/12766071/326390424-ff5fdde7-3396-4e50-b323-ec586de2b80a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODQzMTIsIm5iZiI6MTcxNDM4NDAxMiwicGF0aCI6Ii8xMjc2NjA3MS8zMjYzOTA0MjQtZmY1ZmRkZTctMzM5Ni00ZTUwLWIzMjMtZWM1ODZkZTJiODBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA5NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YTEzYmNlZmYzNzJmNzg2ZTM5MGU4MmM2Nzg2ZmMwMWM2ZGRiYWE3YTRlMzEwMjcxNjczZDgyYjhjZjFjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.irMAHT_OA4oxBuE412eswiRuLp1gigKzYz-_-WTqte8">
> We did an investigation and for some reason, cpp code does not see those modules

so how to resolve this problem? I'm not very familiar with C++.

**Comment by troZee** [comment]
We did not, we are still looking for a cause of this problem

**Comment by nikitapilgrim** [comment]
iOS build same problem

**Comment by sriharsha-y** [comment]
It might be same as mentioned here https://github.com/callstack/react-native-pager-view/issues/822#issuecomment-2095252157

**Comment by sulemanbutt10** [comment]
can anyone please guide which version of react-native-pager-view is compatible with react-native (v0.71.18)

i am also using other libraries:

react-native-collapsible-tab-view
react-native-head-tab-view
react-native-tab-view-collapsible-header

i also have to update these ones as well according to react native (v0.71.18)
can anyone please guide?

**Comment by troZee** [comment]
Resolved in https://github.com/callstack/react-native-pager-view/pull/829
