### ISSUE TITLE
A problem occurred configuring project ':react-native-pager-view'.  compileSdkVersion is not specified.

### ISSUE THREAD

**Issue by getsettalk** [callstack/react-native-pager-view#824]
## Environment

System:
  OS: Windows 10 10.0.19043
  CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  Memory: 19.31 GB / 31.97 GB
Binaries:
  Node:
    version: 20.11.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.21
    path: D:\RohaBhai\node_modules\.bin\yarn.CMD      
  npm:
    version: 10.3.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-233.14808.21.2331.11709847       
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

PS D:\RohaBhai\android> 

## Description
**Why showing this error when** 
building debug app or cleaning gradle

```
./gradlew clean

```
Package version:
```
    "react-native-pager-view": "^6.3.1",
```

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\RohaBhai\node_modules\react-native-pager-view\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':react-native-pager-view'.
> org/jetbrains/kotlin/config/LanguageVersion

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-pager-view'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

**How to fix this** 

This package has  automatic installation, and before its working fine but i don't know why its not working now.

**Comment by alihaydar56** [comment]
did you find any solution?

**Comment by getsettalk** [comment]
Not yet

**Comment by BharatEdu97** [comment]
ANY SOLUTIONS?

**Comment by joaomadeira20** [comment]
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle * Try:
