### ISSUE TITLE
Dynamic render next or previous component

### ISSUE THREAD

**Issue by thanhduyspkt** [callstack/react-native-pager-view#83]
# Question

If I remember correctly, I worked with UIPageViewController in iOS for years.
I only keep data in memory, then UIPageViewController provide the page index to asking for a correct ViewController. I would be nice because It renders three views always.
So, I only care about current view, next view and previous view.

Could you please support this feature instead of rendering rest of views?

**Comment by ferrannp** [comment]
CC @troZee & @dratwas. WDYT?

**Comment by troZee** [comment]
Probably we should change API to support this feature. When subviews are added as a child, they are loaded eagerly. If we want to load each view in lazy way, we need to consider to do it in another way. (Maybe api should be the same like in FlatList ?).  Current solution is also problematic like I described here  https://github.com/react-native-community/react-native-viewpager/issues/81 and probably should be changed, but now I don't know how to do it TBH.
