### ISSUE TITLE
[6.3.1] next merged into master

### ISSUE THREAD

**Issue by Bardiamist** [callstack/react-native-pager-view#837]
## 6.3.1 problems (actual for 6.3.3)

In this commit https://github.com/callstack/react-native-pager-view/commit/280c3a3f86fa686c1c1a29c1c8499cf4d03c4231 `next` branch merged into `master` branch. Looks as mistake.

1. Now TypeScript required `useNext`. What to use if I want stable version?

2. `PagerView` stopped to pass props into pages on Android.

In `6.3.0` it was:
```
{
  "style": [
    null,
    {
      "position": "absolute",
      "left": 0,
      "right": 0,
      "top": 0,
      "bottom": 0
    }
  ]
}
```
Pages on iOS stil receive these props in 6.3.3.
Also I remember here was `collapsable: false`. Should be missed even before 6.3.1.
So what to do now, manually set `collapsable={false}` and style `flex: 1`?

**Comment by Bardiamist** [comment]
>if you want to continue using stable implementation just dont add useNext prop.

It's not optional prop in TypeScript

**Comment by Bardiamist** [comment]
@MrRefactor Reproduced styles problem here https://github.com/Bardiamist/diff/tree/pager

**Comment by valtism** [comment]
This should be an optional type, but in the mean time you can remove the TS error and maintain original behaviour by using `useNext={false}`

**Comment by MrRefactor** [comment]
Closing as per: https://github.com/callstack/react-native-pager-view/releases/tag/v6.6.0
