### ISSUE TITLE
onPageSelected wrong triggered when the `key`  of subComponent change 

### ISSUE THREAD

**Issue by KingAmo** [callstack/react-native-pager-view#84]
# Bug

```
   <ViewPager onPageSelected={this.onPageSelected}>
      <Component1 key={this.state.key1}/>
      <Component2 key={this.state.key2} />
   </ViewPager>
```
```
     onPageSelected = (e) => {
         this.setState({
             selectedTab: e.nativeEvent.position,
         });
     };
```
when `key1` or `key2` changes, the `onPageSelected` props is triggered incorrectly，and ` e.nativeEvent.position` is changed incorrectly

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 919.79 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

Library version: `2.0.1`

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by troZee** [comment]
Hey 👋 . Thank you for reporting issue. Can you provide reproducible code ?

**Comment by ferrannp** [comment]
@KingAmo why would you change the `key` values? I think you should always use the same value for a specific page, if not, problems like this will arise.

**Comment by KingAmo** [comment]
@ferrannp i submit a issue https://github.com/react-native-community/react-native-viewpager/issues/77,  i can't use `ref` props of child component of `viewpager`, so i can't call the function of child component use `ref` props, so i have to change the `key` of child component to re-mount it, and the  child component's `componnetDidMount` will call again and trigger the function i want call

**Comment by karthik-appliedsyntax** [comment]
Hi @KingAmo  even i am facing same issue initial position is 0 when i triggered onPageSelected e.nativeEvent.position will change to 1.  Again if i triggered scroll  onPageSelected  position is not changing e.nativeEvent.position return  1 only.

can you help me out from this issue.

**Comment by troZee** [comment]
@karthik-appliedsyntax 
Can you clone this repo https://github.com/troZee/viewPagerExample and provide reproducible example ?

**Comment by karthik-appliedsyntax** [comment]
Hi @troZee  Actually i tried for  Dot indicators for Android. 
have you customised  Dot indicators for View Pager in Android ?

**Comment by troZee** [comment]
Dots are android has not been implemented yet https://github.com/react-native-community/react-native-viewpager/issues/94

**Comment by karthik-appliedsyntax** [comment]
Hi @troZee  i am facing issue in loading initial page.
I tried your view-pager Example in that your Views are static and its work fine for me also but in my case Views are Dynamic so i need to render it dynamically at that time i am facing issue with loading initial page .

Here is my code

<ViewPager style={styles.viewPager}
                        initialPage={1}
                        keyboardDismissMode="on-drag"
                        scrollEnabled={true}
                     
                        onPageScroll={this.onPageScroll}
                        onPageSelected={this.onPageSelected}
                        onPageScrollStateChanged={this.onPageScrollStateChanged}
                      
                        ref={viewPager => { this.viewPager = viewPager; }}>
                    
                        {this.state.pages && this.state.pages.length>0 && this.state.pages.map(page => this.renderPage(page))}
                        
                    </ViewPager>  

and my render function

renderPage(page: CreatePage) { 
        return (
            <View key={page.key} collapsable={false} style={styles.renderBorder}>
                <Destination 
                    id={page.id} 
                    slug={page.location}
                    description={page.description} 
                />
            </View>
        );
    }
