### ISSUE TITLE
Negative pageMargin not working on iOS - Seeking alternative solution for desired effect

### ISSUE THREAD

**Issue by luckykellan** [callstack/react-native-pager-view#840]
Hi,

I'm experiencing an issue with the pageMargin property in the React Native Pager View on iOS. It seems that setting a negative value for pageMargin doesn't work, which is preventing me from achieving the desired layout as shown in the attached image.

Expected Behavior:
The pageMargin should accept negative values on iOS to allow for the overlap effect between pages.

Actual Behavior:
On iOS, setting a negative value for pageMargin has no effect.

Screenshots:
<img width="517" alt="image" src="https://github.com/callstack/react-native-pager-view/assets/109934256/0895d752-bbe7-45d8-a53f-1ed680e5a769">
I'm looking for a solution or a workaround to achieve the same overlapping page effect on iOS. Any suggestions or alternative methods to implement this layout would be greatly appreciated.

Thank you for your help!

**Comment by Slepzs** [comment]
@luckykellan  Did this fix your issue, or did you end up doing something else?

**Comment by avirankatz** [comment]
@MrRefactor you removed the `ScrollView` based implementation in v6.6.1 right? I can't seem to get negative `pageMargin` to work in iOS

**Comment by MrRefactor** [comment]
> [@MrRefactor](https://github.com/MrRefactor) you removed the `ScrollView` based implementation in v6.6.1 right? I can't seem to get negative `pageMargin` to work in iOS

What version are you using?

**Comment by avirankatz** [comment]
> > [@MrRefactor](https://github.com/MrRefactor) you removed the `ScrollView` based implementation in v6.6.1 right? I can't seem to get negative `pageMargin` to work in iOS
> 
> What version are you using?
> 

v6.7.0

**Comment by di-sukharev** [comment]
@MrRefactor how do we do this on ios on version 6.9.1?
