### ISSUE TITLE
'RNCViewPager/RNCViewPagerComponentDescriptor.h' file not found

### ISSUE THREAD

**Issue by z4o4z** [callstack/react-native-pager-view#843]
## Environment

- react-native: 0.74.3
- react: 18.3.1
- react-native-pager-view: 6.3.3
- mac: M1 Pro - 14.5 (23F79)
- new architecture: enabled (`ENV['RCT_NEW_ARCH_ENABLED'] = "1"`)

## Description

Upgraded to the latest version and getting the xcode errors:
<img width="1061" alt="image" src="https://github.com/callstack/react-native-pager-view/assets/9130301/b18fac67-0a31-4c46-b64e-646e77eac203">

## Reproducible Demo
- don't have demo :(

**Comment by sohayb** [comment]
Although I don't a reproducible demo myself either, it was happening in my app.
This patch can be applied to fix it:
```patch
diff --git a/ios/Fabric/RNCPagerViewComponentView.mm b/ios/Fabric/RNCPagerViewComponentView.mm
index 83fa49768804b9f93e50d0d1fd82c3a131c7f020..a8f792ad18af114834903076709fe143a1afc353 100644
--- a/ios/Fabric/RNCPagerViewComponentView.mm
+++ b/ios/Fabric/RNCPagerViewComponentView.mm
@@ -2,7 +2,7 @@

 #import <Foundation/Foundation.h>
 #import "RNCPagerViewComponentView.h"
-#import <RNCViewPager/RNCViewPagerComponentDescriptor.h>
+#import <react/renderer/components/RNCViewPager/RNCViewPagerComponentDescriptor.h>
 #import <react/renderer/components/pagerview/EventEmitters.h>
 #import <react/renderer/components/pagerview/Props.h>
 #import <react/renderer/components/pagerview/RCTComponentViewHelpers.h>

```

**Comment by Shahrukh0396** [comment]
@sohayb after applying the change you mentioned above it will return multiple errors of non-void function doesn't return a value

<img width="1179" alt="Screenshot 2024-07-23 at 8 07 48 AM" src="https://github.com/user-attachments/assets/e841b0c9-ca70-4958-9498-7dc15d254d2f">

**Comment by Shahrukh0396** [comment]
well i do have some issues in my current project, so i try it on a fresh one so it works fine. seems like a compatibility issue.

**Comment by MrRefactor** [comment]
make sure to completely erase /node_modules, reinstall packages and run `pod install`

**Comment by Shahrukh0396** [comment]
actually this is first time i am using use_frameworks with new architecture so there are some libraries like rnscreens must need to be updated, btw [this](https://github.com/callstack/react-native-pager-view/issues/843#issuecomment-2237053092) really help and it should be included in next version, thanks.

**Comment by denysoleksiienko** [comment]
same issue

```
ENV['RCT_NEW_ARCH_ENABLED'] =  '1'
use_frameworks! :linkage => :static
```

**Comment by jingp-ofload** [comment]
same here.

**Comment by MrRefactor** [comment]
will be fixed in https://github.com/callstack/react-native-pager-view/pull/863 and released

**Comment by MrRefactor** [comment]
Fixed in https://github.com/callstack/react-native-pager-view/releases/tag/v6.4.0
