### ISSUE TITLE
Very sensitive

### ISSUE THREAD

**Issue by samandarkuchkarov** [callstack/react-native-pager-view#845]
## Describe the feature

i am using react-native-tav-view in android and inside every tab i have flatlist, when i scrolling vertically, users accidently swiping left and right

**Comment by shukerullah** [comment]
Many of our users are having trouble with scrolling. They accidentally swipe left or right when they are trying to scroll up or down. This is happening a lot on Android phones.

This issue is urgent. Can someone please help us find a solution?

**Comment by luca-tomasetti** [comment]
I have the same issue if I add the component inside a flatlist

**Comment by MrRefactor** [comment]
Please provide a repro repository

**Comment by samandarkuchkarov** [comment]
[react-native-tab-view-issue](https://github.com/samandarkuchkarov/react-native-tab-view-issue)
repo @MrRefactor

**Comment by samandarkuchkarov** [comment]
https://github.com/samandarkuchkarov/react-native-tab-view-issue/blob/main/2024-11-21%2010.56.34.mp4

example video

**Comment by MrRefactor** [comment]
Hey, thanks for the repro and video, sadly `PagerView` component that we are using doesnt have API to handle that behaviour, so in that case we cannot handle this issue.

**Comment by wwxxjj2233** [comment]
> ## 描述该功能
> 我在 android 中使用 react-native-tav-view，并且在每个选项卡中我都有平面列表，当我垂直滚动时，用户会意外地向左和向右滑动
> 
> ## 动机
> ## 相关问题

Has anyone resolved this issue? It occurs frequently on Android.
