### ISSUE TITLE
Is it possible to allow gestures on both axes within a `PagerView`

### ISSUE THREAD

**Issue by maxwelljmckee** [callstack/react-native-pager-view#849]
## Ask your Question

Here is a simplified code example:
```js

const NewsFeed = ({ content }) => {
  return (
    <PagerView orientation='vertical'>
      {content.map((item) => (
        <ContentCard>
          <PagerView orientation='horizontal'>
            // y-axis gesture should be unlocked
          </PagerView>
        </ContentCard>
      ))
    </PagerView>
  )
}
```

- I'm working on a `NewsFeed` interface that implements nested `PagerView`s
- The top-level parent/view-container is a `PagerView` with `orientation='vertical'`
- Some children contain a nested horizontal `PagerView` that acts as a content carousel
- I'd like to gesture vertically while touching inside the nested `PagerView` component
- However, I'm finding that the y-axis is locked when gesturing inside the horizontal child pager

Is there a way to unlock both gesture axes inside a pager?

**Comment by trevorpfiz** [comment]
> * I'd like to gesture vertically while touching inside the nested `PagerView` component

I have a similar question of how I can still scroll vertically when this is used in a `ScrollView`

**Comment by ManuLpz4** [comment]
Same here

**Comment by MrRefactor** [comment]
Please check Nest pager view example in repo
