### ISSUE TITLE
Content size not updating correctly on iOS

### ISSUE THREAD

**Issue by QichenZhu** [callstack/react-native-pager-view#852]
## Environment
`react-native`: `0.74.5` (New Architecture)
`react-native-pager-view`: `main` branch

## Description
In the iOS examples, the background does not stretch automatically when the control panel is closed.

Related issue: https://github.com/Expensify/App/issues/41810

https://github.com/user-attachments/assets/3de49fe0-04bd-43e3-894d-c02be3e3d449

## Reproducible Demo
1. Run the iOS examples app.
2. Open the Basic Example.
3. Click the `Control` tab.

**Expected result:** the background should fill the available space.

**Actual result:** a white blank area appears.

**Comment by QichenZhu** [comment]
Close this as the [PR](https://github.com/callstack/react-native-pager-view/pull/853) has been merged.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.3.4
