### ISSUE TITLE
>Task :react-native-pager-view:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by Othern** [callstack/react-native-pager-view#856]
### Environment

- React Native version: 0.75.1
- React Native Pager View version: 6.3.4
- Operating System:  macos

###  Description

After installing `react-native-pager-view`, when I run `npm run android`, I encounter the following error:

```
> Task :react-native-pager-view:compileDebugKotlin FAILED
```

The build fails and I am unable to proceed. How can I resolve this issue?

### Steps to Reproduce

1. Install `react-native-pager-view` by running:
   ```bash
   npm install react-native-pager-view
   ```
2. Run the following command to build the Android project:
   ```bash
   npm run android
   ```
3. Observe the build error message:

   > Task :react-native-pager-view:compileDebugKotlin FAILED
e: file:///Users/wengwulin/Desktop/temp/rn2/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt:72:5 'addView' overrides nothing

FAILURE: Build failed with an exception.

### Expected Behavior

The Android build should complete successfully without any errors.

### Actual Behavior

The build fails with the following error:
```
> Task :react-native-pager-view:compileDebugKotlin FAILED
```
### Additional Information

Any help or guidance on resolving this issue would be greatly appreciated. Thank you!

**Comment by mianala** [comment]
Does the same thing on Windows with Expo SDK 51

**Comment by BrianAutomatize** [comment]
Same.

<img width="748" alt="Screenshot 2024-08-16 at 2 50 39 PM" src="https://github.com/user-attachments/assets/36a1f337-cbbc-4496-95fb-92c66a75f477">

**Comment by SectionTN** [comment]
same, anyone could provide a fix, i guess we are all on 0.75

**Comment by BrianAutomatize** [comment]
might be the react-native-tab-view depenedency, grasping at straws

**Comment by SectionTN** [comment]
@BrianAutomatize i'm not using the tabview dependency

**Comment by SectionTN** [comment]
https://github.com/callstack/react-native-pager-view/issues/850#issuecomment-2271662722
here guys

**Comment by GeoAndrade** [comment]
same error, pls some help for this

**Comment by ShaoGongBra** [comment]
me

**Comment by teckbeng-payboy** [comment]
same error here

**Comment by YuriOlepir** [comment]
same error

**Comment by zkteco-home** [comment]
same

**Comment by samueljim** [comment]
same here

**Comment by eyupdogan** [comment]
same error

**Comment by kbeznisko** [comment]
+1

**Comment by ShivaVarimalla** [comment]
+1

**Comment by ShivaVarimalla** [comment]
Same

**Comment by VikNikolaiev** [comment]
+1

**Comment by ron-zetz** [comment]
+1

**Comment by FernandoAOborges** [comment]
> Same.
> 
> <img alt="Screenshot 2024-08-16 at 2 50 39 PM" width="748" src="https://private-user-images.githubusercontent.com/83730905/358700144-36a1f337-cbbc-4496-95fb-92c66a75f477.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTI5MDcsIm5iZiI6MTcyNDE1MjYwNywicGF0aCI6Ii84MzczMDkwNS8zNTg3MDAxNDQtMzZhMWYzMzctY2JiYy00NDk2LTk1ZmItOTJjNjZhNzVmNDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTllMDAxMWIxNmNhYzhhM2VkODU1YjUxYWUzMmMwMzk0YzFlMTU2YTliY2YzYTVkODllYzgwODE0ZjBlMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4Q_iQPSTs8A1o66znhHiTzpVeR8iUbr1dgvAOOQ7z4">

Same here.

**Comment by pekq** [comment]
You can apply this [`patch-package`](https://github.com/ds300/patch-package) until new version is published: 
`patches/react-native-pager-view+6.3.4.patch`

```diff
diff --git a/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt b/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
index aa974a6..e9c4a52 100644
--- a/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
+++ b/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
@@ -88,7 +88,7 @@ class PagerViewViewManager : ViewGroupManager<NestedScrollableHost>(), RNCViewPa
         return host
     }
 
-    override fun addView(host: NestedScrollableHost, child: View?, index: Int) {
+    override fun addView(host: NestedScrollableHost, child: View, index: Int) {
         PagerViewViewManagerImpl.addView(host, child, index)
     }
 
diff --git a/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt b/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
index 4d0adff..959362c 100644
--- a/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
+++ b/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
@@ -69,7 +69,7 @@ class PagerViewViewManager : ViewGroupManager<NestedScrollableHost>() {
         return host
     }
 
-    override fun addView(host: NestedScrollableHost, child: View?, index: Int) {
+    override fun addView(host: NestedScrollableHost, child: View, index: Int) {
         PagerViewViewManagerImpl.addView(host, child, index)
     }
```

It applies this: https://github.com/callstack/react-native-pager-view/pull/857

**Comment by qiaolao233** [comment]
me too

**Comment by qiaolao233** [comment]
![image](https://github.com/user-attachments/assets/2cd64777-7d3f-4310-834d-ce30863528c7)
me too

**Comment by qiaolao233** [comment]
> You can apply this [`patch-package`](https://github.com/ds300/patch-package) until new version is published: `patches/react-native-pager-view+6.3.4.patch`
> 
> ```diff
> diff --git a/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt b/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
> index aa974a6..e9c4a52 100644
> --- a/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
> +++ b/node_modules/react-native-pager-view/android/src/fabric/java/com/reactnativepagerview/PagerViewViewManager.kt
> @@ -88,7 +88,7 @@ class PagerViewViewManager : ViewGroupManager<NestedScrollableHost>(), RNCViewPa
>          return host
>      }
>  
> -    override fun addView(host: NestedScrollableHost, child: View?, index: Int) {
> +    override fun addView(host: NestedScrollableHost, child: View, index: Int) {
>          PagerViewViewManagerImpl.addView(host, child, index)
>      }
>  
> diff --git a/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt b/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
> index 4d0adff..959362c 100644
> --- a/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
> +++ b/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt
> @@ -69,7 +69,7 @@ class PagerViewViewManager : ViewGroupManager<NestedScrollableHost>() {
>          return host
>      }
>  
> -    override fun addView(host: NestedScrollableHost, child: View?, index: Int) {
> +    override fun addView(host: NestedScrollableHost, child: View, index: Int) {
>          PagerViewViewManagerImpl.addView(host, child, index)
>      }
> ```
> 
> It applies this: #857

it work

**Comment by eehhssaan** [comment]
same

**Comment by SectionTN** [comment]
just use the patch-package guys for now as a temporary fix until the community fix it in the future versions

**Comment by MrRefactor** [comment]
Already merged changes in https://github.com/callstack/react-native-pager-view/pull/857 will release new version soon

**Comment by MrRefactor** [comment]
Fixed in https://github.com/callstack/react-native-pager-view/releases/tag/v6.4.0
