### ISSUE TITLE
Is it an error with rn 0.75.2. addView overrides nothing.

### ISSUE THREAD

**Issue by Firesoul18** [callstack/react-native-pager-view#862]
when I try to run my application I get the following error in building phase:

e: file:///C:/Users/yogid/Desktop/WE%20RNS/indibaba/node_modules/react-native-pager-view/android/src/paper/java/com/reactnativepagerview/PagerViewViewManager.kt:72:5 'addView' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pager-view:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
   
   
The following is my package.json:

```
{
  "name": "indibaba",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "clean": "react-native-clean-project"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/material-top-tabs": "^6.6.14",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@tanstack/react-query": "^5.51.23",
    "axios": "^1.7.3",
    "indibaba": "file:",
    "react": "18.3.1",
    "react-native": "0.75.2",
    "react-native-bootsplash": "^6.1.1",
    "react-native-gesture-handler": "^2.18.1",
    "react-native-mmkv": "^2.12.2",
    "react-native-notifier": "^2.0.0",
    "react-native-pager-view": "^6.3.4",
    "react-native-reanimated": "^3.15.0",
    "react-native-safe-area-context": "^4.10.8",
    "react-native-screens": "^3.34.0",
    "react-native-tab-view": "^3.5.2",
    "zustand": "^4.5.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.75.2",
    "@react-native/eslint-config": "0.75.2",
    "@react-native/metro-config": "0.75.2",
    "@react-native/typescript-config": "0.75.2",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-native-clean-project": "^4.0.3",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}
```
   
I haven't used it yet I just installed `react-native-pager-view` and `@react-navigation/material-top-tabs`. Now I am getting this error

**Comment by MrRefactor** [comment]
Already merged changes in https://github.com/callstack/react-native-pager-view/pull/857 will release new version soon

**Comment by anudit** [comment]
Running into this too, Thanks @MrRefactor !

![image](https://github.com/user-attachments/assets/131a3302-2473-44b0-be74-182ffae4973b)

**Comment by MrRefactor** [comment]
is that with changes from the PR applied? @anudit

**Comment by MrRefactor** [comment]
Fixed in https://github.com/callstack/react-native-pager-view/releases/tag/v6.4.0

**Comment by MrRefactor** [comment]
hey @hakanolgun as for now 7.0.0-rc is no longer supported, all features from 7.0.0 are also in 6.4.0 so I highly encourage you to use that version.
