### ISSUE TITLE
Upgrade to ViewPager2 1.1.0

### ISSUE THREAD

**Issue by adxzhang1** [callstack/react-native-pager-view#879]
## Describe the feature

This for upgrading ViewPager2 to 1.1.0

## Motivation

ViewPager2 1.1.0 includes fix for stuck between tab issue on rotate https://issuetracker.google.com/issues/175796502.

## Related Issues

https://github.com/callstack/react-native-pager-view/issues/744
https://github.com/react-navigation/react-navigation/issues/11473
https://github.com/callstack/react-native-pager-view/issues/692

**Comment by troZee** [comment]
Hi @adxzhang1 ,

Thanks for bringing this issue to our attention! It looks like a great opportunity for improvement. If you have some ideas on how to fix it, we would love to see your contribution. Feel free to create a pull request with your proposed changes.

Don't hesitate to reach out if you need any guidance or have questions along the way. Your efforts would be greatly appreciated and would help make the project even better!

Looking forward to your PR!
