### ISSUE TITLE
When I use this react-native-pager-view in Expo Web it crashes the whole building

### ISSUE THREAD

**Issue by lvlupharshit** [callstack/react-native-pager-view#883]
## Environment
`
"@gorhom/bottom-sheet": "^4.6.4",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "axios": "^1.7.7",
    "expo": "~51.0.36",
    "expo-auth-session": "~5.5.2",
    "expo-clipboard": "~6.0.3",
    "expo-crypto": "~13.0.2",
    "expo-device": "~6.0.2",
    "expo-font": "~12.0.10",
    "expo-image": "~1.13.0",
    "expo-notifications": "~0.28.18",
    "expo-status-bar": "~1.12.1",
    "firebase": "^10.13.1",
    "lottie-react-native": "6.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-dotenv": "^3.4.11",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-pager-view": "6.3.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.10",
    "expo-localization": "~15.0.3",
    "expo-system-ui": "~3.0.7",
    "@expo/metro-runtime": "~3.2.3"
`

## Description

I was using PagerView in my android app using Expo. But Expo also provides web support and when I started my webapp using expo it was not letting me build and giving me error => 

[Unable to resolve "../Utilities/Platform" from "node_modules\react-native\Libraries\ReactPrivate\ReactNativePrivateInterface.js"](https://stackoverflow.com/questions/79052387/unable-to-resolve-utilities-platform-from-node-modules-react-native-librar)

## Reproducible Demo

You just have to write

import PagerView from 'react-native-pager-view';

in a expo project and run it on web. It will give the following error.

Temp Stackoverflow Solution => 

https://stackoverflow.com/questions/79052387/unable-to-resolve-utilities-platform-from-node-modules-react-native-librar

**Comment by troZee** [comment]
Hello 
The pager does not support the web platform. To ensure consistent behavior across all platforms, please implement a solution that returns an empty component for the web application

**Comment by bpeck81** [comment]
Yeah it's crazy to crash the whole web app by importing a package.
