### ISSUE TITLE
[iOS] v7.0.0 doesn't work with the New Architecture

### ISSUE THREAD

**Issue by darecki** [callstack/react-native-pager-view#890]
## Environment
Xcode 16.0
```
  "dependencies": {
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-pager-view": "7.0.0-rc.2"
  },
```
## Description
When I try to upgrade to v7.0.0 the app won't compile with the new architecture enabled. 
<img width="609" alt="xcode-errors" src="https://github.com/user-attachments/assets/12b6348f-28f1-4349-92e0-5241bba3ff97">

## Reproducible Demo
To reprocude you can create a new react native project and add the lib to it.
```
npx @react-native-community/cli@latest init PagerViewTest
cd PagerViewTest
yarn add react-native-pager-view@7.0.0-rc.2
cd ios
RCT_NEW_ARCH_ENABLED=1 pod install
```
Now open Xcode and try to build.

**Comment by efstathiosntonas** [comment]
@darecki I think v7 (released on March https://github.com/callstack/react-native-pager-view/pull/817) is way behind v6 and v6 has many Fabric fixes

**Comment by troZee** [comment]
@darecki it is dropped because I cannot find time to finish that. This library has been merged into the main branch and can be used by changing this prop https://github.com/callstack/react-native-pager-view/blob/master/src/PagerView.tsx#L174
