### ISSUE TITLE
app getting crash on version 0.76

### ISSUE THREAD

**Issue by Rohit144401** [callstack/react-native-pager-view#891]
https://github.com/user-attachments/assets/0d325e6d-8257-4268-973a-a73070465c16

![Image](https://github.com/user-attachments/assets/7ade10b5-ff0e-44f4-b5b1-12b32b105ef6)

repo for reproducing https://github.com/Rohit144401/test.git

**Comment by parsable-osiel** [comment]
Do we have any answer on this? facing same issue

**Comment by troZee** [comment]
Duplicated
