### ISSUE TITLE
libreact-native-viewpager incompatibility

### ISSUE THREAD

**Issue by Algonzbao** [callstack/react-native-pager-view#893]
## Environment

iOS Build

## Description

After trying several attemps for creating an iOS build I get this [error:]

 ld: ignoring duplicate libraries: '-lc++'
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollEvent._position' in
┌─ libreact-native-pager-view.a[3](RCTOnPageScrollEvent.o)
└─ libreact-native-viewpager.a[4](RCTOnPageScrollEvent.o)
❌  duplicate symbol '_OBJC_CLASS_$_RCTOnPageScrollStateChanged' in
┌─ libreact-native-pager-view.a[4](RCTOnPageScrollStateChanged.o)
└─ libreact-native-viewpager.a[5](RCTOnPageScrollStateChanged.o)
❌  duplicate symbol '_OBJC_CLASS_$_RCTOnPageSelected' in
┌─ libreact-native-pager-view.a[5](RCTOnPageSelected.o)
└─ libreact-native-viewpager.a[6](RCTOnPageSelected.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollStateChanged._viewTag' in
┌─ libreact-native-pager-view.a[4](RCTOnPageScrollStateChanged.o)
└─ libreact-native-viewpager.a[5](RCTOnPageScrollStateChanged.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollStateChanged._coalescingKey' in
┌─ libreact-native-pager-view.a[4](RCTOnPageScrollStateChanged.o)
└─ libreact-native-viewpager.a[5](RCTOnPageScrollStateChanged.o)
❌  duplicate symbol '_OBJC_METACLASS_$_RCTOnPageSelected' in
┌─ libreact-native-pager-view.a[5](RCTOnPageSelected.o)
└─ libreact-native-viewpager.a[6](RCTOnPageSelected.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollEvent._viewTag' in
┌─ libreact-native-pager-view.a[3](RCTOnPageScrollEvent.o)
└─ libreact-native-viewpager.a[4](RCTOnPageScrollEvent.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollEvent._offset' in
┌─ libreact-native-pager-view.a[3](RCTOnPageScrollEvent.o)
└─ libreact-native-viewpager.a[4](RCTOnPageScrollEvent.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageSelected._coalescingKey' in
┌─ libreact-native-pager-view.a[5](RCTOnPageSelected.o)
└─ libreact-native-viewpager.a[6](RCTOnPageSelected.o)
❌  duplicate symbol '_OBJC_METACLASS_$_RCTOnPageScrollStateChanged' in
┌─ libreact-native-pager-view.a[4](RCTOnPageScrollStateChanged.o)
└─ libreact-native-viewpager.a[5](RCTOnPageScrollStateChanged.o)
❌  duplicate symbol '_OBJC_METACLASS_$_RCTOnPageScrollEvent' in
┌─ libreact-native-pager-view.a[3](RCTOnPageScrollEvent.o)
└─ libreact-native-viewpager.a[4](RCTOnPageScrollEvent.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageScrollStateChanged._state' in
┌─ libreact-native-pager-view.a[4](RCTOnPageScrollStateChanged.o)
└─ libreact-native-viewpager.a[5](RCTOnPageScrollStateChanged.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageSelected._position' in
┌─ libreact-native-pager-view.a[5](RCTOnPageSelected.o)
└─ libreact-native-viewpager.a[6](RCTOnPageSelected.o)
❌  duplicate symbol '_OBJC_IVAR_$_RCTOnPageSelected._viewTag' in
┌─ libreact-native-viewpager.a[4](RCTOnPageScrollEvent.o)
└─ libreact-native-pager-view.a[5](RCTOnPageSelected.o)

❌  ld: 15 duplicate symbols

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Reproducible Demo
This is the status of my package.json, I know I am currently on 7.0.0 rc.0 but I have also tried rc.1 and rc.2 and the same issue persists.
`{
	"scripts": {
		"auth": "",
		"start": "npx expo start",
		"android": "npx expo run:android",
		"ios": "npx expo run:ios",
		"eject": "npx expo eject",
		"test": "jest"
	},
	"dependencies": {
		"@expo-google-fonts/montserrat": "^0.1.0",
		"@expo-google-fonts/roboto": "^0.2.3",
		"@expo/vector-icons": "^14.0.0",
		"@hirbod/react-native-material-textfield": "^1.0.2",
		"@react-native-async-storage/async-storage": "1.23.1",
		"@react-native-community/viewpager": "^5.0.11",
		"@react-navigation/material-top-tabs": "^6.2.1",
		"@react-navigation/native": "^6.1.6",
		"@react-navigation/stack": "^6.3.10",
		"@rneui/base": "^4.0.0-rc.7",
		"@rneui/themed": "^4.0.0-rc.7",
		"babel-plugin-inline-dotenv": "^1.7.0",
		"expo": "~51.0.21",
		"expo-auth-session": "~5.5.2",
		"expo-camera": "~15.0.14",
		"expo-clipboard": "~6.0.3",
		"expo-contacts": "~13.0.4",
		"expo-crypto": "~13.0.2",
		"expo-dev-client": "~4.0.20",
		"expo-device": "~6.0.2",
		"expo-image-manipulator": "~12.0.5",
		"expo-image-picker": "~15.0.7",
		"expo-linking": "~6.3.1",
		"expo-localization": "~15.0.3",
		"expo-notifications": "~0.28.10",
		"expo-random": "~14.0.1",
		"expo-splash-screen": "~0.27.5",
		"expo-status-bar": "~1.12.1",
		"expo-updates": "~0.25.20",
		"expo-web-browser": "~13.0.3",
		"formik": "^2.2.6",
		"i18next": "^22.0.2",
		"lodash": "^4.17.15",
		"lottie-react-native": "6.7.0",
		"metro-react-native-babel-transformer": "^0.77.0",
		"moment": "^2.29.4",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-i18next": "^12.0.0",
		"react-native": "0.74.3",
		"react-native-app-intro-slider": "^4.0.4",
		"react-native-base64": "^0.2.1",
		"react-native-config": "^1.5.0",
		"react-native-gesture-handler": "~2.16.1",
		"react-native-pager-view": "7.0.0-rc.0",
		"react-native-qrcode-svg": "^6.2.0",
		"react-native-reanimated": "~3.10.1",
		"react-native-render-html": "^6.3.1",
		"react-native-safe-area-context": "4.10.1",
		"react-native-screens": "3.31.1",
		"react-native-shadow-2": "^7.0.7",
		"react-native-snap-carousel": "^3.9.1",
		"react-native-svg": "15.2.0",
		"react-native-svg-transformer": "^0.14.3",
		"react-native-tab-view": "^3.5.2",
		"react-native-web": "~0.19.6",
		"react-native-webview": "13.8.6",
		"react-query": "^3.19.4",
		"react-timer-mixin": "0.13.4",
		"yup": "^0.32.9",
		"zustand": "^3.5.7"
	},
	"devDependencies": {
		"@babel/core": "^7.24.0",
		"@typescript-eslint/eslint-plugin": "^5.38.0",
		"@typescript-eslint/parser": "^5.38.0",
		"babel-plugin-module-resolver": "^5.0.2",
		"babel-preset-expo": "~11.0.0",
		"eslint": "^8.23.1",
		"eslint-config-universe": "^11.1.0",
		"jest": "^29.2.1",
		"prettier": "^2.7.1",
		"ts-node-dev": "^2.0.0",
		"typescript": "~5.3.3"
	},
	"private": true,
	"eslintConfig": {
		"extends": "universe/native",
		"settings": {
			"import/ignore": [
				"react-native"
			]
		}
	},
	"name": "",
	"version": "7.1"
}
`

I will be extremly grateful with any assistance or guidance.

Thank you

**Comment by MrRefactor** [comment]
Please dont use rc7, use 6.4.1 instead
