### ISSUE TITLE
ERROR  Invariant Violation: requireNativeComponent: "LEGACY_RNCViewPager" was not found in the UIManager.

### ISSUE THREAD

**Issue by just-myself** [callstack/react-native-pager-view#894]
## Environment
	"react": "18.2.0",
         "react-native": "0.74.5",
         "react-native-pager-view": "^6.4.1",
         "react-native-tab-view": "^3.5.2",

## Description
{
	"name": "react_native_template",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"lint": "eslint .",
		"start": "react-native start --experimental-debugger --reset-cache",
		"test": "jest",
		"asset": "npx react-native-asset",
		"prepare": "husky",
		"lint:eslint": "eslint --ext .js,.jsx,.ts,.tsx,.json, --fix --quiet ./src",
		"lint:lint-staged": "lint-staged"
	},
	"dependencies": {
		"@ant-design/icons-react-native": "^2.3.2",
		"@ant-design/react-native": "^5.2.2",
		"@gorhom/bottom-sheet": "^4",
		"@react-navigation/bottom-tabs": "^6.6.1",
		"@react-navigation/material-top-tabs": "^6.6.14",
		"@react-navigation/native": "^6.1.18",
		"@react-navigation/native-stack": "^6.11.0",
		"ahooks": "^3.8.1",
		"babel-plugin-module-resolver": "^5.0.2",
		"dayjs": "^1.11.13",
		"immer": "^10.1.1",
		"jcore-react-native": "^2.2.1",
		"jpush-react-native": "^3.1.0",
		"ky": "^1.6.0",
		"lodash": "^4.17.21",
		"lottie-react-native": "^6.7.2",
		"mitt": "^3.0.1",
		"pinyin": "^3.1.0",
		"react": "18.2.0",
		"react-native": "0.74.5",
		"react-native-asset": "^2.1.1",
		"react-native-big-list": "^1.6.1",
		"react-native-canvas": "^0.1.40",
		"react-native-device-info": "^11.1.0",
		"react-native-dotenv": "^3.4.11",
		"react-native-fast-image": "^8.6.3",
		"react-native-fs": "^2.20.0",
		"react-native-gesture-handler": "^2.18.1",
		"react-native-image-picker": "^7.1.2",
		"react-native-image-zoom-viewer": "^3.0.1",
		"react-native-linear-gradient": "^2.8.3",
		"react-native-loading-spinner-overlay": "^3.0.1",
		"react-native-mmkv": "^2.12.2",
		"react-native-pager-view": "^6.4.1",
		"react-native-photo-manipulator": "^1.7.2",
		"react-native-reanimated": "^3.15.2",
		"react-native-safe-area-context": "^4.10.8",
		"react-native-screens": "^3.34.0",
		"react-native-signature-canvas": "^4.7.2",
		"react-native-tab-view": "^3.5.2",
		"react-native-toast-message": "^2.2.0",
		"react-native-vision-camera": "^4.5.2",
		"react-native-webview": "^13.12.3",
		"ysir-rn-amap-geolocation": "^1.0.2",
		"ysir-rn-amap3d": "^1.0.1",
		"zustand": "^4.5.4"
	},
	"devDependencies": {
		"@babel/core": "^7.20.0",
		"@babel/preset-env": "^7.20.0",
		"@babel/runtime": "^7.20.0",
		"@commitlint/cli": "^19.5.0",
		"@commitlint/config-conventional": "^19.5.0",
		"@react-native/babel-preset": "0.74.87",
		"@react-native/eslint-config": "0.74.87",
		"@react-native/metro-config": "0.74.87",
		"@react-native/typescript-config": "0.74.87",
		"@types/lodash": "^4.17.12",
		"@types/react": "^18.2.6",
		"@types/react-test-renderer": "^18.0.0",
		"babel-jest": "^29.6.3",
		"eslint": "^8.19.0",
		"husky": "^9.1.6",
		"jest": "^29.6.3",
		"lint-staged": "^15.2.10",
		"prettier": "2.8.8",
		"react-test-renderer": "18.2.0",
		"reactotron-react-native": "^5.1.8",
		"typescript": "5.0.4"
	},
	"engines": {
		"node": ">=18"
	},
	"lint-staged": {
		"*.{js,jsx,tsx,ts,json,md}": [
			"prettier --write"
		]
	},
	"husky": {
		"hooks": {
			"pre-commit": "lint:lint-staged",
			"commit-msg": "commitlint"
		}
	}
}

## Reproducible Demo
ERROR  Invariant Violation: requireNativeComponent: "LEGACY_RNCViewPager" was not found in the UIManager.

This error is located at:
    in LEGACY_RNCViewPager (created by PagerViewInternal)
    in PagerViewInternal
    in Unknown (created by XZLTabs)
    in XZLTabs (created by ContractList)
    in RNCSafeAreaView
    in Unknown (created by PageLayout)
    in PageLayout (created by ContractList)
    in ContractList (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by ApplicationNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ApplicationNavigator)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by ConfigProvider)
    in ThemeProvider (created by ConfigProvider)
    in LocaleProvider (created by ConfigProvider)
    in ConfigProvider (created by ApplicationNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by ApplicationNavigator)
    in ApplicationNavigator (created by App)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in ThemeProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in react_native_template(RootComponent), js engine: hermes

Follow the official use case practice and report an error directly.

**Comment by just-myself** [comment]
I built the project using cli​
It was carried out according to the official usage method in the project​
yarn add react-native-tab-view​
yarn add react-native-pager-view​
​
Use Quick start sample code to report an error in the project

**Comment by Medkhat** [comment]
+ Same here

**Comment by Medkhat** [comment]
@just-myself Did you rebuild your project? If not, clear cache and rebuild, mb will work:)

**Comment by MrRefactor** [comment]
> @just-myself Did you rebuild your project? If not, clear cache and rebuild, mb will work:)

Did you resolve the issue by rebuilding?

**Comment by Medkhat** [comment]
@MrRefactor Yes, I did
