### ISSUE TITLE
can not scroll when switch lang to Arabic in ios

### ISSUE THREAD

**Issue by LuckyRoc** [callstack/react-native-pager-view#900]
## Environment

6.5.0

## Description

RLT not work ,can not scroll

## Reproducible Demo

```
import React from 'react';
import { StyleSheet, View, Text } from 'react-native';
import PagerView from 'react-native-pager-view';

const MyPager = () => {
  return (
    <PagerView style={styles.pagerView} initialPage={0}>
      <View key="1">
        <Text>First page</Text>
      </View>
      <View key="2">
        <Text>Second page</Text>
      </View>
    </PagerView>
  );
};

const styles = StyleSheet.create({
  pagerView: {
    flex: 1,
  },
});
```

**Comment by MrRefactor** [comment]
Hey, is it new arch or old arch?

**Comment by DrRefactor** [comment]
Hello, I've tested both fabric and non-fabric rn-pager-view, neither reproduces the issue on iOS. I use provided code in react-native-pager-view/example:

Fabric:
![Image](https://github.com/user-attachments/assets/2037942e-8622-4002-9853-36f61a67e3f0)

Fabric disabled:
![Image](https://github.com/user-attachments/assets/dd6115e9-e49d-466d-93ad-a727c0dd22cd)

@LuckyRoc did you face the problem on iOS or Android?

**Comment by DrRefactor** [comment]
I also tested android, scroll works fine on RTL:
![Image](https://github.com/user-attachments/assets/e4676cec-0dc5-4412-ae61-7e790478d7f2)

**Comment by LuckyRoc** [comment]
![Image](https://github.com/user-attachments/assets/af0f5225-b308-4736-8fe5-d16f7f9154d7)
https://github.com/user-attachments/assets/b45aa309-b687-4627-b13d-1a17d3caa9e3

**Comment by MrRefactor** [comment]
Please provide repro repo.

**Comment by DrRefactor** [comment]
I have Arabic iOS simulator, works exactly like in my gifs above 🤔 both LTR and RTL work perfectly fine.
