### ISSUE TITLE
Component layout size calculation errors

### ISSUE THREAD

**Issue by meftunca** [callstack/react-native-pager-view#902]
## Environment

```bash
System:
  OS: macOS 15.0.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 157.67 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/mapletechnologies/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mapletechnologies/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

## Description

I am using react-navigation and react-native-paper in my react native project. After switching between pages in my project, the appearance of react-native and react-native-paper components is broken. I am sharing 2 images below. 1. the corrupted version of the image and 2. the expected version
Below are the problem links related to this issue
https://github.com/facebook/react-native/issues/47420
https://github.com/facebook/react-native/issues/47410
I use React native,react-native-screens,reanimated,gesture-handler,react-navigation, expo(preview-21) and the latest version of your library 

## Reproducible Demo

Unfortunately I don't have a testable repo at the moment

**Comment by richardbutler** [comment]
Just adding a +1 here and following as the author of one of the above referenced issues https://github.com/facebook/react-native/issues/47410

**Comment by rarira** [comment]
it affects mainly <View /> components with borderRadius syle.
You can find same layout broken even in the Insepector menu as belows

https://github.com/user-attachments/assets/9025b7ff-fe1f-411e-94d5-251ea5949c88

**Comment by meftunca** [comment]
Why don't the project owners inform us about the solution under this problem?

**Comment by TyshkevichSergey** [comment]
Just want to +1 this issue. Experiencing similar behavior as @meftunca. After figuring out the problem, I noticed that it starts happening when I open any route that contains react-native-tab-view (which uses react-native-pager-view). Random components styled with round borders(borderRadius) become broken and are change shapes. Problem doesn't occur if react-native-pager-view isn't used within the app. It's really hard to debug - so it's just based on my guess and a number of tests

**Comment by Chenjiujiu** [comment]
https://snack.expo.dev/@saddhu/demo002

https://github.com/facebook/react-native/issues/47668

**Comment by MrRefactor** [comment]
fixed in https://github.com/callstack/react-native-pager-view/releases/tag/v6.5.1

**Comment by richardbutler** [comment]
Confirmed this is now fixed. Thanks for your help, @MrRefactor.

**Comment by julian-gargicevich** [comment]
@MrRefactor What can cause such an issue? I'm having a very similar problem but not using react-native-pager-viewer, and I'm having a hard time debugging it and finding the root cause.
