### ISSUE TITLE
Build issues on Android ( Failed to transform viewpager2-1.1.0.aar)

### ISSUE THREAD

**Issue by tdammy92** [callstack/react-native-pager-view#905]
Platform :Android
React-native version:0.71.4
react-native-pager-view: ^6.2.0,

This is the current version that has been in use for more than a year but we noticed android builds failing on App-center, so we re-installed node-modules and cleared cache and stared getting this locally also.

any help will be much appreciated 🙏.

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDevDebug'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Failed to transform viewpager2-1.1.0.aar (androidx.viewpager2:viewpager2:1.1.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/tdammyy/.gradle/caches/transforms-3/49b6b92093e08df364987a01589d626b/transformed/jetified-viewpager2-1.1.0-runtime.jar.
         > Error while dexing.

`

**Comment by troZee** [comment]
I am not able to reproduce that. Please provide a repository, where I can see that error

**Comment by satyabrata-dash5** [comment]
same issue here.Please help how to solve it

**Comment by kartikbhalla12** [comment]
same issue here!

**Comment by LouisMuriuki** [comment]
Same issue, any quantifiable workarounds?

**Comment by MrRefactor** [comment]
As @troZee stated, please provide a repository where we can reproduce that issue.

**Comment by Franklyn-luupli** [comment]
i'm facing same isse here on my end

**Comment by MrRefactor** [comment]
to resolve it for now please use 

`react-native-pager-view: 6.4.1`

**Comment by tdammy92** [comment]
> to resolve it for now please use
> 
> `react-native-pager-view: 6.4.1`

@MrRefactor this worked for me, i used the exact version and it worked.   @satyabrata-dash5 try the exam version 
`"react-native-pager-view": "6.4.1",`

**Comment by Andre-Favero** [comment]
same issue here

**Comment by Locntt** [comment]
same issues. im change to this version but still got the error like above 
`react-native-pager-view: 6.4.1
`

**Comment by MishantBagariya** [comment]
this issue is still there with 6.5.1

**Comment by MrRefactor** [comment]
Please provide a reproduction repository @MishantBagariya

**Comment by MishantBagariya** [comment]
@MrRefactor version info -

distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip,
"react-native": "0.72.5",
"react-native-collapsible-tab-view": "^8.0.0",
"react-native-pager-view": "^6.5.1",
buildToolsVersion = "33.0.0"
minSdkVersion = 24
compileSdkVersion = 34
targetSdkVersion = 34
kotlin_version = '1.8.20'
// We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
ndkVersion = "23.1.7779620"

**Comment by MrRefactor** [comment]
> to resolve it for now please use
> 
> `react-native-pager-view: 6.4.1`

@MishantBagariya

**Comment by MishantBagariya** [comment]
> > to resolve it for now please use
> > `react-native-pager-view: 6.4.1`
> 
> [@MishantBagariya](https://github.com/MishantBagariya)

was using this only earlier react-native-pager-view: 6.4.1, this is not working, build started to fail suddenly then tried to upgrade, BUT even that not worked.

**Comment by MrRefactor** [comment]
> > > to resolve it for now please use
> > > `react-native-pager-view: 6.4.1`
> > 
> > [@MishantBagariya](https://github.com/MishantBagariya)
> 
> was using this only earlier react-native-pager-view: 6.4.1, this is not working, build started to fail suddenly then tried to upgrade, BUT even that not worked.

In that case please provide repro repository

**Comment by MishantBagariya** [comment]
@MrRefactor I understand that having a reproduction repository is crucial for debugging the issue. Unfortunately, my project contains proprietary code or data that I’m unable to share publicly or even privately.

Could you pls try to reproduce issue on same versions of react-native as I shared in prev replies ? I believe this will help isolate the problem quickly. Thanks!

**Comment by MrRefactor** [comment]
> [@MrRefactor](https://github.com/MrRefactor) I understand that having a reproduction repository is crucial for debugging the issue. Unfortunately, my project contains proprietary code or data that I’m unable to share publicly or even privately.
> 
> Could you pls try to reproduce issue on same versions of react-native as I shared in prev replies ? I believe this will help isolate the problem quickly. Thanks!

Please create repro repo with basic setup and dependencies version.

**Comment by shoaibarif244** [comment]
Thanks @MrRefactor

**Comment by MishantBagariya** [comment]
@shoaibarif244 working for you ? if yes, Can you pls share ur react-native & react-native-pager-view versions ?

**Comment by MrRefactor** [comment]
> [@shoaibarif244](https://github.com/shoaibarif244) working for you ? if yes, Can you pls share ur react-native & react-native-pager-view versions ?

make sure you use exactly: `"react-native-pager-view": "6.4.1"`, not `"react-native-pager-view": "^6.4.1"`

**Comment by shoaibarif244** [comment]
> [@shoaibarif244](https://github.com/shoaibarif244) working for you ? if yes, Can you pls share ur react-native & react-native-pager-view versions ?
@MishantBagariya , Yes sure.
```
"react-native": "0.72.5"
"react-native-pager-view": "6.4.1"
```

**Comment by Locntt** [comment]
```
same issues. im change to this version but still got the error like above
react-native-pager-view: 6.4.1 


```
I can install now, thanks guys <3.

**Comment by MrRefactor** [comment]
> > same issues. im change to this version but still got the error like above
> > react-native-pager-view: 6.4.1
> 
> I can install now, thanks guys <3.

did you change anything?

**Comment by Locntt** [comment]
@MrRefactor maybe i forgot delete node_modules at that time
im using :
```
react-native: 0.71.11
react-native-pager-view: 6.4.1
```

**Comment by wassiq** [comment]
> to resolve it for now please use
> 
> `react-native-pager-view: 6.4.1`

I confirmed it is working with react native 0.71.10.
Thank You 👍🏻

**Comment by iphonic** [comment]
> to resolve it for now please use
> 
> `react-native-pager-view: 6.4.1`


Thanks it works, I am using "react-native": "^0.73.6"

**Comment by redionSpace** [comment]
"react-native-pager-view": "6.4.1"
This seemed to have worked

**Comment by Tanmay-97** [comment]
Confirmed, works in RN 0.71.8 with

`"react-native-pager-view": "6.4.1"
`

I also had to remove carets (^) from other dependent libraries (waiting for the day this truly makes sense to me)

Nuke the project if you have to:
```
rm -rf node_modules package-lock.json android/.gradle
npm install
cd android && ./gradlew clean
./gradlew build --refresh-dependencies
cd..
npx react-native run-android
```

**Comment by mutaharmaqbool** [comment]
> to resolve it for now please use
> 
> `react-native-pager-view: 6.4.1`

Worked this solution
