### ISSUE TITLE
useViewPager hook

### ISSUE THREAD

**Issue by x0s3** [callstack/react-native-pager-view#92]
# Feature Request

Expose a hook to access to the ViewPager from components inside it

## Why it is needed

Imagine that you need to move programmatically from Page 1 to Page 3, using that hook users can handle those escenarios easily (just an example)

### Code sample

```javascript
import { useViewPager } from '@react-native-community/viewpager';

function View1() {
   const { setPage, setPageWithoutAnimation } = useViewPager();

  useEffect(() => {
     setPage(pageToMove);
   }, 
   [propWeListenForChangeCurrentPage]);

   return (
      ...
   )
}
```

Feel free to close if is not needed or useful 😄

**Comment by MrRefactor** [comment]
Implemented, please uise latest version.
