### ISSUE TITLE
[Android]: Tab Label Status Incorrect When Switching Tabs

### ISSUE THREAD

**Issue by hapo-nghialuu** [callstack/react-native-pager-view#920]
## Environment
Android
Packages:
```
"expo": "^52.0.8",
"react-native": "0.76.2",
"react-native-pager-view": "6.5.1",
"react-native-tab-view": "^4.0.2"
```

## Description

I'm encountering an issue on Android devices where the tab label status is incorrect when switching between tabs.

This issue appeared after upgrading to Expo 52, along with the latest versions of @react-navigation/native (^7.0.0) and react-native-tab-view (^4.0.2).

The problem did not occur with Expo version 51, @react-navigation/native (^6.0.2), and react-native-tab-view (^3.5.2).

Please refer to the video for a demonstration of the issue.
https://github.com/user-attachments/assets/e3d4dd9c-ae0c-4116-af38-271f0353cb1d

## Expected
Tab label status show correctly with Expo 52

**Comment by hapo-nghialuu** [comment]
```
const renderTabBar = (props: any) => {
  return (
    <TabBar
      {...props}
      indicatorStyle={{ backgroundColor: 'blue' }}
      style={{
        backgroundColor: 'white',
      }}
      activeColor="blue"
      inactiveColor="gray"
      scrollEnabled={true}
      tabStyle={{ width: 100 }}
    />
  );
};

<TabView
          lazy
          navigationState={{ index, routes }}
          renderScene={renderScene}
          onIndexChange={setIndex}
          renderTabBar={renderTabBar}
          initialLayout={{
            width: layout.width,
          }}
        />
```

I realize that the issue occurs when using renderTabBar, otherwise, it doesn't happen.

**Comment by MrRefactor** [comment]
Please report it to `react-native-tab-view` as it looks like its not related to pager
