### ISSUE TITLE
Implement Page Indicator on Android

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-pager-view#94]
# Feature Request
When `showPageIndicator` prop is true, indicators should be shown on Android. Take a look at example

## Why it is needed
Because this is already implemented on iOS and we want to keep consistency between two platforms.  

## How to implement it
it should look in this way 

![Simulator Screen Shot - iPhone 8 - 2019-11-02 at 18 22 07](https://user-images.githubusercontent.com/12766071/68074657-c2b75b80-fd9d-11e9-87a8-5ef3b6154e9b.png)

**Comment by hannahcx** [comment]
Any update on this? I cannot use your library in my app because of this defect.

**Comment by tinydiv333** [comment]
Any update? I want to use this library but because of this i can't

**Comment by troZee** [comment]
Hey, 
Now I have limited amount of time to implement it. As workaround you can use external lib https://github.com/tsepeti/react-native-dots-pagination. It is easy to integrate with VP. 

PR's are welcome.

**Comment by krozniata** [comment]
Closing because support for `showPageIndicator` on iOS will be dropped in version **6.1.0**
