### ISSUE TITLE
v6.6.1 missing auto-linking

### ISSUE THREAD

**Issue by tu-buuuk** [callstack/react-native-pager-view#950]
## Environment

```
"react-native-pager-view": "^6.6.1",
"react-native": "0.74.1",
```

## Description

I got this issue when trying to run the app.
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/9e1573a7-8a9a-4717-97f4-29a1c31aa52b" />

Note: It worked well after I tried to link the package manually.

## Expectation

Please help to make sure that the auto-linking work well

**Comment by troZee** [comment]
Hello 👋 
Please checkout our example. I cannot reproduce it there. It seems the local setup is broken.
